PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS mastery_strands (
    code TEXT PRIMARY KEY, name TEXT NOT NULL, sort_order INTEGER NOT NULL UNIQUE
  );

CREATE TABLE IF NOT EXISTS mastery_skills (
    code TEXT PRIMARY KEY, name TEXT NOT NULL,
    strand_code TEXT NOT NULL REFERENCES mastery_strands(code) ON DELETE RESTRICT,
    sort_order INTEGER NOT NULL UNIQUE
  );

CREATE TABLE IF NOT EXISTS mastery_levels (
    id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL,
    strand_code TEXT NOT NULL REFERENCES mastery_strands(code) ON DELETE RESTRICT,
    skill_code TEXT NOT NULL REFERENCES mastery_skills(code) ON DELETE RESTRICT,
    sequence_index INTEGER NOT NULL UNIQUE CHECK (sequence_index BETWEEN 1 AND 210),
    tier TEXT NOT NULL CHECK (tier IN ('CORE','EXT')),
    time_standard_seconds INTEGER CHECK (time_standard_seconds > 0),
    accuracy_threshold INTEGER NOT NULL DEFAULT 90 CHECK (accuracy_threshold BETWEEN 0 AND 100),
    video_url TEXT NOT NULL DEFAULT ''
  );

CREATE TABLE IF NOT EXISTS mastery_worksheets (
    id TEXT PRIMARY KEY,
    level_id TEXT NOT NULL REFERENCES mastery_levels(id) ON DELETE CASCADE,
    worksheet_index INTEGER NOT NULL CHECK (worksheet_index BETWEEN 1 AND 5),
    worksheet_type TEXT NOT NULL CHECK (worksheet_type IN ('PRACTICE','MIXED','MASTERY_CHECK')),
    UNIQUE (level_id, worksheet_index)
  );

CREATE TABLE IF NOT EXISTS mastery_problems (
    id TEXT PRIMARY KEY,
    worksheet_id TEXT NOT NULL REFERENCES mastery_worksheets(id) ON DELETE CASCADE,
    band TEXT NOT NULL CHECK (band IN ('FLUENCY','APPLIED','SAT')),
    position INTEGER NOT NULL CHECK (position > 0), stem TEXT NOT NULL, answer TEXT NOT NULL,
    answer_format TEXT NOT NULL CHECK (answer_format IN ('MC','SPR')),
    choices TEXT NOT NULL DEFAULT '[]', solution_explanation TEXT NOT NULL DEFAULT '',
    desmos_enabled INTEGER NOT NULL DEFAULT 0 CHECK (desmos_enabled IN (0,1)),
    UNIQUE (worksheet_id, band, position)
  );

CREATE TABLE IF NOT EXISTS mastery_students (
    id TEXT PRIMARY KEY, display_name TEXT NOT NULL DEFAULT 'Student',
    placement_level_index INTEGER NOT NULL DEFAULT 1 CHECK (placement_level_index BETWEEN 1 AND 210),
    current_level_id TEXT NOT NULL REFERENCES mastery_levels(id) ON DELETE RESTRICT,
    daily_page_target INTEGER NOT NULL DEFAULT 3 CHECK (daily_page_target > 0),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS mastery_attempts (
    id TEXT PRIMARY KEY,
    student_id TEXT NOT NULL REFERENCES mastery_students(id) ON DELETE CASCADE,
    worksheet_id TEXT NOT NULL REFERENCES mastery_worksheets(id) ON DELETE RESTRICT,
    started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, submitted_at TEXT,
    elapsed_seconds INTEGER, score REAL, passed INTEGER CHECK (passed IN (0,1)),
    answers TEXT NOT NULL DEFAULT '[]'
  );

CREATE TABLE IF NOT EXISTS mastery_records (
    student_id TEXT NOT NULL REFERENCES mastery_students(id) ON DELETE CASCADE,
    level_id TEXT NOT NULL REFERENCES mastery_levels(id) ON DELETE CASCADE,
    attempts_count INTEGER NOT NULL DEFAULT 0 CHECK (attempts_count >= 0),
    mastered_at TEXT, last_reviewed_at TEXT,
    PRIMARY KEY (student_id, level_id)
  );

CREATE INDEX IF NOT EXISTS idx_mastery_levels_strand_sequence ON mastery_levels(strand_code, sequence_index);

CREATE INDEX IF NOT EXISTS idx_mastery_levels_skill_sequence ON mastery_levels(skill_code, sequence_index);

CREATE INDEX IF NOT EXISTS idx_mastery_worksheets_level_index ON mastery_worksheets(level_id, worksheet_index);

CREATE INDEX IF NOT EXISTS idx_mastery_problems_worksheet_band_position ON mastery_problems(worksheet_id, band, position);

CREATE INDEX IF NOT EXISTS idx_mastery_attempts_student_worksheet_active ON mastery_attempts(student_id, worksheet_id, submitted_at);

CREATE INDEX IF NOT EXISTS idx_mastery_records_student_reviewed ON mastery_records(student_id, last_reviewed_at);

INSERT OR IGNORE INTO mastery_strands (code,name,sort_order) VALUES
('F','Foundations','1'),
('A','Algebra','2'),
('S','Strategy','3'),
('P','Grid-in / student-produced response','4'),
('M','Advanced Math','5'),
('D','Problem-Solving & Data Analysis','6'),
('G','Geometry & Trigonometry','7'),
('X','Desmos technique','8');

INSERT OR IGNORE INTO mastery_skills (code,name,strand_code,sort_order) VALUES
('F1','Number fluency','F','1'),
('F2','Expressions','F','2'),
('F3','Equation moves','F','3'),
('F4','Coordinate & graph reading','F','4'),
('A1','Linear equations in one variable','A','5'),
('A2','Linear equations in two variables','A','6'),
('X','Desmos technique','X','7'),
('A3','Linear functions','A','8'),
('A4','Systems of two linear equations','A','9'),
('A5','Linear inequalities','A','10'),
('S1','Decoding the question','S','11'),
('S2','Answer-choice techniques','S','12'),
('S3','Pacing and triage','S','13'),
('P1','Grid-in / student-produced response','P','14'),
('M1','Equivalent expressions','M','15'),
('M2','Nonlinear equations & systems','M','16'),
('M3','Nonlinear functions','M','17'),
('D1','Ratios, rates, proportional relationships, units','D','18'),
('D2','Percentages','D','19'),
('D3','One-variable data','D','20'),
('D4','Two-variable data','D','21'),
('D5','Probability and conditional probability','D','22'),
('D6','Inference and margin of error','D','23'),
('D7','Evaluating statistical claims','D','24'),
('G1','Lines, angles, triangles','G','25'),
('G3','Area and volume','G','26'),
('G2','Right triangles and trigonometry','G','27'),
('G4','Circles','G','28');

INSERT OR IGNORE INTO mastery_levels
      (id,code,name,strand_code,skill_code,sequence_index,tier,time_standard_seconds,accuracy_threshold,video_url) VALUES
('level-f1a','F1a','Signed numbers: addition & subtraction','F','F1','1','CORE',NULL,'90',''),
('level-f1b','F1b','Signed numbers: multiplication & division','F','F1','2','CORE',NULL,'90',''),
('level-f1c','F1c','Fractions: add/subtract, unlike denominators','F','F1','3','CORE',NULL,'90',''),
('level-f1d','F1d','Fractions: multiply/divide, complex fractions','F','F1','4','CORE',NULL,'90',''),
('level-f1e','F1e','Fraction to decimal to percent','F','F1','5','CORE',NULL,'90',''),
('level-f1f','F1f','Order of operations with negatives and fractions','F','F1','6','CORE',NULL,'90',''),
('level-f1r','F1R','Interleaved review: number fluency','F','F1','7','CORE',NULL,'90',''),
('level-f2a','F2a','Combining like terms','F','F2','8','CORE',NULL,'90',''),
('level-f2b','F2b','Distributing, including negative distribution','F','F2','9','CORE',NULL,'90',''),
('level-f2c','F2c','Exponent rules: product, quotient, power','F','F2','10','CORE',NULL,'90',''),
('level-f2d','F2d','Zero and negative exponents','F','F2','11','CORE',NULL,'90',''),
('level-f2e','F2e','Evaluating by substitution','F','F2','12','CORE',NULL,'90',''),
('level-f2f','F2f','Words to expressions: the basic vocabulary','F','F2','13','CORE',NULL,'90',''),
('level-f2r','F2R','Interleaved review: expressions','F','F2','14','CORE',NULL,'90',''),
('level-f3a','F3a','One-step equations','F','F3','15','CORE',NULL,'90',''),
('level-f3b','F3b','Two-step equations','F','F3','16','CORE',NULL,'90',''),
('level-f3c','F3c','Variables on both sides','F','F3','17','CORE',NULL,'90',''),
('level-f3d','F3d','Clearing fractions from equations','F','F3','18','CORE',NULL,'90',''),
('level-f3e','F3e','Equations with parentheses','F','F3','19','CORE',NULL,'90',''),
('level-f3f','F3f','Literal equations: solve for the letter','F','F3','20','CORE',NULL,'90',''),
('level-f3r','F3R','Interleaved review: equation moves','F','F3','21','CORE',NULL,'90',''),
('level-f4a','F4a','Plotting points, quadrants','F','F4','22','CORE',NULL,'90',''),
('level-f4b','F4b','Reading values off a graph','F','F4','23','CORE',NULL,'90',''),
('level-f4c','F4c','Bar graphs, line graphs, frequency tables','F','F4','24','CORE',NULL,'90',''),
('level-f4d','F4d','Matching tables to graphs','F','F4','25','CORE',NULL,'90','');

INSERT OR IGNORE INTO mastery_levels
      (id,code,name,strand_code,skill_code,sequence_index,tier,time_standard_seconds,accuracy_threshold,video_url) VALUES
('level-f4e','F4e','Axis scale and units','F','F4','26','CORE',NULL,'90',''),
('level-f4r','F4R','Interleaved review: graph reading','F','F4','27','CORE',NULL,'90',''),
('level-a1a','A1a','Integer coefficients','A','A1','28','CORE',NULL,'90',''),
('level-a1b','A1b','Distribute then solve','A','A1','29','CORE',NULL,'90',''),
('level-a1c','A1c','Variables on both sides','A','A1','30','CORE',NULL,'90',''),
('level-a1d','A1d','Fractional & decimal coefficients','A','A1','31','CORE',NULL,'90',''),
('level-a1e','A1e','Word problem to one equation: single quantity','A','A1','32','CORE',NULL,'90',''),
('level-a1f','A1f','Word problem to one equation: two related quantities','A','A1','33','CORE',NULL,'90',''),
('level-a1g','A1g','No solution vs infinitely many','A','A1','34','CORE',NULL,'90',''),
('level-a1h','A1h','Find the constant that forces no/infinite solutions','A','A1','35','CORE',NULL,'90',''),
('level-a1i','A1i','Solve a formula for a variable of interest','A','A1','36','CORE',NULL,'90',''),
('level-a1r','A1R','Interleaved review: one-variable linear','A','A1','37','CORE',NULL,'90',''),
('level-a2a','A2a','Slope from two points','A','A2','38','CORE',NULL,'90',''),
('level-a2b','A2b','Slope-intercept form: read m and b','A','A2','39','CORE',NULL,'90',''),
('level-a2c','A2c','Standard form ax+by=c: rearranging and intercepts','A','A2','40','CORE',NULL,'90',''),
('level-a2d','A2d','Point-slope form','A','A2','41','CORE',NULL,'90',''),
('level-a2e','A2e','Equation from two points','A','A2','42','CORE',NULL,'90',''),
('level-a2f','A2f','Equation from a table of values','A','A2','43','CORE',NULL,'90',''),
('level-a2g','A2g','x- and y-intercepts','A','A2','44','CORE',NULL,'90',''),
('level-a2h','A2h','Parallel and perpendicular lines','A','A2','45','CORE',NULL,'90',''),
('level-a2i','A2i','Interpret slope in context, with units','A','A2','46','CORE',NULL,'90',''),
('level-a2j','A2j','Interpret intercepts in context','A','A2','47','CORE',NULL,'90',''),
('level-a2r','A2R','Interleaved review: two-variable linear','A','A2','48','CORE',NULL,'90',''),
('level-x1','X1','Desmos: graphing one equation, reading the intersection','X','X','49','CORE',NULL,'90',''),
('level-a3a','A3a','Function notation: evaluate f(x)','A','A3','50','CORE',NULL,'90','');

INSERT OR IGNORE INTO mastery_levels
      (id,code,name,strand_code,skill_code,sequence_index,tier,time_standard_seconds,accuracy_threshold,video_url) VALUES
('level-a3b','A3b','Solve f(x) = k','A','A3','51','CORE',NULL,'90',''),
('level-a3c','A3c','Build a linear model from a scenario','A','A3','52','CORE',NULL,'90',''),
('level-a3d','A3d','Interpret rate of change in context','A','A3','53','CORE',NULL,'90',''),
('level-a3e','A3e','Read function values from graphs and tables','A','A3','54','CORE',NULL,'90',''),
('level-a3f','A3f','Shifts and transformations of linear functions','A','A3','55','EXT',NULL,'90',''),
('level-a3r','A3R','Interleaved review: linear functions','A','A3','56','CORE',NULL,'90',''),
('level-x4','X4','Desmos: tables for function values','X','X','57','CORE',NULL,'90',''),
('level-a4a','A4a','Substitution','A','A4','58','CORE',NULL,'90',''),
('level-a4b','A4b','Elimination','A','A4','59','CORE',NULL,'90',''),
('level-a4c','A4c','Graphical solution / intersection','A','A4','60','CORE',NULL,'90',''),
('level-a4d','A4d','No solution vs infinite solutions','A','A4','61','CORE',NULL,'90',''),
('level-a4e','A4e','Find the coefficient forcing no/infinite solutions','A','A4','62','CORE',NULL,'90',''),
('level-a4f','A4f','System word problems: cost & quantity','A','A4','63','CORE',NULL,'90',''),
('level-a4g','A4g','System word problems: mixture & rate','A','A4','64','CORE',NULL,'90',''),
('level-a4r','A4R','Interleaved review: systems','A','A4','65','CORE',NULL,'90',''),
('level-x2','X2','Desmos: solving systems by graphing','X','X','66','CORE',NULL,'90',''),
('level-a5a','A5a','One variable, including flipping the sign','A','A5','67','CORE',NULL,'90',''),
('level-a5b','A5b','Compound inequalities','A','A5','68','EXT',NULL,'90',''),
('level-a5c','A5c','Graphing an inequality in two variables','A','A5','69','CORE',NULL,'90',''),
('level-a5d','A5d','Systems of inequalities: the shaded region','A','A5','70','CORE',NULL,'90',''),
('level-a5e','A5e','Is this point a solution?','A','A5','71','CORE',NULL,'90',''),
('level-a5f','A5f','Constraint word problems: at most, at least','A','A5','72','CORE',NULL,'90',''),
('level-a5r','A5R','Interleaved review: inequalities','A','A5','73','CORE',NULL,'90',''),
('level-x5','X5','Desmos: graphing inequalities and shaded regions','X','X','74','CORE',NULL,'90',''),
('level-s1a','S1a','Find the ask: what value does it actually want?','S','S1','75','CORE',NULL,'90','');

INSERT OR IGNORE INTO mastery_levels
      (id,code,name,strand_code,skill_code,sequence_index,tier,time_standard_seconds,accuracy_threshold,video_url) VALUES
('level-s1b','S1b','Label every number with its unit','S','S1','76','CORE',NULL,'90',''),
('level-s1c','S1c','Translating one sentence into an equation','S','S1','77','CORE',NULL,'90',''),
('level-s1d','S1d','Multi-sentence setups: building the model in pieces','S','S1','78','CORE',NULL,'90',''),
('level-s1r','S1R','Interleaved review: decoding','S','S1','79','CORE',NULL,'90',''),
('level-s2a','S2a','Backsolving: plugging in the answers','S','S2','80','CORE',NULL,'90',''),
('level-s2b','S2b','When backsolving beats algebra, and when it doesn''t','S','S2','81','CORE',NULL,'90',''),
('level-s2c','S2c','Plugging in numbers for variables','S','S2','82','CORE',NULL,'90',''),
('level-s2d','S2d','Plugging in on ''which expression is equivalent''','S','S2','83','CORE',NULL,'90',''),
('level-s2e','S2e','Elimination and ballparking','S','S2','84','CORE',NULL,'90',''),
('level-s2r','S2R','Interleaved review: answer-choice techniques','S','S2','85','CORE',NULL,'90',''),
('level-s3a','S3a','The 95-second budget','S','S3','86','CORE',NULL,'90',''),
('level-s3b','S3b','Skip-and-return: recognizing a time sink','S','S3','87','CORE',NULL,'90',''),
('level-s3c','S3c','Module 1 is the routing test','S','S3','88','CORE',NULL,'90',''),
('level-s3r','S3R','Interleaved review: pacing','S','S3','89','CORE',NULL,'90',''),
('level-x8','X8','Desmos: when NOT to use it','X','X','90','CORE',NULL,'90',''),
('level-p1','P1','SPR entry rules: 5 characters positive, 6 with a negative, no symbols','P','P1','91','CORE',NULL,'90',''),
('level-p2','P2','Fractions vs decimals: when each is safe','P','P1','92','CORE',NULL,'90',''),
('level-p3','P3','Repeating decimals: fill the field (.3333 not .33)','P','P1','93','CORE',NULL,'90',''),
('level-p4','P4','Mixed numbers to improper fraction or decimal','P','P1','94','CORE',NULL,'90',''),
('level-p5','P5','No answer choices: what changes when backsolving is unavailable','P','P1','95','CORE',NULL,'90',''),
('level-p6','P6','Grid-in mixed set under time','P','P1','96','CORE',NULL,'90',''),
('level-m1a','M1a','Exponent rules including fractional exponents','M','M1','97','CORE',NULL,'90',''),
('level-m1b','M1b','Radicals and rational exponents','M','M1','98','CORE',NULL,'90',''),
('level-m1c','M1c','Polynomial multiplication','M','M1','99','CORE',NULL,'90',''),
('level-m1d','M1d','Factoring out the GCF','M','M1','100','CORE',NULL,'90','');

INSERT OR IGNORE INTO mastery_levels
      (id,code,name,strand_code,skill_code,sequence_index,tier,time_standard_seconds,accuracy_threshold,video_url) VALUES
('level-m1e','M1e','Factoring trinomials, a = 1','M','M1','101','CORE',NULL,'90',''),
('level-m1f','M1f','Factoring trinomials, a != 1','M','M1','102','CORE',NULL,'90',''),
('level-m1g','M1g','Difference of squares','M','M1','103','CORE',NULL,'90',''),
('level-m1h','M1h','Perfect square trinomials','M','M1','104','EXT',NULL,'90',''),
('level-m1i','M1i','Rational expressions: simplify, multiply, divide','M','M1','105','CORE',NULL,'90',''),
('level-m1j','M1j','Rational expressions: add & subtract','M','M1','106','EXT',NULL,'90',''),
('level-m1k','M1k','Polynomial division and remainders','M','M1','107','EXT',NULL,'90',''),
('level-m1r','M1R','Interleaved review: equivalent expressions','M','M1','108','CORE',NULL,'90',''),
('level-m2a','M2a','Quadratics by factoring','M','M2','109','CORE',NULL,'90',''),
('level-m2b','M2b','Zero product property and roots','M','M2','110','CORE',NULL,'90',''),
('level-m2c','M2c','Quadratic formula','M','M2','111','CORE',NULL,'90',''),
('level-m2d','M2d','Discriminant: how many solutions','M','M2','112','CORE',NULL,'90',''),
('level-m2e','M2e','Completing the square','M','M2','113','EXT',NULL,'90',''),
('level-m2f','M2f','Radical equations & extraneous solutions','M','M2','114','CORE',NULL,'90',''),
('level-m2g','M2g','Rational equations','M','M2','115','EXT',NULL,'90',''),
('level-m2h','M2h','Absolute value equations','M','M2','116','CORE',NULL,'90',''),
('level-m2i','M2i','Exponential equations with a common base','M','M2','117','CORE',NULL,'90',''),
('level-m2j','M2j','Linear-quadratic systems','M','M2','118','CORE',NULL,'90',''),
('level-m2r','M2R','Interleaved review: nonlinear equations','M','M2','119','CORE',NULL,'90',''),
('level-m3a','M3a','Parabolas: vertex form','M','M3','120','CORE',NULL,'90',''),
('level-m3b','M3b','Parabolas: standard form, axis of symmetry','M','M3','121','CORE',NULL,'90',''),
('level-m3c','M3c','Parabolas: factored form and x-intercepts','M','M3','122','CORE',NULL,'90',''),
('level-m3d','M3d','Choosing the right form for what''s asked','M','M3','123','CORE',NULL,'90',''),
('level-m3e','M3e','Exponential growth vs decay','M','M3','124','CORE',NULL,'90',''),
('level-m3f','M3f','Interpreting exponential parameters in context','M','M3','125','CORE',NULL,'90','');

INSERT OR IGNORE INTO mastery_levels
      (id,code,name,strand_code,skill_code,sequence_index,tier,time_standard_seconds,accuracy_threshold,video_url) VALUES
('level-m3g','M3g','Compound growth with periods: quarterly, monthly','M','M3','126','CORE',NULL,'90',''),
('level-m3h','M3h','Transformations: f(x)+k, f(x+k), af(x), -f(x)','M','M3','127','CORE',NULL,'90',''),
('level-m3i','M3i','Graph reading for nonlinear functions','M','M3','128','CORE',NULL,'90',''),
('level-m3j','M3j','Where a function is undefined','M','M3','129','EXT',NULL,'90',''),
('level-m3k','M3k','Polynomial zeros and end behavior','M','M3','130','EXT',NULL,'90',''),
('level-m3l','M3l','Composite functions f(g(x))','M','M3','131','EXT',NULL,'90',''),
('level-m3r','M3R','Interleaved review: nonlinear functions','M','M3','132','CORE',NULL,'90',''),
('level-x3','X3','Desmos: roots and vertex of a parabola','X','X','133','CORE',NULL,'90',''),
('level-x6','X6','Desmos: sliders, what each coefficient does','X','X','134','EXT',NULL,'90',''),
('level-d1a','D1a','Proportions','D','D1','135','CORE',NULL,'90',''),
('level-d1b','D1b','Unit rate','D','D1','136','CORE',NULL,'90',''),
('level-d1c','D1c','Unit conversion, single and multi-step','D','D1','137','CORE',NULL,'90',''),
('level-d1d','D1d','Density and other derived units','D','D1','138','CORE',NULL,'90',''),
('level-d1e','D1e','Average rate of change from a graph','D','D1','139','CORE',NULL,'90',''),
('level-d1f','D1f','Scale drawings, maps, similar-figure ratios','D','D1','140','EXT',NULL,'90',''),
('level-d1r','D1R','Interleaved review: ratios and rates','D','D1','141','CORE',NULL,'90',''),
('level-d2a','D2a','Percent of a number','D','D2','142','CORE',NULL,'90',''),
('level-d2b','D2b','Percent increase and decrease','D','D2','143','CORE',NULL,'90',''),
('level-d2c','D2c','Reverse percent: find the original','D','D2','144','CORE',NULL,'90',''),
('level-d2d','D2d','Successive percent changes','D','D2','145','EXT',NULL,'90',''),
('level-d2e','D2e','Percent in context: discount, tax, tip, commission','D','D2','146','CORE',NULL,'90',''),
('level-d2f','D2f','Percent from a table or graph','D','D2','147','CORE',NULL,'90',''),
('level-d2r','D2R','Interleaved review: percentages','D','D2','148','CORE',NULL,'90',''),
('level-d3a','D3a','Mean, median, mode','D','D3','149','CORE',NULL,'90',''),
('level-d3b','D3b','Mean and median from a frequency table or dot plot','D','D3','150','CORE',NULL,'90','');

INSERT OR IGNORE INTO mastery_levels
      (id,code,name,strand_code,skill_code,sequence_index,tier,time_standard_seconds,accuracy_threshold,video_url) VALUES
('level-d3c','D3c','Range and standard deviation: compare, never compute','D','D3','151','CORE',NULL,'90',''),
('level-d3d','D3d','Effect of adding or changing a value','D','D3','152','CORE',NULL,'90',''),
('level-d3e','D3e','Histograms, dot plots, and box plots','D','D3','153','CORE',NULL,'90',''),
('level-d3f','D3f','Comparing two distributions','D','D3','154','CORE',NULL,'90',''),
('level-d3g','D3g','Outliers and skew: which measure to trust','D','D3','155','EXT',NULL,'90',''),
('level-d3r','D3R','Interleaved review: one-variable data','D','D3','156','CORE',NULL,'90',''),
('level-d4a','D4a','Reading a scatterplot','D','D4','157','CORE',NULL,'90',''),
('level-d4b','D4b','Line of best fit: predicting','D','D4','158','CORE',NULL,'90',''),
('level-d4c','D4c','Interpreting slope & intercept of the fit line','D','D4','159','CORE',NULL,'90',''),
('level-d4d','D4d','Choosing the model: linear vs exponential','D','D4','160','CORE',NULL,'90',''),
('level-d4e','D4e','Residuals: actual vs predicted','D','D4','161','EXT',NULL,'90',''),
('level-d4r','D4R','Interleaved review: two-variable data','D','D4','162','CORE',NULL,'90',''),
('level-x7','X7','Desmos: regression on scatterplot data','X','X','163','EXT',NULL,'90',''),
('level-d5a','D5a','Probability from counts','D','D5','164','CORE',NULL,'90',''),
('level-d5b','D5b','Reading a two-way table','D','D5','165','CORE',NULL,'90',''),
('level-d5c','D5c','Probability from a two-way table','D','D5','166','CORE',NULL,'90',''),
('level-d5d','D5d','Conditional probability: ''given that''','D','D5','167','CORE',NULL,'90',''),
('level-d5e','D5e','Complements and ''not''','D','D5','168','EXT',NULL,'90',''),
('level-d5r','D5R','Interleaved review: probability','D','D5','169','CORE',NULL,'90',''),
('level-d6a','D6a','Plausible population values from a sample and given margin of error','D','D6','170','CORE',NULL,'90',''),
('level-d6b','D6b','Interpreting margin of error in a sentence','D','D6','171','CORE',NULL,'90',''),
('level-d6c','D6c','How sample size changes margin of error','D','D6','172','EXT',NULL,'90',''),
('level-d7a','D7a','Random sampling: who you can generalize to','D','D7','173','CORE',NULL,'90',''),
('level-d7b','D7b','Random assignment: when you can say ''caused''','D','D7','174','CORE',NULL,'90',''),
('level-d7c','D7c','Which conclusion is supported?','D','D7','175','CORE',NULL,'90','');

INSERT OR IGNORE INTO mastery_levels
      (id,code,name,strand_code,skill_code,sequence_index,tier,time_standard_seconds,accuracy_threshold,video_url) VALUES
('level-d7d','D7d','Spotting bias in study design','D','D7','176','EXT',NULL,'90',''),
('level-d-r','D-R','Interleaved review: inference and claims','D','D7','177','CORE',NULL,'90',''),
('level-g1a','G1a','Vertical angles & linear pairs','G','G1','178','CORE',NULL,'90',''),
('level-g1b','G1b','Parallel lines & transversals','G','G1','179','CORE',NULL,'90',''),
('level-g1c','G1c','Triangle angle sum & exterior angle','G','G1','180','CORE',NULL,'90',''),
('level-g1d','G1d','Isosceles & equilateral triangles','G','G1','181','CORE',NULL,'90',''),
('level-g1e','G1e','Similar triangles: setting up the ratio','G','G1','182','CORE',NULL,'90',''),
('level-g1f','G1f','Congruence','G','G1','183','CORE',NULL,'90',''),
('level-g1g','G1g','Polygon interior & exterior angles','G','G1','184','EXT',NULL,'90',''),
('level-g1r','G1R','Interleaved review: lines, angles, triangles','G','G1','185','CORE',NULL,'90',''),
('level-g3a','G3a','Area: triangle, rectangle, parallelogram, trapezoid','G','G3','186','CORE',NULL,'90',''),
('level-g3b','G3b','Circumference and area of a circle','G','G3','187','CORE',NULL,'90',''),
('level-g3c','G3c','Volume of prisms and cylinders','G','G3','188','CORE',NULL,'90',''),
('level-g3d','G3d','Cones, pyramids, spheres: using the reference sheet','G','G3','189','CORE',NULL,'90',''),
('level-g3e','G3e','Surface area','G','G3','190','EXT',NULL,'90',''),
('level-g3f','G3f','Composite and shaded regions','G','G3','191','EXT',NULL,'90',''),
('level-g3g','G3g','Scaling: effect on area and volume','G','G3','192','EXT',NULL,'90',''),
('level-g3r','G3R','Interleaved review: area and volume','G','G3','193','CORE',NULL,'90',''),
('level-g2a','G2a','Pythagorean theorem','G','G2','194','CORE',NULL,'90',''),
('level-g2b','G2b','Pythagorean triples','G','G2','195','EXT',NULL,'90',''),
('level-g2c','G2c','Special right triangles: 45-45-90 and 30-60-90','G','G2','196','CORE',NULL,'90',''),
('level-g2d','G2d','SOH-CAH-TOA: find a side','G','G2','197','CORE',NULL,'90',''),
('level-g2e','G2e','SOH-CAH-TOA: find an angle','G','G2','198','EXT',NULL,'90',''),
('level-g2f','G2f','sin x = cos(90 - x)','G','G2','199','EXT',NULL,'90',''),
('level-g2g','G2g','Trig in diagrams and word problems','G','G2','200','EXT',NULL,'90','');

INSERT OR IGNORE INTO mastery_levels
      (id,code,name,strand_code,skill_code,sequence_index,tier,time_standard_seconds,accuracy_threshold,video_url) VALUES
('level-g2r','G2R','Interleaved review: right triangle trig','G','G2','201','CORE',NULL,'90',''),
('level-g4f','G4f','Equation of a circle','G','G4','202','CORE',NULL,'90',''),
('level-g4a','G4a','Central angles and arc measure','G','G4','203','EXT',NULL,'90',''),
('level-g4b','G4b','Arc length','G','G4','204','EXT',NULL,'90',''),
('level-g4c','G4c','Sector area','G','G4','205','EXT',NULL,'90',''),
('level-g4d','G4d','Inscribed angles','G','G4','206','EXT',NULL,'90',''),
('level-g4e','G4e','Radians and degrees','G','G4','207','EXT',NULL,'90',''),
('level-g4g','G4g','Completing the square to find center & radius','G','G4','208','EXT',NULL,'90',''),
('level-g4h','G4h','Tangent lines and the perpendicular radius','G','G4','209','EXT',NULL,'90',''),
('level-g4r','G4R','Interleaved review: circles','G','G4','210','EXT',NULL,'90','');

INSERT OR IGNORE INTO mastery_worksheets (id,level_id,worksheet_index,worksheet_type) VALUES
('ws-f1a-01','level-f1a','1','PRACTICE'),
('ws-f1a-02','level-f1a','2','PRACTICE'),
('ws-f1a-03','level-f1a','3','PRACTICE'),
('ws-f1a-04','level-f1a','4','MIXED'),
('ws-f1a-05','level-f1a','5','MASTERY_CHECK'),
('ws-f1b-01','level-f1b','1','PRACTICE'),
('ws-f1b-02','level-f1b','2','PRACTICE'),
('ws-f1b-03','level-f1b','3','PRACTICE'),
('ws-f1b-04','level-f1b','4','MIXED'),
('ws-f1b-05','level-f1b','5','MASTERY_CHECK'),
('ws-f1c-01','level-f1c','1','PRACTICE'),
('ws-f1c-02','level-f1c','2','PRACTICE'),
('ws-f1c-03','level-f1c','3','PRACTICE'),
('ws-f1c-04','level-f1c','4','MIXED'),
('ws-f1c-05','level-f1c','5','MASTERY_CHECK'),
('ws-f1d-01','level-f1d','1','PRACTICE'),
('ws-f1d-02','level-f1d','2','PRACTICE'),
('ws-f1d-03','level-f1d','3','PRACTICE'),
('ws-f1d-04','level-f1d','4','MIXED'),
('ws-f1d-05','level-f1d','5','MASTERY_CHECK'),
('ws-f1e-01','level-f1e','1','PRACTICE'),
('ws-f1e-02','level-f1e','2','PRACTICE'),
('ws-f1e-03','level-f1e','3','PRACTICE'),
('ws-f1e-04','level-f1e','4','MIXED'),
('ws-f1e-05','level-f1e','5','MASTERY_CHECK'),
('ws-f1f-01','level-f1f','1','PRACTICE'),
('ws-f1f-02','level-f1f','2','PRACTICE'),
('ws-f1f-03','level-f1f','3','PRACTICE'),
('ws-f1f-04','level-f1f','4','MIXED'),
('ws-f1f-05','level-f1f','5','MASTERY_CHECK'),
('ws-f1r-01','level-f1r','1','PRACTICE'),
('ws-f1r-02','level-f1r','2','PRACTICE'),
('ws-f1r-03','level-f1r','3','PRACTICE'),
('ws-f1r-04','level-f1r','4','MIXED'),
('ws-f1r-05','level-f1r','5','MASTERY_CHECK'),
('ws-f2a-01','level-f2a','1','PRACTICE'),
('ws-f2a-02','level-f2a','2','PRACTICE'),
('ws-f2a-03','level-f2a','3','PRACTICE'),
('ws-f2a-04','level-f2a','4','MIXED'),
('ws-f2a-05','level-f2a','5','MASTERY_CHECK'),
('ws-f2b-01','level-f2b','1','PRACTICE'),
('ws-f2b-02','level-f2b','2','PRACTICE'),
('ws-f2b-03','level-f2b','3','PRACTICE'),
('ws-f2b-04','level-f2b','4','MIXED'),
('ws-f2b-05','level-f2b','5','MASTERY_CHECK'),
('ws-f2c-01','level-f2c','1','PRACTICE'),
('ws-f2c-02','level-f2c','2','PRACTICE'),
('ws-f2c-03','level-f2c','3','PRACTICE'),
('ws-f2c-04','level-f2c','4','MIXED'),
('ws-f2c-05','level-f2c','5','MASTERY_CHECK'),
('ws-f2d-01','level-f2d','1','PRACTICE'),
('ws-f2d-02','level-f2d','2','PRACTICE'),
('ws-f2d-03','level-f2d','3','PRACTICE'),
('ws-f2d-04','level-f2d','4','MIXED'),
('ws-f2d-05','level-f2d','5','MASTERY_CHECK'),
('ws-f2e-01','level-f2e','1','PRACTICE'),
('ws-f2e-02','level-f2e','2','PRACTICE'),
('ws-f2e-03','level-f2e','3','PRACTICE'),
('ws-f2e-04','level-f2e','4','MIXED'),
('ws-f2e-05','level-f2e','5','MASTERY_CHECK'),
('ws-f2f-01','level-f2f','1','PRACTICE'),
('ws-f2f-02','level-f2f','2','PRACTICE'),
('ws-f2f-03','level-f2f','3','PRACTICE'),
('ws-f2f-04','level-f2f','4','MIXED'),
('ws-f2f-05','level-f2f','5','MASTERY_CHECK'),
('ws-f2r-01','level-f2r','1','PRACTICE'),
('ws-f2r-02','level-f2r','2','PRACTICE'),
('ws-f2r-03','level-f2r','3','PRACTICE'),
('ws-f2r-04','level-f2r','4','MIXED'),
('ws-f2r-05','level-f2r','5','MASTERY_CHECK'),
('ws-f3a-01','level-f3a','1','PRACTICE'),
('ws-f3a-02','level-f3a','2','PRACTICE'),
('ws-f3a-03','level-f3a','3','PRACTICE'),
('ws-f3a-04','level-f3a','4','MIXED'),
('ws-f3a-05','level-f3a','5','MASTERY_CHECK'),
('ws-f3b-01','level-f3b','1','PRACTICE'),
('ws-f3b-02','level-f3b','2','PRACTICE'),
('ws-f3b-03','level-f3b','3','PRACTICE'),
('ws-f3b-04','level-f3b','4','MIXED'),
('ws-f3b-05','level-f3b','5','MASTERY_CHECK'),
('ws-f3c-01','level-f3c','1','PRACTICE'),
('ws-f3c-02','level-f3c','2','PRACTICE'),
('ws-f3c-03','level-f3c','3','PRACTICE'),
('ws-f3c-04','level-f3c','4','MIXED'),
('ws-f3c-05','level-f3c','5','MASTERY_CHECK'),
('ws-f3d-01','level-f3d','1','PRACTICE'),
('ws-f3d-02','level-f3d','2','PRACTICE'),
('ws-f3d-03','level-f3d','3','PRACTICE'),
('ws-f3d-04','level-f3d','4','MIXED'),
('ws-f3d-05','level-f3d','5','MASTERY_CHECK'),
('ws-f3e-01','level-f3e','1','PRACTICE'),
('ws-f3e-02','level-f3e','2','PRACTICE'),
('ws-f3e-03','level-f3e','3','PRACTICE'),
('ws-f3e-04','level-f3e','4','MIXED'),
('ws-f3e-05','level-f3e','5','MASTERY_CHECK'),
('ws-f3f-01','level-f3f','1','PRACTICE'),
('ws-f3f-02','level-f3f','2','PRACTICE'),
('ws-f3f-03','level-f3f','3','PRACTICE'),
('ws-f3f-04','level-f3f','4','MIXED'),
('ws-f3f-05','level-f3f','5','MASTERY_CHECK'),
('ws-f3r-01','level-f3r','1','PRACTICE'),
('ws-f3r-02','level-f3r','2','PRACTICE'),
('ws-f3r-03','level-f3r','3','PRACTICE'),
('ws-f3r-04','level-f3r','4','MIXED'),
('ws-f3r-05','level-f3r','5','MASTERY_CHECK'),
('ws-f4a-01','level-f4a','1','PRACTICE'),
('ws-f4a-02','level-f4a','2','PRACTICE'),
('ws-f4a-03','level-f4a','3','PRACTICE'),
('ws-f4a-04','level-f4a','4','MIXED'),
('ws-f4a-05','level-f4a','5','MASTERY_CHECK'),
('ws-f4b-01','level-f4b','1','PRACTICE'),
('ws-f4b-02','level-f4b','2','PRACTICE'),
('ws-f4b-03','level-f4b','3','PRACTICE'),
('ws-f4b-04','level-f4b','4','MIXED'),
('ws-f4b-05','level-f4b','5','MASTERY_CHECK'),
('ws-f4c-01','level-f4c','1','PRACTICE'),
('ws-f4c-02','level-f4c','2','PRACTICE'),
('ws-f4c-03','level-f4c','3','PRACTICE'),
('ws-f4c-04','level-f4c','4','MIXED'),
('ws-f4c-05','level-f4c','5','MASTERY_CHECK'),
('ws-f4d-01','level-f4d','1','PRACTICE'),
('ws-f4d-02','level-f4d','2','PRACTICE'),
('ws-f4d-03','level-f4d','3','PRACTICE'),
('ws-f4d-04','level-f4d','4','MIXED'),
('ws-f4d-05','level-f4d','5','MASTERY_CHECK');

INSERT OR IGNORE INTO mastery_worksheets (id,level_id,worksheet_index,worksheet_type) VALUES
('ws-f4e-01','level-f4e','1','PRACTICE'),
('ws-f4e-02','level-f4e','2','PRACTICE'),
('ws-f4e-03','level-f4e','3','PRACTICE'),
('ws-f4e-04','level-f4e','4','MIXED'),
('ws-f4e-05','level-f4e','5','MASTERY_CHECK'),
('ws-f4r-01','level-f4r','1','PRACTICE'),
('ws-f4r-02','level-f4r','2','PRACTICE'),
('ws-f4r-03','level-f4r','3','PRACTICE'),
('ws-f4r-04','level-f4r','4','MIXED'),
('ws-f4r-05','level-f4r','5','MASTERY_CHECK'),
('ws-a1a-01','level-a1a','1','PRACTICE'),
('ws-a1a-02','level-a1a','2','PRACTICE'),
('ws-a1a-03','level-a1a','3','PRACTICE'),
('ws-a1a-04','level-a1a','4','MIXED'),
('ws-a1a-05','level-a1a','5','MASTERY_CHECK'),
('ws-a1b-01','level-a1b','1','PRACTICE'),
('ws-a1b-02','level-a1b','2','PRACTICE'),
('ws-a1b-03','level-a1b','3','PRACTICE'),
('ws-a1b-04','level-a1b','4','MIXED'),
('ws-a1b-05','level-a1b','5','MASTERY_CHECK'),
('ws-a1c-01','level-a1c','1','PRACTICE'),
('ws-a1c-02','level-a1c','2','PRACTICE'),
('ws-a1c-03','level-a1c','3','PRACTICE'),
('ws-a1c-04','level-a1c','4','MIXED'),
('ws-a1c-05','level-a1c','5','MASTERY_CHECK'),
('ws-a1d-01','level-a1d','1','PRACTICE'),
('ws-a1d-02','level-a1d','2','PRACTICE'),
('ws-a1d-03','level-a1d','3','PRACTICE'),
('ws-a1d-04','level-a1d','4','MIXED'),
('ws-a1d-05','level-a1d','5','MASTERY_CHECK'),
('ws-a1e-01','level-a1e','1','PRACTICE'),
('ws-a1e-02','level-a1e','2','PRACTICE'),
('ws-a1e-03','level-a1e','3','PRACTICE'),
('ws-a1e-04','level-a1e','4','MIXED'),
('ws-a1e-05','level-a1e','5','MASTERY_CHECK'),
('ws-a1f-01','level-a1f','1','PRACTICE'),
('ws-a1f-02','level-a1f','2','PRACTICE'),
('ws-a1f-03','level-a1f','3','PRACTICE'),
('ws-a1f-04','level-a1f','4','MIXED'),
('ws-a1f-05','level-a1f','5','MASTERY_CHECK'),
('ws-a1g-01','level-a1g','1','PRACTICE'),
('ws-a1g-02','level-a1g','2','PRACTICE'),
('ws-a1g-03','level-a1g','3','PRACTICE'),
('ws-a1g-04','level-a1g','4','MIXED'),
('ws-a1g-05','level-a1g','5','MASTERY_CHECK'),
('ws-a1h-01','level-a1h','1','PRACTICE'),
('ws-a1h-02','level-a1h','2','PRACTICE'),
('ws-a1h-03','level-a1h','3','PRACTICE'),
('ws-a1h-04','level-a1h','4','MIXED'),
('ws-a1h-05','level-a1h','5','MASTERY_CHECK'),
('ws-a1i-01','level-a1i','1','PRACTICE'),
('ws-a1i-02','level-a1i','2','PRACTICE'),
('ws-a1i-03','level-a1i','3','PRACTICE'),
('ws-a1i-04','level-a1i','4','MIXED'),
('ws-a1i-05','level-a1i','5','MASTERY_CHECK'),
('ws-a1r-01','level-a1r','1','PRACTICE'),
('ws-a1r-02','level-a1r','2','PRACTICE'),
('ws-a1r-03','level-a1r','3','PRACTICE'),
('ws-a1r-04','level-a1r','4','MIXED'),
('ws-a1r-05','level-a1r','5','MASTERY_CHECK'),
('ws-a2a-01','level-a2a','1','PRACTICE'),
('ws-a2a-02','level-a2a','2','PRACTICE'),
('ws-a2a-03','level-a2a','3','PRACTICE'),
('ws-a2a-04','level-a2a','4','MIXED'),
('ws-a2a-05','level-a2a','5','MASTERY_CHECK'),
('ws-a2b-01','level-a2b','1','PRACTICE'),
('ws-a2b-02','level-a2b','2','PRACTICE'),
('ws-a2b-03','level-a2b','3','PRACTICE'),
('ws-a2b-04','level-a2b','4','MIXED'),
('ws-a2b-05','level-a2b','5','MASTERY_CHECK'),
('ws-a2c-01','level-a2c','1','PRACTICE'),
('ws-a2c-02','level-a2c','2','PRACTICE'),
('ws-a2c-03','level-a2c','3','PRACTICE'),
('ws-a2c-04','level-a2c','4','MIXED'),
('ws-a2c-05','level-a2c','5','MASTERY_CHECK'),
('ws-a2d-01','level-a2d','1','PRACTICE'),
('ws-a2d-02','level-a2d','2','PRACTICE'),
('ws-a2d-03','level-a2d','3','PRACTICE'),
('ws-a2d-04','level-a2d','4','MIXED'),
('ws-a2d-05','level-a2d','5','MASTERY_CHECK'),
('ws-a2e-01','level-a2e','1','PRACTICE'),
('ws-a2e-02','level-a2e','2','PRACTICE'),
('ws-a2e-03','level-a2e','3','PRACTICE'),
('ws-a2e-04','level-a2e','4','MIXED'),
('ws-a2e-05','level-a2e','5','MASTERY_CHECK'),
('ws-a2f-01','level-a2f','1','PRACTICE'),
('ws-a2f-02','level-a2f','2','PRACTICE'),
('ws-a2f-03','level-a2f','3','PRACTICE'),
('ws-a2f-04','level-a2f','4','MIXED'),
('ws-a2f-05','level-a2f','5','MASTERY_CHECK'),
('ws-a2g-01','level-a2g','1','PRACTICE'),
('ws-a2g-02','level-a2g','2','PRACTICE'),
('ws-a2g-03','level-a2g','3','PRACTICE'),
('ws-a2g-04','level-a2g','4','MIXED'),
('ws-a2g-05','level-a2g','5','MASTERY_CHECK'),
('ws-a2h-01','level-a2h','1','PRACTICE'),
('ws-a2h-02','level-a2h','2','PRACTICE'),
('ws-a2h-03','level-a2h','3','PRACTICE'),
('ws-a2h-04','level-a2h','4','MIXED'),
('ws-a2h-05','level-a2h','5','MASTERY_CHECK'),
('ws-a2i-01','level-a2i','1','PRACTICE'),
('ws-a2i-02','level-a2i','2','PRACTICE'),
('ws-a2i-03','level-a2i','3','PRACTICE'),
('ws-a2i-04','level-a2i','4','MIXED'),
('ws-a2i-05','level-a2i','5','MASTERY_CHECK'),
('ws-a2j-01','level-a2j','1','PRACTICE'),
('ws-a2j-02','level-a2j','2','PRACTICE'),
('ws-a2j-03','level-a2j','3','PRACTICE'),
('ws-a2j-04','level-a2j','4','MIXED'),
('ws-a2j-05','level-a2j','5','MASTERY_CHECK'),
('ws-a2r-01','level-a2r','1','PRACTICE'),
('ws-a2r-02','level-a2r','2','PRACTICE'),
('ws-a2r-03','level-a2r','3','PRACTICE'),
('ws-a2r-04','level-a2r','4','MIXED'),
('ws-a2r-05','level-a2r','5','MASTERY_CHECK'),
('ws-x1-01','level-x1','1','PRACTICE'),
('ws-x1-02','level-x1','2','PRACTICE'),
('ws-x1-03','level-x1','3','PRACTICE'),
('ws-x1-04','level-x1','4','MIXED'),
('ws-x1-05','level-x1','5','MASTERY_CHECK'),
('ws-a3a-01','level-a3a','1','PRACTICE'),
('ws-a3a-02','level-a3a','2','PRACTICE'),
('ws-a3a-03','level-a3a','3','PRACTICE'),
('ws-a3a-04','level-a3a','4','MIXED'),
('ws-a3a-05','level-a3a','5','MASTERY_CHECK');

INSERT OR IGNORE INTO mastery_worksheets (id,level_id,worksheet_index,worksheet_type) VALUES
('ws-a3b-01','level-a3b','1','PRACTICE'),
('ws-a3b-02','level-a3b','2','PRACTICE'),
('ws-a3b-03','level-a3b','3','PRACTICE'),
('ws-a3b-04','level-a3b','4','MIXED'),
('ws-a3b-05','level-a3b','5','MASTERY_CHECK'),
('ws-a3c-01','level-a3c','1','PRACTICE'),
('ws-a3c-02','level-a3c','2','PRACTICE'),
('ws-a3c-03','level-a3c','3','PRACTICE'),
('ws-a3c-04','level-a3c','4','MIXED'),
('ws-a3c-05','level-a3c','5','MASTERY_CHECK'),
('ws-a3d-01','level-a3d','1','PRACTICE'),
('ws-a3d-02','level-a3d','2','PRACTICE'),
('ws-a3d-03','level-a3d','3','PRACTICE'),
('ws-a3d-04','level-a3d','4','MIXED'),
('ws-a3d-05','level-a3d','5','MASTERY_CHECK'),
('ws-a3e-01','level-a3e','1','PRACTICE'),
('ws-a3e-02','level-a3e','2','PRACTICE'),
('ws-a3e-03','level-a3e','3','PRACTICE'),
('ws-a3e-04','level-a3e','4','MIXED'),
('ws-a3e-05','level-a3e','5','MASTERY_CHECK'),
('ws-a3f-01','level-a3f','1','PRACTICE'),
('ws-a3f-02','level-a3f','2','PRACTICE'),
('ws-a3f-03','level-a3f','3','PRACTICE'),
('ws-a3f-04','level-a3f','4','MIXED'),
('ws-a3f-05','level-a3f','5','MASTERY_CHECK'),
('ws-a3r-01','level-a3r','1','PRACTICE'),
('ws-a3r-02','level-a3r','2','PRACTICE'),
('ws-a3r-03','level-a3r','3','PRACTICE'),
('ws-a3r-04','level-a3r','4','MIXED'),
('ws-a3r-05','level-a3r','5','MASTERY_CHECK'),
('ws-x4-01','level-x4','1','PRACTICE'),
('ws-x4-02','level-x4','2','PRACTICE'),
('ws-x4-03','level-x4','3','PRACTICE'),
('ws-x4-04','level-x4','4','MIXED'),
('ws-x4-05','level-x4','5','MASTERY_CHECK'),
('ws-a4a-01','level-a4a','1','PRACTICE'),
('ws-a4a-02','level-a4a','2','PRACTICE'),
('ws-a4a-03','level-a4a','3','PRACTICE'),
('ws-a4a-04','level-a4a','4','MIXED'),
('ws-a4a-05','level-a4a','5','MASTERY_CHECK'),
('ws-a4b-01','level-a4b','1','PRACTICE'),
('ws-a4b-02','level-a4b','2','PRACTICE'),
('ws-a4b-03','level-a4b','3','PRACTICE'),
('ws-a4b-04','level-a4b','4','MIXED'),
('ws-a4b-05','level-a4b','5','MASTERY_CHECK'),
('ws-a4c-01','level-a4c','1','PRACTICE'),
('ws-a4c-02','level-a4c','2','PRACTICE'),
('ws-a4c-03','level-a4c','3','PRACTICE'),
('ws-a4c-04','level-a4c','4','MIXED'),
('ws-a4c-05','level-a4c','5','MASTERY_CHECK'),
('ws-a4d-01','level-a4d','1','PRACTICE'),
('ws-a4d-02','level-a4d','2','PRACTICE'),
('ws-a4d-03','level-a4d','3','PRACTICE'),
('ws-a4d-04','level-a4d','4','MIXED'),
('ws-a4d-05','level-a4d','5','MASTERY_CHECK'),
('ws-a4e-01','level-a4e','1','PRACTICE'),
('ws-a4e-02','level-a4e','2','PRACTICE'),
('ws-a4e-03','level-a4e','3','PRACTICE'),
('ws-a4e-04','level-a4e','4','MIXED'),
('ws-a4e-05','level-a4e','5','MASTERY_CHECK'),
('ws-a4f-01','level-a4f','1','PRACTICE'),
('ws-a4f-02','level-a4f','2','PRACTICE'),
('ws-a4f-03','level-a4f','3','PRACTICE'),
('ws-a4f-04','level-a4f','4','MIXED'),
('ws-a4f-05','level-a4f','5','MASTERY_CHECK'),
('ws-a4g-01','level-a4g','1','PRACTICE'),
('ws-a4g-02','level-a4g','2','PRACTICE'),
('ws-a4g-03','level-a4g','3','PRACTICE'),
('ws-a4g-04','level-a4g','4','MIXED'),
('ws-a4g-05','level-a4g','5','MASTERY_CHECK'),
('ws-a4r-01','level-a4r','1','PRACTICE'),
('ws-a4r-02','level-a4r','2','PRACTICE'),
('ws-a4r-03','level-a4r','3','PRACTICE'),
('ws-a4r-04','level-a4r','4','MIXED'),
('ws-a4r-05','level-a4r','5','MASTERY_CHECK'),
('ws-x2-01','level-x2','1','PRACTICE'),
('ws-x2-02','level-x2','2','PRACTICE'),
('ws-x2-03','level-x2','3','PRACTICE'),
('ws-x2-04','level-x2','4','MIXED'),
('ws-x2-05','level-x2','5','MASTERY_CHECK'),
('ws-a5a-01','level-a5a','1','PRACTICE'),
('ws-a5a-02','level-a5a','2','PRACTICE'),
('ws-a5a-03','level-a5a','3','PRACTICE'),
('ws-a5a-04','level-a5a','4','MIXED'),
('ws-a5a-05','level-a5a','5','MASTERY_CHECK'),
('ws-a5b-01','level-a5b','1','PRACTICE'),
('ws-a5b-02','level-a5b','2','PRACTICE'),
('ws-a5b-03','level-a5b','3','PRACTICE'),
('ws-a5b-04','level-a5b','4','MIXED'),
('ws-a5b-05','level-a5b','5','MASTERY_CHECK'),
('ws-a5c-01','level-a5c','1','PRACTICE'),
('ws-a5c-02','level-a5c','2','PRACTICE'),
('ws-a5c-03','level-a5c','3','PRACTICE'),
('ws-a5c-04','level-a5c','4','MIXED'),
('ws-a5c-05','level-a5c','5','MASTERY_CHECK'),
('ws-a5d-01','level-a5d','1','PRACTICE'),
('ws-a5d-02','level-a5d','2','PRACTICE'),
('ws-a5d-03','level-a5d','3','PRACTICE'),
('ws-a5d-04','level-a5d','4','MIXED'),
('ws-a5d-05','level-a5d','5','MASTERY_CHECK'),
('ws-a5e-01','level-a5e','1','PRACTICE'),
('ws-a5e-02','level-a5e','2','PRACTICE'),
('ws-a5e-03','level-a5e','3','PRACTICE'),
('ws-a5e-04','level-a5e','4','MIXED'),
('ws-a5e-05','level-a5e','5','MASTERY_CHECK'),
('ws-a5f-01','level-a5f','1','PRACTICE'),
('ws-a5f-02','level-a5f','2','PRACTICE'),
('ws-a5f-03','level-a5f','3','PRACTICE'),
('ws-a5f-04','level-a5f','4','MIXED'),
('ws-a5f-05','level-a5f','5','MASTERY_CHECK'),
('ws-a5r-01','level-a5r','1','PRACTICE'),
('ws-a5r-02','level-a5r','2','PRACTICE'),
('ws-a5r-03','level-a5r','3','PRACTICE'),
('ws-a5r-04','level-a5r','4','MIXED'),
('ws-a5r-05','level-a5r','5','MASTERY_CHECK'),
('ws-x5-01','level-x5','1','PRACTICE'),
('ws-x5-02','level-x5','2','PRACTICE'),
('ws-x5-03','level-x5','3','PRACTICE'),
('ws-x5-04','level-x5','4','MIXED'),
('ws-x5-05','level-x5','5','MASTERY_CHECK'),
('ws-s1a-01','level-s1a','1','PRACTICE'),
('ws-s1a-02','level-s1a','2','PRACTICE'),
('ws-s1a-03','level-s1a','3','PRACTICE'),
('ws-s1a-04','level-s1a','4','MIXED'),
('ws-s1a-05','level-s1a','5','MASTERY_CHECK');

INSERT OR IGNORE INTO mastery_worksheets (id,level_id,worksheet_index,worksheet_type) VALUES
('ws-s1b-01','level-s1b','1','PRACTICE'),
('ws-s1b-02','level-s1b','2','PRACTICE'),
('ws-s1b-03','level-s1b','3','PRACTICE'),
('ws-s1b-04','level-s1b','4','MIXED'),
('ws-s1b-05','level-s1b','5','MASTERY_CHECK'),
('ws-s1c-01','level-s1c','1','PRACTICE'),
('ws-s1c-02','level-s1c','2','PRACTICE'),
('ws-s1c-03','level-s1c','3','PRACTICE'),
('ws-s1c-04','level-s1c','4','MIXED'),
('ws-s1c-05','level-s1c','5','MASTERY_CHECK'),
('ws-s1d-01','level-s1d','1','PRACTICE'),
('ws-s1d-02','level-s1d','2','PRACTICE'),
('ws-s1d-03','level-s1d','3','PRACTICE'),
('ws-s1d-04','level-s1d','4','MIXED'),
('ws-s1d-05','level-s1d','5','MASTERY_CHECK'),
('ws-s1r-01','level-s1r','1','PRACTICE'),
('ws-s1r-02','level-s1r','2','PRACTICE'),
('ws-s1r-03','level-s1r','3','PRACTICE'),
('ws-s1r-04','level-s1r','4','MIXED'),
('ws-s1r-05','level-s1r','5','MASTERY_CHECK'),
('ws-s2a-01','level-s2a','1','PRACTICE'),
('ws-s2a-02','level-s2a','2','PRACTICE'),
('ws-s2a-03','level-s2a','3','PRACTICE'),
('ws-s2a-04','level-s2a','4','MIXED'),
('ws-s2a-05','level-s2a','5','MASTERY_CHECK'),
('ws-s2b-01','level-s2b','1','PRACTICE'),
('ws-s2b-02','level-s2b','2','PRACTICE'),
('ws-s2b-03','level-s2b','3','PRACTICE'),
('ws-s2b-04','level-s2b','4','MIXED'),
('ws-s2b-05','level-s2b','5','MASTERY_CHECK'),
('ws-s2c-01','level-s2c','1','PRACTICE'),
('ws-s2c-02','level-s2c','2','PRACTICE'),
('ws-s2c-03','level-s2c','3','PRACTICE'),
('ws-s2c-04','level-s2c','4','MIXED'),
('ws-s2c-05','level-s2c','5','MASTERY_CHECK'),
('ws-s2d-01','level-s2d','1','PRACTICE'),
('ws-s2d-02','level-s2d','2','PRACTICE'),
('ws-s2d-03','level-s2d','3','PRACTICE'),
('ws-s2d-04','level-s2d','4','MIXED'),
('ws-s2d-05','level-s2d','5','MASTERY_CHECK'),
('ws-s2e-01','level-s2e','1','PRACTICE'),
('ws-s2e-02','level-s2e','2','PRACTICE'),
('ws-s2e-03','level-s2e','3','PRACTICE'),
('ws-s2e-04','level-s2e','4','MIXED'),
('ws-s2e-05','level-s2e','5','MASTERY_CHECK'),
('ws-s2r-01','level-s2r','1','PRACTICE'),
('ws-s2r-02','level-s2r','2','PRACTICE'),
('ws-s2r-03','level-s2r','3','PRACTICE'),
('ws-s2r-04','level-s2r','4','MIXED'),
('ws-s2r-05','level-s2r','5','MASTERY_CHECK'),
('ws-s3a-01','level-s3a','1','PRACTICE'),
('ws-s3a-02','level-s3a','2','PRACTICE'),
('ws-s3a-03','level-s3a','3','PRACTICE'),
('ws-s3a-04','level-s3a','4','MIXED'),
('ws-s3a-05','level-s3a','5','MASTERY_CHECK'),
('ws-s3b-01','level-s3b','1','PRACTICE'),
('ws-s3b-02','level-s3b','2','PRACTICE'),
('ws-s3b-03','level-s3b','3','PRACTICE'),
('ws-s3b-04','level-s3b','4','MIXED'),
('ws-s3b-05','level-s3b','5','MASTERY_CHECK'),
('ws-s3c-01','level-s3c','1','PRACTICE'),
('ws-s3c-02','level-s3c','2','PRACTICE'),
('ws-s3c-03','level-s3c','3','PRACTICE'),
('ws-s3c-04','level-s3c','4','MIXED'),
('ws-s3c-05','level-s3c','5','MASTERY_CHECK'),
('ws-s3r-01','level-s3r','1','PRACTICE'),
('ws-s3r-02','level-s3r','2','PRACTICE'),
('ws-s3r-03','level-s3r','3','PRACTICE'),
('ws-s3r-04','level-s3r','4','MIXED'),
('ws-s3r-05','level-s3r','5','MASTERY_CHECK'),
('ws-x8-01','level-x8','1','PRACTICE'),
('ws-x8-02','level-x8','2','PRACTICE'),
('ws-x8-03','level-x8','3','PRACTICE'),
('ws-x8-04','level-x8','4','MIXED'),
('ws-x8-05','level-x8','5','MASTERY_CHECK'),
('ws-p1-01','level-p1','1','PRACTICE'),
('ws-p1-02','level-p1','2','PRACTICE'),
('ws-p1-03','level-p1','3','PRACTICE'),
('ws-p1-04','level-p1','4','MIXED'),
('ws-p1-05','level-p1','5','MASTERY_CHECK'),
('ws-p2-01','level-p2','1','PRACTICE'),
('ws-p2-02','level-p2','2','PRACTICE'),
('ws-p2-03','level-p2','3','PRACTICE'),
('ws-p2-04','level-p2','4','MIXED'),
('ws-p2-05','level-p2','5','MASTERY_CHECK'),
('ws-p3-01','level-p3','1','PRACTICE'),
('ws-p3-02','level-p3','2','PRACTICE'),
('ws-p3-03','level-p3','3','PRACTICE'),
('ws-p3-04','level-p3','4','MIXED'),
('ws-p3-05','level-p3','5','MASTERY_CHECK'),
('ws-p4-01','level-p4','1','PRACTICE'),
('ws-p4-02','level-p4','2','PRACTICE'),
('ws-p4-03','level-p4','3','PRACTICE'),
('ws-p4-04','level-p4','4','MIXED'),
('ws-p4-05','level-p4','5','MASTERY_CHECK'),
('ws-p5-01','level-p5','1','PRACTICE'),
('ws-p5-02','level-p5','2','PRACTICE'),
('ws-p5-03','level-p5','3','PRACTICE'),
('ws-p5-04','level-p5','4','MIXED'),
('ws-p5-05','level-p5','5','MASTERY_CHECK'),
('ws-p6-01','level-p6','1','PRACTICE'),
('ws-p6-02','level-p6','2','PRACTICE'),
('ws-p6-03','level-p6','3','PRACTICE'),
('ws-p6-04','level-p6','4','MIXED'),
('ws-p6-05','level-p6','5','MASTERY_CHECK'),
('ws-m1a-01','level-m1a','1','PRACTICE'),
('ws-m1a-02','level-m1a','2','PRACTICE'),
('ws-m1a-03','level-m1a','3','PRACTICE'),
('ws-m1a-04','level-m1a','4','MIXED'),
('ws-m1a-05','level-m1a','5','MASTERY_CHECK'),
('ws-m1b-01','level-m1b','1','PRACTICE'),
('ws-m1b-02','level-m1b','2','PRACTICE'),
('ws-m1b-03','level-m1b','3','PRACTICE'),
('ws-m1b-04','level-m1b','4','MIXED'),
('ws-m1b-05','level-m1b','5','MASTERY_CHECK'),
('ws-m1c-01','level-m1c','1','PRACTICE'),
('ws-m1c-02','level-m1c','2','PRACTICE'),
('ws-m1c-03','level-m1c','3','PRACTICE'),
('ws-m1c-04','level-m1c','4','MIXED'),
('ws-m1c-05','level-m1c','5','MASTERY_CHECK'),
('ws-m1d-01','level-m1d','1','PRACTICE'),
('ws-m1d-02','level-m1d','2','PRACTICE'),
('ws-m1d-03','level-m1d','3','PRACTICE'),
('ws-m1d-04','level-m1d','4','MIXED'),
('ws-m1d-05','level-m1d','5','MASTERY_CHECK');

INSERT OR IGNORE INTO mastery_worksheets (id,level_id,worksheet_index,worksheet_type) VALUES
('ws-m1e-01','level-m1e','1','PRACTICE'),
('ws-m1e-02','level-m1e','2','PRACTICE'),
('ws-m1e-03','level-m1e','3','PRACTICE'),
('ws-m1e-04','level-m1e','4','MIXED'),
('ws-m1e-05','level-m1e','5','MASTERY_CHECK'),
('ws-m1f-01','level-m1f','1','PRACTICE'),
('ws-m1f-02','level-m1f','2','PRACTICE'),
('ws-m1f-03','level-m1f','3','PRACTICE'),
('ws-m1f-04','level-m1f','4','MIXED'),
('ws-m1f-05','level-m1f','5','MASTERY_CHECK'),
('ws-m1g-01','level-m1g','1','PRACTICE'),
('ws-m1g-02','level-m1g','2','PRACTICE'),
('ws-m1g-03','level-m1g','3','PRACTICE'),
('ws-m1g-04','level-m1g','4','MIXED'),
('ws-m1g-05','level-m1g','5','MASTERY_CHECK'),
('ws-m1h-01','level-m1h','1','PRACTICE'),
('ws-m1h-02','level-m1h','2','PRACTICE'),
('ws-m1h-03','level-m1h','3','PRACTICE'),
('ws-m1h-04','level-m1h','4','MIXED'),
('ws-m1h-05','level-m1h','5','MASTERY_CHECK'),
('ws-m1i-01','level-m1i','1','PRACTICE'),
('ws-m1i-02','level-m1i','2','PRACTICE'),
('ws-m1i-03','level-m1i','3','PRACTICE'),
('ws-m1i-04','level-m1i','4','MIXED'),
('ws-m1i-05','level-m1i','5','MASTERY_CHECK'),
('ws-m1j-01','level-m1j','1','PRACTICE'),
('ws-m1j-02','level-m1j','2','PRACTICE'),
('ws-m1j-03','level-m1j','3','PRACTICE'),
('ws-m1j-04','level-m1j','4','MIXED'),
('ws-m1j-05','level-m1j','5','MASTERY_CHECK'),
('ws-m1k-01','level-m1k','1','PRACTICE'),
('ws-m1k-02','level-m1k','2','PRACTICE'),
('ws-m1k-03','level-m1k','3','PRACTICE'),
('ws-m1k-04','level-m1k','4','MIXED'),
('ws-m1k-05','level-m1k','5','MASTERY_CHECK'),
('ws-m1r-01','level-m1r','1','PRACTICE'),
('ws-m1r-02','level-m1r','2','PRACTICE'),
('ws-m1r-03','level-m1r','3','PRACTICE'),
('ws-m1r-04','level-m1r','4','MIXED'),
('ws-m1r-05','level-m1r','5','MASTERY_CHECK'),
('ws-m2a-01','level-m2a','1','PRACTICE'),
('ws-m2a-02','level-m2a','2','PRACTICE'),
('ws-m2a-03','level-m2a','3','PRACTICE'),
('ws-m2a-04','level-m2a','4','MIXED'),
('ws-m2a-05','level-m2a','5','MASTERY_CHECK'),
('ws-m2b-01','level-m2b','1','PRACTICE'),
('ws-m2b-02','level-m2b','2','PRACTICE'),
('ws-m2b-03','level-m2b','3','PRACTICE'),
('ws-m2b-04','level-m2b','4','MIXED'),
('ws-m2b-05','level-m2b','5','MASTERY_CHECK'),
('ws-m2c-01','level-m2c','1','PRACTICE'),
('ws-m2c-02','level-m2c','2','PRACTICE'),
('ws-m2c-03','level-m2c','3','PRACTICE'),
('ws-m2c-04','level-m2c','4','MIXED'),
('ws-m2c-05','level-m2c','5','MASTERY_CHECK'),
('ws-m2d-01','level-m2d','1','PRACTICE'),
('ws-m2d-02','level-m2d','2','PRACTICE'),
('ws-m2d-03','level-m2d','3','PRACTICE'),
('ws-m2d-04','level-m2d','4','MIXED'),
('ws-m2d-05','level-m2d','5','MASTERY_CHECK'),
('ws-m2e-01','level-m2e','1','PRACTICE'),
('ws-m2e-02','level-m2e','2','PRACTICE'),
('ws-m2e-03','level-m2e','3','PRACTICE'),
('ws-m2e-04','level-m2e','4','MIXED'),
('ws-m2e-05','level-m2e','5','MASTERY_CHECK'),
('ws-m2f-01','level-m2f','1','PRACTICE'),
('ws-m2f-02','level-m2f','2','PRACTICE'),
('ws-m2f-03','level-m2f','3','PRACTICE'),
('ws-m2f-04','level-m2f','4','MIXED'),
('ws-m2f-05','level-m2f','5','MASTERY_CHECK'),
('ws-m2g-01','level-m2g','1','PRACTICE'),
('ws-m2g-02','level-m2g','2','PRACTICE'),
('ws-m2g-03','level-m2g','3','PRACTICE'),
('ws-m2g-04','level-m2g','4','MIXED'),
('ws-m2g-05','level-m2g','5','MASTERY_CHECK'),
('ws-m2h-01','level-m2h','1','PRACTICE'),
('ws-m2h-02','level-m2h','2','PRACTICE'),
('ws-m2h-03','level-m2h','3','PRACTICE'),
('ws-m2h-04','level-m2h','4','MIXED'),
('ws-m2h-05','level-m2h','5','MASTERY_CHECK'),
('ws-m2i-01','level-m2i','1','PRACTICE'),
('ws-m2i-02','level-m2i','2','PRACTICE'),
('ws-m2i-03','level-m2i','3','PRACTICE'),
('ws-m2i-04','level-m2i','4','MIXED'),
('ws-m2i-05','level-m2i','5','MASTERY_CHECK'),
('ws-m2j-01','level-m2j','1','PRACTICE'),
('ws-m2j-02','level-m2j','2','PRACTICE'),
('ws-m2j-03','level-m2j','3','PRACTICE'),
('ws-m2j-04','level-m2j','4','MIXED'),
('ws-m2j-05','level-m2j','5','MASTERY_CHECK'),
('ws-m2r-01','level-m2r','1','PRACTICE'),
('ws-m2r-02','level-m2r','2','PRACTICE'),
('ws-m2r-03','level-m2r','3','PRACTICE'),
('ws-m2r-04','level-m2r','4','MIXED'),
('ws-m2r-05','level-m2r','5','MASTERY_CHECK'),
('ws-m3a-01','level-m3a','1','PRACTICE'),
('ws-m3a-02','level-m3a','2','PRACTICE'),
('ws-m3a-03','level-m3a','3','PRACTICE'),
('ws-m3a-04','level-m3a','4','MIXED'),
('ws-m3a-05','level-m3a','5','MASTERY_CHECK'),
('ws-m3b-01','level-m3b','1','PRACTICE'),
('ws-m3b-02','level-m3b','2','PRACTICE'),
('ws-m3b-03','level-m3b','3','PRACTICE'),
('ws-m3b-04','level-m3b','4','MIXED'),
('ws-m3b-05','level-m3b','5','MASTERY_CHECK'),
('ws-m3c-01','level-m3c','1','PRACTICE'),
('ws-m3c-02','level-m3c','2','PRACTICE'),
('ws-m3c-03','level-m3c','3','PRACTICE'),
('ws-m3c-04','level-m3c','4','MIXED'),
('ws-m3c-05','level-m3c','5','MASTERY_CHECK'),
('ws-m3d-01','level-m3d','1','PRACTICE'),
('ws-m3d-02','level-m3d','2','PRACTICE'),
('ws-m3d-03','level-m3d','3','PRACTICE'),
('ws-m3d-04','level-m3d','4','MIXED'),
('ws-m3d-05','level-m3d','5','MASTERY_CHECK'),
('ws-m3e-01','level-m3e','1','PRACTICE'),
('ws-m3e-02','level-m3e','2','PRACTICE'),
('ws-m3e-03','level-m3e','3','PRACTICE'),
('ws-m3e-04','level-m3e','4','MIXED'),
('ws-m3e-05','level-m3e','5','MASTERY_CHECK'),
('ws-m3f-01','level-m3f','1','PRACTICE'),
('ws-m3f-02','level-m3f','2','PRACTICE'),
('ws-m3f-03','level-m3f','3','PRACTICE'),
('ws-m3f-04','level-m3f','4','MIXED'),
('ws-m3f-05','level-m3f','5','MASTERY_CHECK');

INSERT OR IGNORE INTO mastery_worksheets (id,level_id,worksheet_index,worksheet_type) VALUES
('ws-m3g-01','level-m3g','1','PRACTICE'),
('ws-m3g-02','level-m3g','2','PRACTICE'),
('ws-m3g-03','level-m3g','3','PRACTICE'),
('ws-m3g-04','level-m3g','4','MIXED'),
('ws-m3g-05','level-m3g','5','MASTERY_CHECK'),
('ws-m3h-01','level-m3h','1','PRACTICE'),
('ws-m3h-02','level-m3h','2','PRACTICE'),
('ws-m3h-03','level-m3h','3','PRACTICE'),
('ws-m3h-04','level-m3h','4','MIXED'),
('ws-m3h-05','level-m3h','5','MASTERY_CHECK'),
('ws-m3i-01','level-m3i','1','PRACTICE'),
('ws-m3i-02','level-m3i','2','PRACTICE'),
('ws-m3i-03','level-m3i','3','PRACTICE'),
('ws-m3i-04','level-m3i','4','MIXED'),
('ws-m3i-05','level-m3i','5','MASTERY_CHECK'),
('ws-m3j-01','level-m3j','1','PRACTICE'),
('ws-m3j-02','level-m3j','2','PRACTICE'),
('ws-m3j-03','level-m3j','3','PRACTICE'),
('ws-m3j-04','level-m3j','4','MIXED'),
('ws-m3j-05','level-m3j','5','MASTERY_CHECK'),
('ws-m3k-01','level-m3k','1','PRACTICE'),
('ws-m3k-02','level-m3k','2','PRACTICE'),
('ws-m3k-03','level-m3k','3','PRACTICE'),
('ws-m3k-04','level-m3k','4','MIXED'),
('ws-m3k-05','level-m3k','5','MASTERY_CHECK'),
('ws-m3l-01','level-m3l','1','PRACTICE'),
('ws-m3l-02','level-m3l','2','PRACTICE'),
('ws-m3l-03','level-m3l','3','PRACTICE'),
('ws-m3l-04','level-m3l','4','MIXED'),
('ws-m3l-05','level-m3l','5','MASTERY_CHECK'),
('ws-m3r-01','level-m3r','1','PRACTICE'),
('ws-m3r-02','level-m3r','2','PRACTICE'),
('ws-m3r-03','level-m3r','3','PRACTICE'),
('ws-m3r-04','level-m3r','4','MIXED'),
('ws-m3r-05','level-m3r','5','MASTERY_CHECK'),
('ws-x3-01','level-x3','1','PRACTICE'),
('ws-x3-02','level-x3','2','PRACTICE'),
('ws-x3-03','level-x3','3','PRACTICE'),
('ws-x3-04','level-x3','4','MIXED'),
('ws-x3-05','level-x3','5','MASTERY_CHECK'),
('ws-x6-01','level-x6','1','PRACTICE'),
('ws-x6-02','level-x6','2','PRACTICE'),
('ws-x6-03','level-x6','3','PRACTICE'),
('ws-x6-04','level-x6','4','MIXED'),
('ws-x6-05','level-x6','5','MASTERY_CHECK'),
('ws-d1a-01','level-d1a','1','PRACTICE'),
('ws-d1a-02','level-d1a','2','PRACTICE'),
('ws-d1a-03','level-d1a','3','PRACTICE'),
('ws-d1a-04','level-d1a','4','MIXED'),
('ws-d1a-05','level-d1a','5','MASTERY_CHECK'),
('ws-d1b-01','level-d1b','1','PRACTICE'),
('ws-d1b-02','level-d1b','2','PRACTICE'),
('ws-d1b-03','level-d1b','3','PRACTICE'),
('ws-d1b-04','level-d1b','4','MIXED'),
('ws-d1b-05','level-d1b','5','MASTERY_CHECK'),
('ws-d1c-01','level-d1c','1','PRACTICE'),
('ws-d1c-02','level-d1c','2','PRACTICE'),
('ws-d1c-03','level-d1c','3','PRACTICE'),
('ws-d1c-04','level-d1c','4','MIXED'),
('ws-d1c-05','level-d1c','5','MASTERY_CHECK'),
('ws-d1d-01','level-d1d','1','PRACTICE'),
('ws-d1d-02','level-d1d','2','PRACTICE'),
('ws-d1d-03','level-d1d','3','PRACTICE'),
('ws-d1d-04','level-d1d','4','MIXED'),
('ws-d1d-05','level-d1d','5','MASTERY_CHECK'),
('ws-d1e-01','level-d1e','1','PRACTICE'),
('ws-d1e-02','level-d1e','2','PRACTICE'),
('ws-d1e-03','level-d1e','3','PRACTICE'),
('ws-d1e-04','level-d1e','4','MIXED'),
('ws-d1e-05','level-d1e','5','MASTERY_CHECK'),
('ws-d1f-01','level-d1f','1','PRACTICE'),
('ws-d1f-02','level-d1f','2','PRACTICE'),
('ws-d1f-03','level-d1f','3','PRACTICE'),
('ws-d1f-04','level-d1f','4','MIXED'),
('ws-d1f-05','level-d1f','5','MASTERY_CHECK'),
('ws-d1r-01','level-d1r','1','PRACTICE'),
('ws-d1r-02','level-d1r','2','PRACTICE'),
('ws-d1r-03','level-d1r','3','PRACTICE'),
('ws-d1r-04','level-d1r','4','MIXED'),
('ws-d1r-05','level-d1r','5','MASTERY_CHECK'),
('ws-d2a-01','level-d2a','1','PRACTICE'),
('ws-d2a-02','level-d2a','2','PRACTICE'),
('ws-d2a-03','level-d2a','3','PRACTICE'),
('ws-d2a-04','level-d2a','4','MIXED'),
('ws-d2a-05','level-d2a','5','MASTERY_CHECK'),
('ws-d2b-01','level-d2b','1','PRACTICE'),
('ws-d2b-02','level-d2b','2','PRACTICE'),
('ws-d2b-03','level-d2b','3','PRACTICE'),
('ws-d2b-04','level-d2b','4','MIXED'),
('ws-d2b-05','level-d2b','5','MASTERY_CHECK'),
('ws-d2c-01','level-d2c','1','PRACTICE'),
('ws-d2c-02','level-d2c','2','PRACTICE'),
('ws-d2c-03','level-d2c','3','PRACTICE'),
('ws-d2c-04','level-d2c','4','MIXED'),
('ws-d2c-05','level-d2c','5','MASTERY_CHECK'),
('ws-d2d-01','level-d2d','1','PRACTICE'),
('ws-d2d-02','level-d2d','2','PRACTICE'),
('ws-d2d-03','level-d2d','3','PRACTICE'),
('ws-d2d-04','level-d2d','4','MIXED'),
('ws-d2d-05','level-d2d','5','MASTERY_CHECK'),
('ws-d2e-01','level-d2e','1','PRACTICE'),
('ws-d2e-02','level-d2e','2','PRACTICE'),
('ws-d2e-03','level-d2e','3','PRACTICE'),
('ws-d2e-04','level-d2e','4','MIXED'),
('ws-d2e-05','level-d2e','5','MASTERY_CHECK'),
('ws-d2f-01','level-d2f','1','PRACTICE'),
('ws-d2f-02','level-d2f','2','PRACTICE'),
('ws-d2f-03','level-d2f','3','PRACTICE'),
('ws-d2f-04','level-d2f','4','MIXED'),
('ws-d2f-05','level-d2f','5','MASTERY_CHECK'),
('ws-d2r-01','level-d2r','1','PRACTICE'),
('ws-d2r-02','level-d2r','2','PRACTICE'),
('ws-d2r-03','level-d2r','3','PRACTICE'),
('ws-d2r-04','level-d2r','4','MIXED'),
('ws-d2r-05','level-d2r','5','MASTERY_CHECK'),
('ws-d3a-01','level-d3a','1','PRACTICE'),
('ws-d3a-02','level-d3a','2','PRACTICE'),
('ws-d3a-03','level-d3a','3','PRACTICE'),
('ws-d3a-04','level-d3a','4','MIXED'),
('ws-d3a-05','level-d3a','5','MASTERY_CHECK'),
('ws-d3b-01','level-d3b','1','PRACTICE'),
('ws-d3b-02','level-d3b','2','PRACTICE'),
('ws-d3b-03','level-d3b','3','PRACTICE'),
('ws-d3b-04','level-d3b','4','MIXED'),
('ws-d3b-05','level-d3b','5','MASTERY_CHECK');

INSERT OR IGNORE INTO mastery_worksheets (id,level_id,worksheet_index,worksheet_type) VALUES
('ws-d3c-01','level-d3c','1','PRACTICE'),
('ws-d3c-02','level-d3c','2','PRACTICE'),
('ws-d3c-03','level-d3c','3','PRACTICE'),
('ws-d3c-04','level-d3c','4','MIXED'),
('ws-d3c-05','level-d3c','5','MASTERY_CHECK'),
('ws-d3d-01','level-d3d','1','PRACTICE'),
('ws-d3d-02','level-d3d','2','PRACTICE'),
('ws-d3d-03','level-d3d','3','PRACTICE'),
('ws-d3d-04','level-d3d','4','MIXED'),
('ws-d3d-05','level-d3d','5','MASTERY_CHECK'),
('ws-d3e-01','level-d3e','1','PRACTICE'),
('ws-d3e-02','level-d3e','2','PRACTICE'),
('ws-d3e-03','level-d3e','3','PRACTICE'),
('ws-d3e-04','level-d3e','4','MIXED'),
('ws-d3e-05','level-d3e','5','MASTERY_CHECK'),
('ws-d3f-01','level-d3f','1','PRACTICE'),
('ws-d3f-02','level-d3f','2','PRACTICE'),
('ws-d3f-03','level-d3f','3','PRACTICE'),
('ws-d3f-04','level-d3f','4','MIXED'),
('ws-d3f-05','level-d3f','5','MASTERY_CHECK'),
('ws-d3g-01','level-d3g','1','PRACTICE'),
('ws-d3g-02','level-d3g','2','PRACTICE'),
('ws-d3g-03','level-d3g','3','PRACTICE'),
('ws-d3g-04','level-d3g','4','MIXED'),
('ws-d3g-05','level-d3g','5','MASTERY_CHECK'),
('ws-d3r-01','level-d3r','1','PRACTICE'),
('ws-d3r-02','level-d3r','2','PRACTICE'),
('ws-d3r-03','level-d3r','3','PRACTICE'),
('ws-d3r-04','level-d3r','4','MIXED'),
('ws-d3r-05','level-d3r','5','MASTERY_CHECK'),
('ws-d4a-01','level-d4a','1','PRACTICE'),
('ws-d4a-02','level-d4a','2','PRACTICE'),
('ws-d4a-03','level-d4a','3','PRACTICE'),
('ws-d4a-04','level-d4a','4','MIXED'),
('ws-d4a-05','level-d4a','5','MASTERY_CHECK'),
('ws-d4b-01','level-d4b','1','PRACTICE'),
('ws-d4b-02','level-d4b','2','PRACTICE'),
('ws-d4b-03','level-d4b','3','PRACTICE'),
('ws-d4b-04','level-d4b','4','MIXED'),
('ws-d4b-05','level-d4b','5','MASTERY_CHECK'),
('ws-d4c-01','level-d4c','1','PRACTICE'),
('ws-d4c-02','level-d4c','2','PRACTICE'),
('ws-d4c-03','level-d4c','3','PRACTICE'),
('ws-d4c-04','level-d4c','4','MIXED'),
('ws-d4c-05','level-d4c','5','MASTERY_CHECK'),
('ws-d4d-01','level-d4d','1','PRACTICE'),
('ws-d4d-02','level-d4d','2','PRACTICE'),
('ws-d4d-03','level-d4d','3','PRACTICE'),
('ws-d4d-04','level-d4d','4','MIXED'),
('ws-d4d-05','level-d4d','5','MASTERY_CHECK'),
('ws-d4e-01','level-d4e','1','PRACTICE'),
('ws-d4e-02','level-d4e','2','PRACTICE'),
('ws-d4e-03','level-d4e','3','PRACTICE'),
('ws-d4e-04','level-d4e','4','MIXED'),
('ws-d4e-05','level-d4e','5','MASTERY_CHECK'),
('ws-d4r-01','level-d4r','1','PRACTICE'),
('ws-d4r-02','level-d4r','2','PRACTICE'),
('ws-d4r-03','level-d4r','3','PRACTICE'),
('ws-d4r-04','level-d4r','4','MIXED'),
('ws-d4r-05','level-d4r','5','MASTERY_CHECK'),
('ws-x7-01','level-x7','1','PRACTICE'),
('ws-x7-02','level-x7','2','PRACTICE'),
('ws-x7-03','level-x7','3','PRACTICE'),
('ws-x7-04','level-x7','4','MIXED'),
('ws-x7-05','level-x7','5','MASTERY_CHECK'),
('ws-d5a-01','level-d5a','1','PRACTICE'),
('ws-d5a-02','level-d5a','2','PRACTICE'),
('ws-d5a-03','level-d5a','3','PRACTICE'),
('ws-d5a-04','level-d5a','4','MIXED'),
('ws-d5a-05','level-d5a','5','MASTERY_CHECK'),
('ws-d5b-01','level-d5b','1','PRACTICE'),
('ws-d5b-02','level-d5b','2','PRACTICE'),
('ws-d5b-03','level-d5b','3','PRACTICE'),
('ws-d5b-04','level-d5b','4','MIXED'),
('ws-d5b-05','level-d5b','5','MASTERY_CHECK'),
('ws-d5c-01','level-d5c','1','PRACTICE'),
('ws-d5c-02','level-d5c','2','PRACTICE'),
('ws-d5c-03','level-d5c','3','PRACTICE'),
('ws-d5c-04','level-d5c','4','MIXED'),
('ws-d5c-05','level-d5c','5','MASTERY_CHECK'),
('ws-d5d-01','level-d5d','1','PRACTICE'),
('ws-d5d-02','level-d5d','2','PRACTICE'),
('ws-d5d-03','level-d5d','3','PRACTICE'),
('ws-d5d-04','level-d5d','4','MIXED'),
('ws-d5d-05','level-d5d','5','MASTERY_CHECK'),
('ws-d5e-01','level-d5e','1','PRACTICE'),
('ws-d5e-02','level-d5e','2','PRACTICE'),
('ws-d5e-03','level-d5e','3','PRACTICE'),
('ws-d5e-04','level-d5e','4','MIXED'),
('ws-d5e-05','level-d5e','5','MASTERY_CHECK'),
('ws-d5r-01','level-d5r','1','PRACTICE'),
('ws-d5r-02','level-d5r','2','PRACTICE'),
('ws-d5r-03','level-d5r','3','PRACTICE'),
('ws-d5r-04','level-d5r','4','MIXED'),
('ws-d5r-05','level-d5r','5','MASTERY_CHECK'),
('ws-d6a-01','level-d6a','1','PRACTICE'),
('ws-d6a-02','level-d6a','2','PRACTICE'),
('ws-d6a-03','level-d6a','3','PRACTICE'),
('ws-d6a-04','level-d6a','4','MIXED'),
('ws-d6a-05','level-d6a','5','MASTERY_CHECK'),
('ws-d6b-01','level-d6b','1','PRACTICE'),
('ws-d6b-02','level-d6b','2','PRACTICE'),
('ws-d6b-03','level-d6b','3','PRACTICE'),
('ws-d6b-04','level-d6b','4','MIXED'),
('ws-d6b-05','level-d6b','5','MASTERY_CHECK'),
('ws-d6c-01','level-d6c','1','PRACTICE'),
('ws-d6c-02','level-d6c','2','PRACTICE'),
('ws-d6c-03','level-d6c','3','PRACTICE'),
('ws-d6c-04','level-d6c','4','MIXED'),
('ws-d6c-05','level-d6c','5','MASTERY_CHECK'),
('ws-d7a-01','level-d7a','1','PRACTICE'),
('ws-d7a-02','level-d7a','2','PRACTICE'),
('ws-d7a-03','level-d7a','3','PRACTICE'),
('ws-d7a-04','level-d7a','4','MIXED'),
('ws-d7a-05','level-d7a','5','MASTERY_CHECK'),
('ws-d7b-01','level-d7b','1','PRACTICE'),
('ws-d7b-02','level-d7b','2','PRACTICE'),
('ws-d7b-03','level-d7b','3','PRACTICE'),
('ws-d7b-04','level-d7b','4','MIXED'),
('ws-d7b-05','level-d7b','5','MASTERY_CHECK'),
('ws-d7c-01','level-d7c','1','PRACTICE'),
('ws-d7c-02','level-d7c','2','PRACTICE'),
('ws-d7c-03','level-d7c','3','PRACTICE'),
('ws-d7c-04','level-d7c','4','MIXED'),
('ws-d7c-05','level-d7c','5','MASTERY_CHECK');

INSERT OR IGNORE INTO mastery_worksheets (id,level_id,worksheet_index,worksheet_type) VALUES
('ws-d7d-01','level-d7d','1','PRACTICE'),
('ws-d7d-02','level-d7d','2','PRACTICE'),
('ws-d7d-03','level-d7d','3','PRACTICE'),
('ws-d7d-04','level-d7d','4','MIXED'),
('ws-d7d-05','level-d7d','5','MASTERY_CHECK'),
('ws-d-r-01','level-d-r','1','PRACTICE'),
('ws-d-r-02','level-d-r','2','PRACTICE'),
('ws-d-r-03','level-d-r','3','PRACTICE'),
('ws-d-r-04','level-d-r','4','MIXED'),
('ws-d-r-05','level-d-r','5','MASTERY_CHECK'),
('ws-g1a-01','level-g1a','1','PRACTICE'),
('ws-g1a-02','level-g1a','2','PRACTICE'),
('ws-g1a-03','level-g1a','3','PRACTICE'),
('ws-g1a-04','level-g1a','4','MIXED'),
('ws-g1a-05','level-g1a','5','MASTERY_CHECK'),
('ws-g1b-01','level-g1b','1','PRACTICE'),
('ws-g1b-02','level-g1b','2','PRACTICE'),
('ws-g1b-03','level-g1b','3','PRACTICE'),
('ws-g1b-04','level-g1b','4','MIXED'),
('ws-g1b-05','level-g1b','5','MASTERY_CHECK'),
('ws-g1c-01','level-g1c','1','PRACTICE'),
('ws-g1c-02','level-g1c','2','PRACTICE'),
('ws-g1c-03','level-g1c','3','PRACTICE'),
('ws-g1c-04','level-g1c','4','MIXED'),
('ws-g1c-05','level-g1c','5','MASTERY_CHECK'),
('ws-g1d-01','level-g1d','1','PRACTICE'),
('ws-g1d-02','level-g1d','2','PRACTICE'),
('ws-g1d-03','level-g1d','3','PRACTICE'),
('ws-g1d-04','level-g1d','4','MIXED'),
('ws-g1d-05','level-g1d','5','MASTERY_CHECK'),
('ws-g1e-01','level-g1e','1','PRACTICE'),
('ws-g1e-02','level-g1e','2','PRACTICE'),
('ws-g1e-03','level-g1e','3','PRACTICE'),
('ws-g1e-04','level-g1e','4','MIXED'),
('ws-g1e-05','level-g1e','5','MASTERY_CHECK'),
('ws-g1f-01','level-g1f','1','PRACTICE'),
('ws-g1f-02','level-g1f','2','PRACTICE'),
('ws-g1f-03','level-g1f','3','PRACTICE'),
('ws-g1f-04','level-g1f','4','MIXED'),
('ws-g1f-05','level-g1f','5','MASTERY_CHECK'),
('ws-g1g-01','level-g1g','1','PRACTICE'),
('ws-g1g-02','level-g1g','2','PRACTICE'),
('ws-g1g-03','level-g1g','3','PRACTICE'),
('ws-g1g-04','level-g1g','4','MIXED'),
('ws-g1g-05','level-g1g','5','MASTERY_CHECK'),
('ws-g1r-01','level-g1r','1','PRACTICE'),
('ws-g1r-02','level-g1r','2','PRACTICE'),
('ws-g1r-03','level-g1r','3','PRACTICE'),
('ws-g1r-04','level-g1r','4','MIXED'),
('ws-g1r-05','level-g1r','5','MASTERY_CHECK'),
('ws-g3a-01','level-g3a','1','PRACTICE'),
('ws-g3a-02','level-g3a','2','PRACTICE'),
('ws-g3a-03','level-g3a','3','PRACTICE'),
('ws-g3a-04','level-g3a','4','MIXED'),
('ws-g3a-05','level-g3a','5','MASTERY_CHECK'),
('ws-g3b-01','level-g3b','1','PRACTICE'),
('ws-g3b-02','level-g3b','2','PRACTICE'),
('ws-g3b-03','level-g3b','3','PRACTICE'),
('ws-g3b-04','level-g3b','4','MIXED'),
('ws-g3b-05','level-g3b','5','MASTERY_CHECK'),
('ws-g3c-01','level-g3c','1','PRACTICE'),
('ws-g3c-02','level-g3c','2','PRACTICE'),
('ws-g3c-03','level-g3c','3','PRACTICE'),
('ws-g3c-04','level-g3c','4','MIXED'),
('ws-g3c-05','level-g3c','5','MASTERY_CHECK'),
('ws-g3d-01','level-g3d','1','PRACTICE'),
('ws-g3d-02','level-g3d','2','PRACTICE'),
('ws-g3d-03','level-g3d','3','PRACTICE'),
('ws-g3d-04','level-g3d','4','MIXED'),
('ws-g3d-05','level-g3d','5','MASTERY_CHECK'),
('ws-g3e-01','level-g3e','1','PRACTICE'),
('ws-g3e-02','level-g3e','2','PRACTICE'),
('ws-g3e-03','level-g3e','3','PRACTICE'),
('ws-g3e-04','level-g3e','4','MIXED'),
('ws-g3e-05','level-g3e','5','MASTERY_CHECK'),
('ws-g3f-01','level-g3f','1','PRACTICE'),
('ws-g3f-02','level-g3f','2','PRACTICE'),
('ws-g3f-03','level-g3f','3','PRACTICE'),
('ws-g3f-04','level-g3f','4','MIXED'),
('ws-g3f-05','level-g3f','5','MASTERY_CHECK'),
('ws-g3g-01','level-g3g','1','PRACTICE'),
('ws-g3g-02','level-g3g','2','PRACTICE'),
('ws-g3g-03','level-g3g','3','PRACTICE'),
('ws-g3g-04','level-g3g','4','MIXED'),
('ws-g3g-05','level-g3g','5','MASTERY_CHECK'),
('ws-g3r-01','level-g3r','1','PRACTICE'),
('ws-g3r-02','level-g3r','2','PRACTICE'),
('ws-g3r-03','level-g3r','3','PRACTICE'),
('ws-g3r-04','level-g3r','4','MIXED'),
('ws-g3r-05','level-g3r','5','MASTERY_CHECK'),
('ws-g2a-01','level-g2a','1','PRACTICE'),
('ws-g2a-02','level-g2a','2','PRACTICE'),
('ws-g2a-03','level-g2a','3','PRACTICE'),
('ws-g2a-04','level-g2a','4','MIXED'),
('ws-g2a-05','level-g2a','5','MASTERY_CHECK'),
('ws-g2b-01','level-g2b','1','PRACTICE'),
('ws-g2b-02','level-g2b','2','PRACTICE'),
('ws-g2b-03','level-g2b','3','PRACTICE'),
('ws-g2b-04','level-g2b','4','MIXED'),
('ws-g2b-05','level-g2b','5','MASTERY_CHECK'),
('ws-g2c-01','level-g2c','1','PRACTICE'),
('ws-g2c-02','level-g2c','2','PRACTICE'),
('ws-g2c-03','level-g2c','3','PRACTICE'),
('ws-g2c-04','level-g2c','4','MIXED'),
('ws-g2c-05','level-g2c','5','MASTERY_CHECK'),
('ws-g2d-01','level-g2d','1','PRACTICE'),
('ws-g2d-02','level-g2d','2','PRACTICE'),
('ws-g2d-03','level-g2d','3','PRACTICE'),
('ws-g2d-04','level-g2d','4','MIXED'),
('ws-g2d-05','level-g2d','5','MASTERY_CHECK'),
('ws-g2e-01','level-g2e','1','PRACTICE'),
('ws-g2e-02','level-g2e','2','PRACTICE'),
('ws-g2e-03','level-g2e','3','PRACTICE'),
('ws-g2e-04','level-g2e','4','MIXED'),
('ws-g2e-05','level-g2e','5','MASTERY_CHECK'),
('ws-g2f-01','level-g2f','1','PRACTICE'),
('ws-g2f-02','level-g2f','2','PRACTICE'),
('ws-g2f-03','level-g2f','3','PRACTICE'),
('ws-g2f-04','level-g2f','4','MIXED'),
('ws-g2f-05','level-g2f','5','MASTERY_CHECK'),
('ws-g2g-01','level-g2g','1','PRACTICE'),
('ws-g2g-02','level-g2g','2','PRACTICE'),
('ws-g2g-03','level-g2g','3','PRACTICE'),
('ws-g2g-04','level-g2g','4','MIXED'),
('ws-g2g-05','level-g2g','5','MASTERY_CHECK');

INSERT OR IGNORE INTO mastery_worksheets (id,level_id,worksheet_index,worksheet_type) VALUES
('ws-g2r-01','level-g2r','1','PRACTICE'),
('ws-g2r-02','level-g2r','2','PRACTICE'),
('ws-g2r-03','level-g2r','3','PRACTICE'),
('ws-g2r-04','level-g2r','4','MIXED'),
('ws-g2r-05','level-g2r','5','MASTERY_CHECK'),
('ws-g4f-01','level-g4f','1','PRACTICE'),
('ws-g4f-02','level-g4f','2','PRACTICE'),
('ws-g4f-03','level-g4f','3','PRACTICE'),
('ws-g4f-04','level-g4f','4','MIXED'),
('ws-g4f-05','level-g4f','5','MASTERY_CHECK'),
('ws-g4a-01','level-g4a','1','PRACTICE'),
('ws-g4a-02','level-g4a','2','PRACTICE'),
('ws-g4a-03','level-g4a','3','PRACTICE'),
('ws-g4a-04','level-g4a','4','MIXED'),
('ws-g4a-05','level-g4a','5','MASTERY_CHECK'),
('ws-g4b-01','level-g4b','1','PRACTICE'),
('ws-g4b-02','level-g4b','2','PRACTICE'),
('ws-g4b-03','level-g4b','3','PRACTICE'),
('ws-g4b-04','level-g4b','4','MIXED'),
('ws-g4b-05','level-g4b','5','MASTERY_CHECK'),
('ws-g4c-01','level-g4c','1','PRACTICE'),
('ws-g4c-02','level-g4c','2','PRACTICE'),
('ws-g4c-03','level-g4c','3','PRACTICE'),
('ws-g4c-04','level-g4c','4','MIXED'),
('ws-g4c-05','level-g4c','5','MASTERY_CHECK'),
('ws-g4d-01','level-g4d','1','PRACTICE'),
('ws-g4d-02','level-g4d','2','PRACTICE'),
('ws-g4d-03','level-g4d','3','PRACTICE'),
('ws-g4d-04','level-g4d','4','MIXED'),
('ws-g4d-05','level-g4d','5','MASTERY_CHECK'),
('ws-g4e-01','level-g4e','1','PRACTICE'),
('ws-g4e-02','level-g4e','2','PRACTICE'),
('ws-g4e-03','level-g4e','3','PRACTICE'),
('ws-g4e-04','level-g4e','4','MIXED'),
('ws-g4e-05','level-g4e','5','MASTERY_CHECK'),
('ws-g4g-01','level-g4g','1','PRACTICE'),
('ws-g4g-02','level-g4g','2','PRACTICE'),
('ws-g4g-03','level-g4g','3','PRACTICE'),
('ws-g4g-04','level-g4g','4','MIXED'),
('ws-g4g-05','level-g4g','5','MASTERY_CHECK'),
('ws-g4h-01','level-g4h','1','PRACTICE'),
('ws-g4h-02','level-g4h','2','PRACTICE'),
('ws-g4h-03','level-g4h','3','PRACTICE'),
('ws-g4h-04','level-g4h','4','MIXED'),
('ws-g4h-05','level-g4h','5','MASTERY_CHECK'),
('ws-g4r-01','level-g4r','1','PRACTICE'),
('ws-g4r-02','level-g4r','2','PRACTICE'),
('ws-g4r-03','level-g4r','3','PRACTICE'),
('ws-g4r-04','level-g4r','4','MIXED'),
('ws-g4r-05','level-g4r','5','MASTERY_CHECK');

INSERT OR IGNORE INTO mastery_students
    (id,display_name,placement_level_index,current_level_id,daily_page_target)
    VALUES ('demo-student','Alex',1,'level-f1a',3);

PRAGMA optimize;
