PRAGMA foreign_keys = OFF;

DELETE FROM mastery_attempts;

DELETE FROM mastery_records;

DELETE FROM mastery_problems;

DELETE FROM mastery_worksheets;

DELETE FROM mastery_students;

DELETE FROM mastery_levels;

DELETE FROM mastery_skills;

DELETE FROM mastery_strands;

INSERT INTO mastery_strands (code,name,sort_order) VALUES
('F','Foundations','1'),
('A','Algebra','2'),
('M','Advanced Math','3'),
('D','Problem-Solving & Data Analysis','4'),
('G','Geometry & Trigonometry','5');

INSERT INTO mastery_skills (code,name,strand_code,sort_order) VALUES
('F1','Number fluency','F','1'),
('F2','Expressions','F','2'),
('F3','Equation moves','F','3'),
('F4','Coordinate & graph reading','F','4'),
('A1','Linear equations in one variable','A','5'),
('A2','Linear equations in two variables','A','6'),
('A3','Linear functions','A','7'),
('A4','Systems of two linear equations','A','8'),
('A5','Linear inequalities','A','9'),
('M1','Equivalent expressions','M','10'),
('M2','Nonlinear equations & systems','M','11'),
('M3','Nonlinear functions','M','12'),
('D1','Ratios, rates, proportional relationships, units','D','13'),
('D2','Percentages','D','14'),
('D3','One-variable data','D','15'),
('D4','Two-variable data','D','16'),
('D5','Probability','D','17'),
('D6','Inference and margin of error','D','18'),
('D7','Evaluating statistical claims','D','19'),
('G1','Lines, angles, triangles','G','20'),
('G2','Right triangles and trigonometry','G','21'),
('G3','Area and volume','G','22'),
('G4','Circles','G','23');

INSERT INTO mastery_levels (id,code,name,strand_code,skill_code,sequence_index,tier,time_standard_seconds,accuracy_threshold,video_url) VALUES
('subskill-f1a','F1a','Signed numbers: + and −','F','F1','1','CORE',NULL,'90',''),
('subskill-f1b','F1b','Signed numbers: × and ÷','F','F1','2','CORE',NULL,'90',''),
('subskill-f1c','F1c','Fractions: add/subtract, unlike denominators','F','F1','3','CORE',NULL,'90',''),
('subskill-f1d','F1d','Fractions: multiply/divide, complex fractions','F','F1','4','CORE',NULL,'90',''),
('subskill-f1e','F1e','Fraction ↔ decimal ↔ percent','F','F1','5','CORE',NULL,'90',''),
('subskill-f1f','F1f','Order of operations with negatives and fractions','F','F1','6','CORE',NULL,'90',''),
('subskill-f1r','F1R','Interleaved review','F','F1','7','CORE',NULL,'90',''),
('subskill-f2a','F2a','Combining like terms','F','F2','8','CORE',NULL,'90',''),
('subskill-f2b','F2b','Distributing (including negative distribution)','F','F2','9','CORE',NULL,'90',''),
('subskill-f2c','F2c','Exponent rules: product, quotient, power','F','F2','10','CORE',NULL,'90',''),
('subskill-f2d','F2d','Zero and negative exponents','F','F2','11','CORE',NULL,'90',''),
('subskill-f2e','F2e','Evaluating by substitution','F','F2','12','CORE',NULL,'90',''),
('subskill-f2f','F2f','Words → expressions: the basic vocabulary','F','F2','13','CORE',NULL,'90',''),
('subskill-f2r','F2R','Interleaved review','F','F2','14','CORE',NULL,'90',''),
('subskill-f3a','F3a','One-step','F','F3','15','CORE',NULL,'90',''),
('subskill-f3b','F3b','Two-step','F','F3','16','CORE',NULL,'90',''),
('subskill-f3c','F3c','Variables on both sides','F','F3','17','CORE',NULL,'90',''),
('subskill-f3d','F3d','Clearing fractions','F','F3','18','CORE',NULL,'90',''),
('subskill-f3e','F3e','Parentheses','F','F3','19','CORE',NULL,'90',''),
('subskill-f3f','F3f','Literal equations','F','F3','20','CORE',NULL,'90',''),
('subskill-f3r','F3R','Interleaved review','F','F3','21','CORE',NULL,'90',''),
('subskill-f4a','F4a','Plotting points, quadrants','F','F4','22','CORE',NULL,'90',''),
('subskill-f4b','F4b','Reading values off a graph','F','F4','23','CORE',NULL,'90',''),
('subskill-f4c','F4c','Bar graphs, line graphs, frequency tables','F','F4','24','CORE',NULL,'90',''),
('subskill-f4d','F4d','Matching tables to graphs','F','F4','25','CORE',NULL,'90',''),
('subskill-f4e','F4e','Axis scale and units','F','F4','26','CORE',NULL,'90',''),
('subskill-f4r','F4R','Interleaved review','F','F4','27','CORE',NULL,'90',''),
('subskill-a1a','A1a','Integer coefficients','A','A1','28','CORE',NULL,'90',''),
('subskill-a1b','A1b','Distribute then solve','A','A1','29','CORE',NULL,'90',''),
('subskill-a1c','A1c','Variables on both sides','A','A1','30','CORE',NULL,'90',''),
('subskill-a1d','A1d','Fractional & decimal coefficients','A','A1','31','CORE',NULL,'90',''),
('subskill-a1e','A1e','Word problem → one equation, single quantity','A','A1','32','CORE',NULL,'90',''),
('subskill-a1f','A1f','Word problem → one equation, two related quantities','A','A1','33','CORE',NULL,'90',''),
('subskill-a1g','A1g','No solution vs infinitely many','A','A1','34','CORE',NULL,'90',''),
('subskill-a1h','A1h','Find the constant that forces no/infinite solutions','A','A1','35','CORE',NULL,'90',''),
('subskill-a1i','A1i','Solve a formula for a variable of interest','A','A1','36','CORE',NULL,'90',''),
('subskill-a1r','A1R','Interleaved review','A','A1','37','CORE',NULL,'90',''),
('subskill-a2a','A2a','Slope from two points','A','A2','38','CORE',NULL,'90',''),
('subskill-a2b','A2b','Slope-intercept: read m and b','A','A2','39','CORE',NULL,'90',''),
('subskill-a2c','A2c','Standard form ax + by = c: rearranging and intercepts','A','A2','40','CORE',NULL,'90',''),
('subskill-a2d','A2d','Point-slope form','A','A2','41','CORE',NULL,'90',''),
('subskill-a2e','A2e','Equation from two points','A','A2','42','CORE',NULL,'90',''),
('subskill-a2f','A2f','Equation from a table of values','A','A2','43','CORE',NULL,'90',''),
('subskill-a2g','A2g','x- and y-intercepts','A','A2','44','CORE',NULL,'90',''),
('subskill-a2h','A2h','Parallel and perpendicular','A','A2','45','CORE',NULL,'90',''),
('subskill-a2i','A2i','Interpret slope in context, with units','A','A2','46','CORE',NULL,'90',''),
('subskill-a2j','A2j','Interpret intercepts in context','A','A2','47','CORE',NULL,'90',''),
('subskill-a2r','A2R','Interleaved review','A','A2','48','CORE',NULL,'90',''),
('subskill-a3a','A3a','Function notation: evaluate f(x)','A','A3','49','CORE',NULL,'90',''),
('subskill-a3b','A3b','Solve f(x) = k','A','A3','50','CORE',NULL,'90',''),
('subskill-a3c','A3c','Build a linear model from a scenario','A','A3','51','CORE',NULL,'90',''),
('subskill-a3d','A3d','Interpret rate of change in context','A','A3','52','CORE',NULL,'90',''),
('subskill-a3e','A3e','Read function values from graphs and tables','A','A3','53','CORE',NULL,'90',''),
('subskill-a3f','A3f','Shifts and transformations','A','A3','54','EXT',NULL,'90',''),
('subskill-a3r','A3R','Interleaved review','A','A3','55','CORE',NULL,'90',''),
('subskill-a4a','A4a','Substitution','A','A4','56','CORE',NULL,'90',''),
('subskill-a4b','A4b','Elimination','A','A4','57','CORE',NULL,'90',''),
('subskill-a4c','A4c','Graphical / intersection','A','A4','58','CORE',NULL,'90',''),
('subskill-a4d','A4d','No solution vs infinite solutions','A','A4','59','CORE',NULL,'90',''),
('subskill-a4e','A4e','Find the coefficient forcing no/infinite solutions','A','A4','60','CORE',NULL,'90',''),
('subskill-a4f','A4f','System word problems: cost & quantity','A','A4','61','CORE',NULL,'90',''),
('subskill-a4g','A4g','System word problems: mixture & rate','A','A4','62','CORE',NULL,'90',''),
('subskill-a4r','A4R','Interleaved review','A','A4','63','CORE',NULL,'90',''),
('subskill-a5a','A5a','One variable, including flipping the sign','A','A5','64','CORE',NULL,'90',''),
('subskill-a5b','A5b','Compound inequalities','A','A5','65','EXT',NULL,'90',''),
('subskill-a5c','A5c','Graphing an inequality in two variables','A','A5','66','CORE',NULL,'90',''),
('subskill-a5d','A5d','Systems of inequalities: shaded region','A','A5','67','CORE',NULL,'90',''),
('subskill-a5e','A5e','Is this point a solution?','A','A5','68','CORE',NULL,'90',''),
('subskill-a5f','A5f','Constraint word problems ("at most," "at least")','A','A5','69','CORE',NULL,'90',''),
('subskill-a5r','A5R','Interleaved review','A','A5','70','CORE',NULL,'90',''),
('subskill-m1a','M1a','Exponent rules including fractional exponents','M','M1','71','CORE',NULL,'90',''),
('subskill-m1b','M1b','Radicals ↔ rational exponents','M','M1','72','CORE',NULL,'90',''),
('subskill-m1c','M1c','Polynomial multiplication','M','M1','73','CORE',NULL,'90',''),
('subskill-m1d','M1d','Factoring out the GCF','M','M1','74','CORE',NULL,'90',''),
('subskill-m1e','M1e','Factoring trinomials, a = 1','M','M1','75','CORE',NULL,'90',''),
('subskill-m1f','M1f','Factoring trinomials, a ≠ 1','M','M1','76','CORE',NULL,'90',''),
('subskill-m1g','M1g','Difference of squares','M','M1','77','CORE',NULL,'90',''),
('subskill-m1h','M1h','Perfect square trinomials','M','M1','78','EXT',NULL,'90',''),
('subskill-m1i','M1i','Rational expressions: simplify, multiply, divide','M','M1','79','CORE',NULL,'90',''),
('subskill-m1j','M1j','Rational expressions: add & subtract','M','M1','80','EXT',NULL,'90',''),
('subskill-m1k','M1k','Polynomial division and remainders','M','M1','81','EXT',NULL,'90',''),
('subskill-m1r','M1R','Interleaved review','M','M1','82','CORE',NULL,'90',''),
('subskill-m2a','M2a','Quadratics by factoring','M','M2','83','CORE',NULL,'90',''),
('subskill-m2b','M2b','Zero product property and roots','M','M2','84','CORE',NULL,'90',''),
('subskill-m2c','M2c','Quadratic formula','M','M2','85','CORE',NULL,'90',''),
('subskill-m2d','M2d','Discriminant: how many solutions','M','M2','86','CORE',NULL,'90',''),
('subskill-m2e','M2e','Completing the square','M','M2','87','EXT',NULL,'90',''),
('subskill-m2f','M2f','Radical equations & extraneous solutions','M','M2','88','CORE',NULL,'90',''),
('subskill-m2g','M2g','Rational equations','M','M2','89','EXT',NULL,'90',''),
('subskill-m2h','M2h','Absolute value equations','M','M2','90','CORE',NULL,'90',''),
('subskill-m2i','M2i','Exponential equations with a common base','M','M2','91','CORE',NULL,'90',''),
('subskill-m2j','M2j','Linear–quadratic systems','M','M2','92','CORE',NULL,'90',''),
('subskill-m2r','M2R','Interleaved review','M','M2','93','CORE',NULL,'90',''),
('subskill-m3a','M3a','Parabolas: vertex form','M','M3','94','CORE',NULL,'90',''),
('subskill-m3b','M3b','Parabolas: standard form, axis of symmetry','M','M3','95','CORE',NULL,'90',''),
('subskill-m3c','M3c','Parabolas: factored form and x-intercepts','M','M3','96','CORE',NULL,'90',''),
('subskill-m3d','M3d','Choosing the right form for what''s asked','M','M3','97','CORE',NULL,'90',''),
('subskill-m3e','M3e','Exponential growth vs decay','M','M3','98','CORE',NULL,'90',''),
('subskill-m3f','M3f','Interpreting exponential parameters in context','M','M3','99','CORE',NULL,'90',''),
('subskill-m3g','M3g','Compound growth with periods (quarterly, monthly)','M','M3','100','CORE',NULL,'90',''),
('subskill-m3h','M3h','Transformations: f(x)+k, f(x+k), af(x), −f(x)','M','M3','101','CORE',NULL,'90',''),
('subskill-m3i','M3i','Graph reading for nonlinear functions','M','M3','102','CORE',NULL,'90',''),
('subskill-m3j','M3j','Where a function is undefined','M','M3','103','EXT',NULL,'90',''),
('subskill-m3k','M3k','Polynomial zeros and end behavior','M','M3','104','EXT',NULL,'90',''),
('subskill-m3l','M3l','Composite functions f(g(x))','M','M3','105','EXT',NULL,'90',''),
('subskill-m3r','M3R','Interleaved review','M','M3','106','CORE',NULL,'90',''),
('subskill-d1a','D1a','Proportions','D','D1','107','CORE',NULL,'90',''),
('subskill-d1b','D1b','Unit rate','D','D1','108','CORE',NULL,'90',''),
('subskill-d1c','D1c','Unit conversion, single and multi-step','D','D1','109','CORE',NULL,'90',''),
('subskill-d1d','D1d','Density and other derived units','D','D1','110','CORE',NULL,'90',''),
('subskill-d1e','D1e','Average rate of change from a graph','D','D1','111','CORE',NULL,'90',''),
('subskill-d1f','D1f','Scale drawings, maps, similar-figure ratios','D','D1','112','EXT',NULL,'90',''),
('subskill-d1r','D1R','Interleaved review','D','D1','113','CORE',NULL,'90',''),
('subskill-d2a','D2a','Percent of a number','D','D2','114','CORE',NULL,'90',''),
('subskill-d2b','D2b','Increase and decrease','D','D2','115','CORE',NULL,'90',''),
('subskill-d2c','D2c','Reverse percent (find the original)','D','D2','116','CORE',NULL,'90',''),
('subskill-d2d','D2d','Successive percent changes','D','D2','117','EXT',NULL,'90',''),
('subskill-d2e','D2e','In context: discount, tax, tip, commission','D','D2','118','CORE',NULL,'90',''),
('subskill-d2f','D2f','Percent from a table or graph','D','D2','119','CORE',NULL,'90',''),
('subskill-d2r','D2R','Interleaved review','D','D2','120','CORE',NULL,'90',''),
('subskill-d3a','D3a','Mean, median, mode','D','D3','121','CORE',NULL,'90',''),
('subskill-d3b','D3b','Mean and median from a frequency table or dot plot','D','D3','122','CORE',NULL,'90',''),
('subskill-d3c','D3c','Range and standard deviation — compare, never compute','D','D3','123','CORE',NULL,'90',''),
('subskill-d3d','D3d','Effect of adding or changing a value','D','D3','124','CORE',NULL,'90',''),
('subskill-d3e','D3e','Histograms, dot plots, and box plots','D','D3','125','CORE',NULL,'90',''),
('subskill-d3f','D3f','Comparing two distributions','D','D3','126','CORE',NULL,'90',''),
('subskill-d3g','D3g','Outliers and skew: which measure to trust','D','D3','127','EXT',NULL,'90',''),
('subskill-d3r','D3R','Interleaved review','D','D3','128','CORE',NULL,'90',''),
('subskill-d4a','D4a','Reading a scatterplot','D','D4','129','CORE',NULL,'90',''),
('subskill-d4b','D4b','Line of best fit: predicting','D','D4','130','CORE',NULL,'90',''),
('subskill-d4c','D4c','Interpreting slope & intercept of the fit line','D','D4','131','CORE',NULL,'90',''),
('subskill-d4d','D4d','Choosing the model: linear vs exponential','D','D4','132','CORE',NULL,'90',''),
('subskill-d4e','D4e','Residuals: actual vs predicted','D','D4','133','EXT',NULL,'90',''),
('subskill-d4r','D4R','Interleaved review','D','D4','134','CORE',NULL,'90',''),
('subskill-d5a','D5a','Probability from counts','D','D5','135','CORE',NULL,'90',''),
('subskill-d5b','D5b','Reading a two-way table','D','D5','136','CORE',NULL,'90',''),
('subskill-d5c','D5c','Probability from a two-way table','D','D5','137','CORE',NULL,'90',''),
('subskill-d5d','D5d','Conditional probability ("given that…")','D','D5','138','CORE',NULL,'90',''),
('subskill-d5e','D5e','Complements and "not"','D','D5','139','EXT',NULL,'90',''),
('subskill-d5r','D5R','Interleaved review','D','D5','140','CORE',NULL,'90',''),
('subskill-d6a','D6a','Plausible population values from a sample + given margin of error','D','D6','141','CORE',NULL,'90',''),
('subskill-d6b','D6b','Interpreting margin of error in a sentence','D','D6','142','CORE',NULL,'90',''),
('subskill-d6c','D6c','How sample size changes margin of error','D','D6','143','EXT',NULL,'90',''),
('subskill-d7a','D7a','Random sampling → who you can generalize to','D','D7','144','CORE',NULL,'90',''),
('subskill-d7b','D7b','Random assignment → when you can say "caused"','D','D7','145','CORE',NULL,'90',''),
('subskill-d7c','D7c','Which conclusion is supported?','D','D7','146','CORE',NULL,'90',''),
('subskill-d7d','D7d','Spotting bias in study design','D','D7','147','EXT',NULL,'90',''),
('subskill-d-r','D-R','Combined review for D6 + D7','D','D7','148','CORE',NULL,'90',''),
('subskill-g1a','G1a','Vertical angles & linear pairs','G','G1','149','CORE',NULL,'90',''),
('subskill-g1b','G1b','Parallel lines & transversals','G','G1','150','CORE',NULL,'90',''),
('subskill-g1c','G1c','Triangle angle sum & exterior angle','G','G1','151','CORE',NULL,'90',''),
('subskill-g1d','G1d','Isosceles & equilateral','G','G1','152','CORE',NULL,'90',''),
('subskill-g1e','G1e','Similar triangles: setting up the ratio','G','G1','153','CORE',NULL,'90',''),
('subskill-g1f','G1f','Congruence','G','G1','154','CORE',NULL,'90',''),
('subskill-g1g','G1g','Polygon interior & exterior angles','G','G1','155','EXT',NULL,'90',''),
('subskill-g1r','G1R','Interleaved review','G','G1','156','CORE',NULL,'90',''),
('subskill-g2a','G2a','Pythagorean theorem','G','G2','157','CORE',NULL,'90',''),
('subskill-g2b','G2b','Pythagorean triples','G','G2','158','EXT',NULL,'90',''),
('subskill-g2c','G2c','45-45-90 and 30-60-90 (both on the reference sheet)','G','G2','159','CORE',NULL,'90',''),
('subskill-g2d','G2d','SOH-CAH-TOA: find a side','G','G2','160','CORE',NULL,'90',''),
('subskill-g2e','G2e','SOH-CAH-TOA: find an angle','G','G2','161','EXT',NULL,'90',''),
('subskill-g2f','G2f','sin x = cos(90 − x)','G','G2','162','EXT',NULL,'90',''),
('subskill-g2g','G2g','Trig in diagrams and word problems','G','G2','163','EXT',NULL,'90',''),
('subskill-g2r','G2R','Interleaved review','G','G2','164','CORE',NULL,'90',''),
('subskill-g3a','G3a','Area: triangle, rectangle, parallelogram, trapezoid','G','G3','165','CORE',NULL,'90',''),
('subskill-g3b','G3b','Circumference and area of a circle','G','G3','166','CORE',NULL,'90',''),
('subskill-g3c','G3c','Volume of prisms and cylinders','G','G3','167','CORE',NULL,'90',''),
('subskill-g3d','G3d','Cones, pyramids, spheres (reference sheet)','G','G3','168','CORE',NULL,'90',''),
('subskill-g3e','G3e','Surface area','G','G3','169','EXT',NULL,'90',''),
('subskill-g3f','G3f','Composite and shaded regions','G','G3','170','EXT',NULL,'90',''),
('subskill-g3g','G3g','Scaling: effect on area and volume','G','G3','171','EXT',NULL,'90',''),
('subskill-g3r','G3R','Interleaved review','G','G3','172','CORE',NULL,'90',''),
('subskill-g4f','G4f','Equation of a circle','G','G4','173','CORE',NULL,'90',''),
('subskill-g4a','G4a','Central angles and arc measure','G','G4','174','EXT',NULL,'90',''),
('subskill-g4b','G4b','Arc length','G','G4','175','EXT',NULL,'90',''),
('subskill-g4c','G4c','Sector area','G','G4','176','EXT',NULL,'90',''),
('subskill-g4d','G4d','Inscribed angles','G','G4','177','EXT',NULL,'90',''),
('subskill-g4e','G4e','Radians ↔ degrees','G','G4','178','EXT',NULL,'90',''),
('subskill-g4g','G4g','Completing the square for center & radius','G','G4','179','EXT',NULL,'90',''),
('subskill-g4h','G4h','Tangent lines and the perpendicular radius','G','G4','180','EXT',NULL,'90',''),
('subskill-g4r','G4R','Interleaved review','G','G4','181','EXT',NULL,'90','');

INSERT INTO mastery_worksheets (id,level_id,worksheet_index,worksheet_type) VALUES
('ws-f1a-01','subskill-f1a','1','PRACTICE'),
('ws-f1a-02','subskill-f1a','2','PRACTICE'),
('ws-f1a-03','subskill-f1a','3','PRACTICE'),
('ws-f1a-04','subskill-f1a','4','MIXED'),
('ws-f1a-05','subskill-f1a','5','MASTERY_CHECK'),
('ws-f1b-01','subskill-f1b','1','PRACTICE'),
('ws-f1b-02','subskill-f1b','2','PRACTICE'),
('ws-f1b-03','subskill-f1b','3','PRACTICE'),
('ws-f1b-04','subskill-f1b','4','MIXED'),
('ws-f1b-05','subskill-f1b','5','MASTERY_CHECK'),
('ws-f1c-01','subskill-f1c','1','PRACTICE'),
('ws-f1c-02','subskill-f1c','2','PRACTICE'),
('ws-f1c-03','subskill-f1c','3','PRACTICE'),
('ws-f1c-04','subskill-f1c','4','MIXED'),
('ws-f1c-05','subskill-f1c','5','MASTERY_CHECK'),
('ws-f1d-01','subskill-f1d','1','PRACTICE'),
('ws-f1d-02','subskill-f1d','2','PRACTICE'),
('ws-f1d-03','subskill-f1d','3','PRACTICE'),
('ws-f1d-04','subskill-f1d','4','MIXED'),
('ws-f1d-05','subskill-f1d','5','MASTERY_CHECK'),
('ws-f1e-01','subskill-f1e','1','PRACTICE'),
('ws-f1e-02','subskill-f1e','2','PRACTICE'),
('ws-f1e-03','subskill-f1e','3','PRACTICE'),
('ws-f1e-04','subskill-f1e','4','MIXED'),
('ws-f1e-05','subskill-f1e','5','MASTERY_CHECK'),
('ws-f1f-01','subskill-f1f','1','PRACTICE'),
('ws-f1f-02','subskill-f1f','2','PRACTICE'),
('ws-f1f-03','subskill-f1f','3','PRACTICE'),
('ws-f1f-04','subskill-f1f','4','MIXED'),
('ws-f1f-05','subskill-f1f','5','MASTERY_CHECK'),
('ws-f1r-01','subskill-f1r','1','PRACTICE'),
('ws-f1r-02','subskill-f1r','2','PRACTICE'),
('ws-f1r-03','subskill-f1r','3','PRACTICE'),
('ws-f1r-04','subskill-f1r','4','MIXED'),
('ws-f1r-05','subskill-f1r','5','MASTERY_CHECK'),
('ws-f2a-01','subskill-f2a','1','PRACTICE'),
('ws-f2a-02','subskill-f2a','2','PRACTICE'),
('ws-f2a-03','subskill-f2a','3','PRACTICE'),
('ws-f2a-04','subskill-f2a','4','MIXED'),
('ws-f2a-05','subskill-f2a','5','MASTERY_CHECK'),
('ws-f2b-01','subskill-f2b','1','PRACTICE'),
('ws-f2b-02','subskill-f2b','2','PRACTICE'),
('ws-f2b-03','subskill-f2b','3','PRACTICE'),
('ws-f2b-04','subskill-f2b','4','MIXED'),
('ws-f2b-05','subskill-f2b','5','MASTERY_CHECK'),
('ws-f2c-01','subskill-f2c','1','PRACTICE'),
('ws-f2c-02','subskill-f2c','2','PRACTICE'),
('ws-f2c-03','subskill-f2c','3','PRACTICE'),
('ws-f2c-04','subskill-f2c','4','MIXED'),
('ws-f2c-05','subskill-f2c','5','MASTERY_CHECK'),
('ws-f2d-01','subskill-f2d','1','PRACTICE'),
('ws-f2d-02','subskill-f2d','2','PRACTICE'),
('ws-f2d-03','subskill-f2d','3','PRACTICE'),
('ws-f2d-04','subskill-f2d','4','MIXED'),
('ws-f2d-05','subskill-f2d','5','MASTERY_CHECK'),
('ws-f2e-01','subskill-f2e','1','PRACTICE'),
('ws-f2e-02','subskill-f2e','2','PRACTICE'),
('ws-f2e-03','subskill-f2e','3','PRACTICE'),
('ws-f2e-04','subskill-f2e','4','MIXED'),
('ws-f2e-05','subskill-f2e','5','MASTERY_CHECK'),
('ws-f2f-01','subskill-f2f','1','PRACTICE'),
('ws-f2f-02','subskill-f2f','2','PRACTICE'),
('ws-f2f-03','subskill-f2f','3','PRACTICE'),
('ws-f2f-04','subskill-f2f','4','MIXED'),
('ws-f2f-05','subskill-f2f','5','MASTERY_CHECK'),
('ws-f2r-01','subskill-f2r','1','PRACTICE'),
('ws-f2r-02','subskill-f2r','2','PRACTICE'),
('ws-f2r-03','subskill-f2r','3','PRACTICE'),
('ws-f2r-04','subskill-f2r','4','MIXED'),
('ws-f2r-05','subskill-f2r','5','MASTERY_CHECK'),
('ws-f3a-01','subskill-f3a','1','PRACTICE'),
('ws-f3a-02','subskill-f3a','2','PRACTICE'),
('ws-f3a-03','subskill-f3a','3','PRACTICE'),
('ws-f3a-04','subskill-f3a','4','MIXED'),
('ws-f3a-05','subskill-f3a','5','MASTERY_CHECK'),
('ws-f3b-01','subskill-f3b','1','PRACTICE'),
('ws-f3b-02','subskill-f3b','2','PRACTICE'),
('ws-f3b-03','subskill-f3b','3','PRACTICE'),
('ws-f3b-04','subskill-f3b','4','MIXED'),
('ws-f3b-05','subskill-f3b','5','MASTERY_CHECK'),
('ws-f3c-01','subskill-f3c','1','PRACTICE'),
('ws-f3c-02','subskill-f3c','2','PRACTICE'),
('ws-f3c-03','subskill-f3c','3','PRACTICE'),
('ws-f3c-04','subskill-f3c','4','MIXED'),
('ws-f3c-05','subskill-f3c','5','MASTERY_CHECK'),
('ws-f3d-01','subskill-f3d','1','PRACTICE'),
('ws-f3d-02','subskill-f3d','2','PRACTICE'),
('ws-f3d-03','subskill-f3d','3','PRACTICE'),
('ws-f3d-04','subskill-f3d','4','MIXED'),
('ws-f3d-05','subskill-f3d','5','MASTERY_CHECK'),
('ws-f3e-01','subskill-f3e','1','PRACTICE'),
('ws-f3e-02','subskill-f3e','2','PRACTICE'),
('ws-f3e-03','subskill-f3e','3','PRACTICE'),
('ws-f3e-04','subskill-f3e','4','MIXED'),
('ws-f3e-05','subskill-f3e','5','MASTERY_CHECK'),
('ws-f3f-01','subskill-f3f','1','PRACTICE'),
('ws-f3f-02','subskill-f3f','2','PRACTICE'),
('ws-f3f-03','subskill-f3f','3','PRACTICE'),
('ws-f3f-04','subskill-f3f','4','MIXED'),
('ws-f3f-05','subskill-f3f','5','MASTERY_CHECK'),
('ws-f3r-01','subskill-f3r','1','PRACTICE'),
('ws-f3r-02','subskill-f3r','2','PRACTICE'),
('ws-f3r-03','subskill-f3r','3','PRACTICE'),
('ws-f3r-04','subskill-f3r','4','MIXED'),
('ws-f3r-05','subskill-f3r','5','MASTERY_CHECK'),
('ws-f4a-01','subskill-f4a','1','PRACTICE'),
('ws-f4a-02','subskill-f4a','2','PRACTICE'),
('ws-f4a-03','subskill-f4a','3','PRACTICE'),
('ws-f4a-04','subskill-f4a','4','MIXED'),
('ws-f4a-05','subskill-f4a','5','MASTERY_CHECK'),
('ws-f4b-01','subskill-f4b','1','PRACTICE'),
('ws-f4b-02','subskill-f4b','2','PRACTICE'),
('ws-f4b-03','subskill-f4b','3','PRACTICE'),
('ws-f4b-04','subskill-f4b','4','MIXED'),
('ws-f4b-05','subskill-f4b','5','MASTERY_CHECK'),
('ws-f4c-01','subskill-f4c','1','PRACTICE'),
('ws-f4c-02','subskill-f4c','2','PRACTICE'),
('ws-f4c-03','subskill-f4c','3','PRACTICE'),
('ws-f4c-04','subskill-f4c','4','MIXED'),
('ws-f4c-05','subskill-f4c','5','MASTERY_CHECK'),
('ws-f4d-01','subskill-f4d','1','PRACTICE'),
('ws-f4d-02','subskill-f4d','2','PRACTICE'),
('ws-f4d-03','subskill-f4d','3','PRACTICE'),
('ws-f4d-04','subskill-f4d','4','MIXED'),
('ws-f4d-05','subskill-f4d','5','MASTERY_CHECK'),
('ws-f4e-01','subskill-f4e','1','PRACTICE'),
('ws-f4e-02','subskill-f4e','2','PRACTICE'),
('ws-f4e-03','subskill-f4e','3','PRACTICE'),
('ws-f4e-04','subskill-f4e','4','MIXED'),
('ws-f4e-05','subskill-f4e','5','MASTERY_CHECK'),
('ws-f4r-01','subskill-f4r','1','PRACTICE'),
('ws-f4r-02','subskill-f4r','2','PRACTICE'),
('ws-f4r-03','subskill-f4r','3','PRACTICE'),
('ws-f4r-04','subskill-f4r','4','MIXED'),
('ws-f4r-05','subskill-f4r','5','MASTERY_CHECK'),
('ws-a1a-01','subskill-a1a','1','PRACTICE'),
('ws-a1a-02','subskill-a1a','2','PRACTICE'),
('ws-a1a-03','subskill-a1a','3','PRACTICE'),
('ws-a1a-04','subskill-a1a','4','MIXED'),
('ws-a1a-05','subskill-a1a','5','MASTERY_CHECK'),
('ws-a1b-01','subskill-a1b','1','PRACTICE'),
('ws-a1b-02','subskill-a1b','2','PRACTICE'),
('ws-a1b-03','subskill-a1b','3','PRACTICE'),
('ws-a1b-04','subskill-a1b','4','MIXED'),
('ws-a1b-05','subskill-a1b','5','MASTERY_CHECK'),
('ws-a1c-01','subskill-a1c','1','PRACTICE'),
('ws-a1c-02','subskill-a1c','2','PRACTICE'),
('ws-a1c-03','subskill-a1c','3','PRACTICE'),
('ws-a1c-04','subskill-a1c','4','MIXED'),
('ws-a1c-05','subskill-a1c','5','MASTERY_CHECK'),
('ws-a1d-01','subskill-a1d','1','PRACTICE'),
('ws-a1d-02','subskill-a1d','2','PRACTICE'),
('ws-a1d-03','subskill-a1d','3','PRACTICE'),
('ws-a1d-04','subskill-a1d','4','MIXED'),
('ws-a1d-05','subskill-a1d','5','MASTERY_CHECK'),
('ws-a1e-01','subskill-a1e','1','PRACTICE'),
('ws-a1e-02','subskill-a1e','2','PRACTICE'),
('ws-a1e-03','subskill-a1e','3','PRACTICE'),
('ws-a1e-04','subskill-a1e','4','MIXED'),
('ws-a1e-05','subskill-a1e','5','MASTERY_CHECK'),
('ws-a1f-01','subskill-a1f','1','PRACTICE'),
('ws-a1f-02','subskill-a1f','2','PRACTICE'),
('ws-a1f-03','subskill-a1f','3','PRACTICE'),
('ws-a1f-04','subskill-a1f','4','MIXED'),
('ws-a1f-05','subskill-a1f','5','MASTERY_CHECK'),
('ws-a1g-01','subskill-a1g','1','PRACTICE'),
('ws-a1g-02','subskill-a1g','2','PRACTICE'),
('ws-a1g-03','subskill-a1g','3','PRACTICE'),
('ws-a1g-04','subskill-a1g','4','MIXED'),
('ws-a1g-05','subskill-a1g','5','MASTERY_CHECK'),
('ws-a1h-01','subskill-a1h','1','PRACTICE'),
('ws-a1h-02','subskill-a1h','2','PRACTICE'),
('ws-a1h-03','subskill-a1h','3','PRACTICE'),
('ws-a1h-04','subskill-a1h','4','MIXED'),
('ws-a1h-05','subskill-a1h','5','MASTERY_CHECK'),
('ws-a1i-01','subskill-a1i','1','PRACTICE'),
('ws-a1i-02','subskill-a1i','2','PRACTICE'),
('ws-a1i-03','subskill-a1i','3','PRACTICE'),
('ws-a1i-04','subskill-a1i','4','MIXED'),
('ws-a1i-05','subskill-a1i','5','MASTERY_CHECK'),
('ws-a1r-01','subskill-a1r','1','PRACTICE'),
('ws-a1r-02','subskill-a1r','2','PRACTICE'),
('ws-a1r-03','subskill-a1r','3','PRACTICE'),
('ws-a1r-04','subskill-a1r','4','MIXED'),
('ws-a1r-05','subskill-a1r','5','MASTERY_CHECK'),
('ws-a2a-01','subskill-a2a','1','PRACTICE'),
('ws-a2a-02','subskill-a2a','2','PRACTICE'),
('ws-a2a-03','subskill-a2a','3','PRACTICE'),
('ws-a2a-04','subskill-a2a','4','MIXED'),
('ws-a2a-05','subskill-a2a','5','MASTERY_CHECK'),
('ws-a2b-01','subskill-a2b','1','PRACTICE'),
('ws-a2b-02','subskill-a2b','2','PRACTICE'),
('ws-a2b-03','subskill-a2b','3','PRACTICE'),
('ws-a2b-04','subskill-a2b','4','MIXED'),
('ws-a2b-05','subskill-a2b','5','MASTERY_CHECK'),
('ws-a2c-01','subskill-a2c','1','PRACTICE'),
('ws-a2c-02','subskill-a2c','2','PRACTICE'),
('ws-a2c-03','subskill-a2c','3','PRACTICE'),
('ws-a2c-04','subskill-a2c','4','MIXED'),
('ws-a2c-05','subskill-a2c','5','MASTERY_CHECK'),
('ws-a2d-01','subskill-a2d','1','PRACTICE'),
('ws-a2d-02','subskill-a2d','2','PRACTICE'),
('ws-a2d-03','subskill-a2d','3','PRACTICE'),
('ws-a2d-04','subskill-a2d','4','MIXED'),
('ws-a2d-05','subskill-a2d','5','MASTERY_CHECK'),
('ws-a2e-01','subskill-a2e','1','PRACTICE'),
('ws-a2e-02','subskill-a2e','2','PRACTICE'),
('ws-a2e-03','subskill-a2e','3','PRACTICE'),
('ws-a2e-04','subskill-a2e','4','MIXED'),
('ws-a2e-05','subskill-a2e','5','MASTERY_CHECK'),
('ws-a2f-01','subskill-a2f','1','PRACTICE'),
('ws-a2f-02','subskill-a2f','2','PRACTICE'),
('ws-a2f-03','subskill-a2f','3','PRACTICE'),
('ws-a2f-04','subskill-a2f','4','MIXED'),
('ws-a2f-05','subskill-a2f','5','MASTERY_CHECK'),
('ws-a2g-01','subskill-a2g','1','PRACTICE'),
('ws-a2g-02','subskill-a2g','2','PRACTICE'),
('ws-a2g-03','subskill-a2g','3','PRACTICE'),
('ws-a2g-04','subskill-a2g','4','MIXED'),
('ws-a2g-05','subskill-a2g','5','MASTERY_CHECK'),
('ws-a2h-01','subskill-a2h','1','PRACTICE'),
('ws-a2h-02','subskill-a2h','2','PRACTICE'),
('ws-a2h-03','subskill-a2h','3','PRACTICE'),
('ws-a2h-04','subskill-a2h','4','MIXED'),
('ws-a2h-05','subskill-a2h','5','MASTERY_CHECK'),
('ws-a2i-01','subskill-a2i','1','PRACTICE'),
('ws-a2i-02','subskill-a2i','2','PRACTICE'),
('ws-a2i-03','subskill-a2i','3','PRACTICE'),
('ws-a2i-04','subskill-a2i','4','MIXED'),
('ws-a2i-05','subskill-a2i','5','MASTERY_CHECK'),
('ws-a2j-01','subskill-a2j','1','PRACTICE'),
('ws-a2j-02','subskill-a2j','2','PRACTICE'),
('ws-a2j-03','subskill-a2j','3','PRACTICE'),
('ws-a2j-04','subskill-a2j','4','MIXED'),
('ws-a2j-05','subskill-a2j','5','MASTERY_CHECK'),
('ws-a2r-01','subskill-a2r','1','PRACTICE'),
('ws-a2r-02','subskill-a2r','2','PRACTICE'),
('ws-a2r-03','subskill-a2r','3','PRACTICE'),
('ws-a2r-04','subskill-a2r','4','MIXED'),
('ws-a2r-05','subskill-a2r','5','MASTERY_CHECK'),
('ws-a3a-01','subskill-a3a','1','PRACTICE'),
('ws-a3a-02','subskill-a3a','2','PRACTICE'),
('ws-a3a-03','subskill-a3a','3','PRACTICE'),
('ws-a3a-04','subskill-a3a','4','MIXED'),
('ws-a3a-05','subskill-a3a','5','MASTERY_CHECK'),
('ws-a3b-01','subskill-a3b','1','PRACTICE'),
('ws-a3b-02','subskill-a3b','2','PRACTICE'),
('ws-a3b-03','subskill-a3b','3','PRACTICE'),
('ws-a3b-04','subskill-a3b','4','MIXED'),
('ws-a3b-05','subskill-a3b','5','MASTERY_CHECK'),
('ws-a3c-01','subskill-a3c','1','PRACTICE'),
('ws-a3c-02','subskill-a3c','2','PRACTICE'),
('ws-a3c-03','subskill-a3c','3','PRACTICE'),
('ws-a3c-04','subskill-a3c','4','MIXED'),
('ws-a3c-05','subskill-a3c','5','MASTERY_CHECK'),
('ws-a3d-01','subskill-a3d','1','PRACTICE'),
('ws-a3d-02','subskill-a3d','2','PRACTICE'),
('ws-a3d-03','subskill-a3d','3','PRACTICE'),
('ws-a3d-04','subskill-a3d','4','MIXED'),
('ws-a3d-05','subskill-a3d','5','MASTERY_CHECK'),
('ws-a3e-01','subskill-a3e','1','PRACTICE'),
('ws-a3e-02','subskill-a3e','2','PRACTICE'),
('ws-a3e-03','subskill-a3e','3','PRACTICE'),
('ws-a3e-04','subskill-a3e','4','MIXED'),
('ws-a3e-05','subskill-a3e','5','MASTERY_CHECK'),
('ws-a3f-01','subskill-a3f','1','PRACTICE'),
('ws-a3f-02','subskill-a3f','2','PRACTICE'),
('ws-a3f-03','subskill-a3f','3','PRACTICE'),
('ws-a3f-04','subskill-a3f','4','MIXED'),
('ws-a3f-05','subskill-a3f','5','MASTERY_CHECK'),
('ws-a3r-01','subskill-a3r','1','PRACTICE'),
('ws-a3r-02','subskill-a3r','2','PRACTICE'),
('ws-a3r-03','subskill-a3r','3','PRACTICE'),
('ws-a3r-04','subskill-a3r','4','MIXED'),
('ws-a3r-05','subskill-a3r','5','MASTERY_CHECK'),
('ws-a4a-01','subskill-a4a','1','PRACTICE'),
('ws-a4a-02','subskill-a4a','2','PRACTICE'),
('ws-a4a-03','subskill-a4a','3','PRACTICE'),
('ws-a4a-04','subskill-a4a','4','MIXED'),
('ws-a4a-05','subskill-a4a','5','MASTERY_CHECK'),
('ws-a4b-01','subskill-a4b','1','PRACTICE'),
('ws-a4b-02','subskill-a4b','2','PRACTICE'),
('ws-a4b-03','subskill-a4b','3','PRACTICE'),
('ws-a4b-04','subskill-a4b','4','MIXED'),
('ws-a4b-05','subskill-a4b','5','MASTERY_CHECK'),
('ws-a4c-01','subskill-a4c','1','PRACTICE'),
('ws-a4c-02','subskill-a4c','2','PRACTICE'),
('ws-a4c-03','subskill-a4c','3','PRACTICE'),
('ws-a4c-04','subskill-a4c','4','MIXED'),
('ws-a4c-05','subskill-a4c','5','MASTERY_CHECK'),
('ws-a4d-01','subskill-a4d','1','PRACTICE'),
('ws-a4d-02','subskill-a4d','2','PRACTICE'),
('ws-a4d-03','subskill-a4d','3','PRACTICE'),
('ws-a4d-04','subskill-a4d','4','MIXED'),
('ws-a4d-05','subskill-a4d','5','MASTERY_CHECK'),
('ws-a4e-01','subskill-a4e','1','PRACTICE'),
('ws-a4e-02','subskill-a4e','2','PRACTICE'),
('ws-a4e-03','subskill-a4e','3','PRACTICE'),
('ws-a4e-04','subskill-a4e','4','MIXED'),
('ws-a4e-05','subskill-a4e','5','MASTERY_CHECK'),
('ws-a4f-01','subskill-a4f','1','PRACTICE'),
('ws-a4f-02','subskill-a4f','2','PRACTICE'),
('ws-a4f-03','subskill-a4f','3','PRACTICE'),
('ws-a4f-04','subskill-a4f','4','MIXED'),
('ws-a4f-05','subskill-a4f','5','MASTERY_CHECK'),
('ws-a4g-01','subskill-a4g','1','PRACTICE'),
('ws-a4g-02','subskill-a4g','2','PRACTICE'),
('ws-a4g-03','subskill-a4g','3','PRACTICE'),
('ws-a4g-04','subskill-a4g','4','MIXED'),
('ws-a4g-05','subskill-a4g','5','MASTERY_CHECK'),
('ws-a4r-01','subskill-a4r','1','PRACTICE'),
('ws-a4r-02','subskill-a4r','2','PRACTICE'),
('ws-a4r-03','subskill-a4r','3','PRACTICE'),
('ws-a4r-04','subskill-a4r','4','MIXED'),
('ws-a4r-05','subskill-a4r','5','MASTERY_CHECK'),
('ws-a5a-01','subskill-a5a','1','PRACTICE'),
('ws-a5a-02','subskill-a5a','2','PRACTICE'),
('ws-a5a-03','subskill-a5a','3','PRACTICE'),
('ws-a5a-04','subskill-a5a','4','MIXED'),
('ws-a5a-05','subskill-a5a','5','MASTERY_CHECK'),
('ws-a5b-01','subskill-a5b','1','PRACTICE'),
('ws-a5b-02','subskill-a5b','2','PRACTICE'),
('ws-a5b-03','subskill-a5b','3','PRACTICE'),
('ws-a5b-04','subskill-a5b','4','MIXED'),
('ws-a5b-05','subskill-a5b','5','MASTERY_CHECK'),
('ws-a5c-01','subskill-a5c','1','PRACTICE'),
('ws-a5c-02','subskill-a5c','2','PRACTICE'),
('ws-a5c-03','subskill-a5c','3','PRACTICE'),
('ws-a5c-04','subskill-a5c','4','MIXED'),
('ws-a5c-05','subskill-a5c','5','MASTERY_CHECK'),
('ws-a5d-01','subskill-a5d','1','PRACTICE'),
('ws-a5d-02','subskill-a5d','2','PRACTICE'),
('ws-a5d-03','subskill-a5d','3','PRACTICE'),
('ws-a5d-04','subskill-a5d','4','MIXED'),
('ws-a5d-05','subskill-a5d','5','MASTERY_CHECK'),
('ws-a5e-01','subskill-a5e','1','PRACTICE'),
('ws-a5e-02','subskill-a5e','2','PRACTICE'),
('ws-a5e-03','subskill-a5e','3','PRACTICE'),
('ws-a5e-04','subskill-a5e','4','MIXED'),
('ws-a5e-05','subskill-a5e','5','MASTERY_CHECK'),
('ws-a5f-01','subskill-a5f','1','PRACTICE'),
('ws-a5f-02','subskill-a5f','2','PRACTICE'),
('ws-a5f-03','subskill-a5f','3','PRACTICE'),
('ws-a5f-04','subskill-a5f','4','MIXED'),
('ws-a5f-05','subskill-a5f','5','MASTERY_CHECK'),
('ws-a5r-01','subskill-a5r','1','PRACTICE'),
('ws-a5r-02','subskill-a5r','2','PRACTICE'),
('ws-a5r-03','subskill-a5r','3','PRACTICE'),
('ws-a5r-04','subskill-a5r','4','MIXED'),
('ws-a5r-05','subskill-a5r','5','MASTERY_CHECK'),
('ws-m1a-01','subskill-m1a','1','PRACTICE'),
('ws-m1a-02','subskill-m1a','2','PRACTICE'),
('ws-m1a-03','subskill-m1a','3','PRACTICE'),
('ws-m1a-04','subskill-m1a','4','MIXED'),
('ws-m1a-05','subskill-m1a','5','MASTERY_CHECK'),
('ws-m1b-01','subskill-m1b','1','PRACTICE'),
('ws-m1b-02','subskill-m1b','2','PRACTICE'),
('ws-m1b-03','subskill-m1b','3','PRACTICE'),
('ws-m1b-04','subskill-m1b','4','MIXED'),
('ws-m1b-05','subskill-m1b','5','MASTERY_CHECK'),
('ws-m1c-01','subskill-m1c','1','PRACTICE'),
('ws-m1c-02','subskill-m1c','2','PRACTICE'),
('ws-m1c-03','subskill-m1c','3','PRACTICE'),
('ws-m1c-04','subskill-m1c','4','MIXED'),
('ws-m1c-05','subskill-m1c','5','MASTERY_CHECK'),
('ws-m1d-01','subskill-m1d','1','PRACTICE'),
('ws-m1d-02','subskill-m1d','2','PRACTICE'),
('ws-m1d-03','subskill-m1d','3','PRACTICE'),
('ws-m1d-04','subskill-m1d','4','MIXED'),
('ws-m1d-05','subskill-m1d','5','MASTERY_CHECK'),
('ws-m1e-01','subskill-m1e','1','PRACTICE'),
('ws-m1e-02','subskill-m1e','2','PRACTICE'),
('ws-m1e-03','subskill-m1e','3','PRACTICE'),
('ws-m1e-04','subskill-m1e','4','MIXED'),
('ws-m1e-05','subskill-m1e','5','MASTERY_CHECK'),
('ws-m1f-01','subskill-m1f','1','PRACTICE'),
('ws-m1f-02','subskill-m1f','2','PRACTICE'),
('ws-m1f-03','subskill-m1f','3','PRACTICE'),
('ws-m1f-04','subskill-m1f','4','MIXED'),
('ws-m1f-05','subskill-m1f','5','MASTERY_CHECK'),
('ws-m1g-01','subskill-m1g','1','PRACTICE'),
('ws-m1g-02','subskill-m1g','2','PRACTICE'),
('ws-m1g-03','subskill-m1g','3','PRACTICE'),
('ws-m1g-04','subskill-m1g','4','MIXED'),
('ws-m1g-05','subskill-m1g','5','MASTERY_CHECK'),
('ws-m1h-01','subskill-m1h','1','PRACTICE'),
('ws-m1h-02','subskill-m1h','2','PRACTICE'),
('ws-m1h-03','subskill-m1h','3','PRACTICE'),
('ws-m1h-04','subskill-m1h','4','MIXED'),
('ws-m1h-05','subskill-m1h','5','MASTERY_CHECK'),
('ws-m1i-01','subskill-m1i','1','PRACTICE'),
('ws-m1i-02','subskill-m1i','2','PRACTICE'),
('ws-m1i-03','subskill-m1i','3','PRACTICE'),
('ws-m1i-04','subskill-m1i','4','MIXED'),
('ws-m1i-05','subskill-m1i','5','MASTERY_CHECK'),
('ws-m1j-01','subskill-m1j','1','PRACTICE'),
('ws-m1j-02','subskill-m1j','2','PRACTICE'),
('ws-m1j-03','subskill-m1j','3','PRACTICE'),
('ws-m1j-04','subskill-m1j','4','MIXED'),
('ws-m1j-05','subskill-m1j','5','MASTERY_CHECK'),
('ws-m1k-01','subskill-m1k','1','PRACTICE'),
('ws-m1k-02','subskill-m1k','2','PRACTICE'),
('ws-m1k-03','subskill-m1k','3','PRACTICE'),
('ws-m1k-04','subskill-m1k','4','MIXED'),
('ws-m1k-05','subskill-m1k','5','MASTERY_CHECK'),
('ws-m1r-01','subskill-m1r','1','PRACTICE'),
('ws-m1r-02','subskill-m1r','2','PRACTICE'),
('ws-m1r-03','subskill-m1r','3','PRACTICE'),
('ws-m1r-04','subskill-m1r','4','MIXED'),
('ws-m1r-05','subskill-m1r','5','MASTERY_CHECK'),
('ws-m2a-01','subskill-m2a','1','PRACTICE'),
('ws-m2a-02','subskill-m2a','2','PRACTICE'),
('ws-m2a-03','subskill-m2a','3','PRACTICE'),
('ws-m2a-04','subskill-m2a','4','MIXED'),
('ws-m2a-05','subskill-m2a','5','MASTERY_CHECK'),
('ws-m2b-01','subskill-m2b','1','PRACTICE'),
('ws-m2b-02','subskill-m2b','2','PRACTICE'),
('ws-m2b-03','subskill-m2b','3','PRACTICE'),
('ws-m2b-04','subskill-m2b','4','MIXED'),
('ws-m2b-05','subskill-m2b','5','MASTERY_CHECK'),
('ws-m2c-01','subskill-m2c','1','PRACTICE'),
('ws-m2c-02','subskill-m2c','2','PRACTICE'),
('ws-m2c-03','subskill-m2c','3','PRACTICE'),
('ws-m2c-04','subskill-m2c','4','MIXED'),
('ws-m2c-05','subskill-m2c','5','MASTERY_CHECK'),
('ws-m2d-01','subskill-m2d','1','PRACTICE'),
('ws-m2d-02','subskill-m2d','2','PRACTICE'),
('ws-m2d-03','subskill-m2d','3','PRACTICE'),
('ws-m2d-04','subskill-m2d','4','MIXED'),
('ws-m2d-05','subskill-m2d','5','MASTERY_CHECK'),
('ws-m2e-01','subskill-m2e','1','PRACTICE'),
('ws-m2e-02','subskill-m2e','2','PRACTICE'),
('ws-m2e-03','subskill-m2e','3','PRACTICE'),
('ws-m2e-04','subskill-m2e','4','MIXED'),
('ws-m2e-05','subskill-m2e','5','MASTERY_CHECK'),
('ws-m2f-01','subskill-m2f','1','PRACTICE'),
('ws-m2f-02','subskill-m2f','2','PRACTICE'),
('ws-m2f-03','subskill-m2f','3','PRACTICE'),
('ws-m2f-04','subskill-m2f','4','MIXED'),
('ws-m2f-05','subskill-m2f','5','MASTERY_CHECK'),
('ws-m2g-01','subskill-m2g','1','PRACTICE'),
('ws-m2g-02','subskill-m2g','2','PRACTICE'),
('ws-m2g-03','subskill-m2g','3','PRACTICE'),
('ws-m2g-04','subskill-m2g','4','MIXED'),
('ws-m2g-05','subskill-m2g','5','MASTERY_CHECK'),
('ws-m2h-01','subskill-m2h','1','PRACTICE'),
('ws-m2h-02','subskill-m2h','2','PRACTICE'),
('ws-m2h-03','subskill-m2h','3','PRACTICE'),
('ws-m2h-04','subskill-m2h','4','MIXED'),
('ws-m2h-05','subskill-m2h','5','MASTERY_CHECK'),
('ws-m2i-01','subskill-m2i','1','PRACTICE'),
('ws-m2i-02','subskill-m2i','2','PRACTICE'),
('ws-m2i-03','subskill-m2i','3','PRACTICE'),
('ws-m2i-04','subskill-m2i','4','MIXED'),
('ws-m2i-05','subskill-m2i','5','MASTERY_CHECK'),
('ws-m2j-01','subskill-m2j','1','PRACTICE'),
('ws-m2j-02','subskill-m2j','2','PRACTICE'),
('ws-m2j-03','subskill-m2j','3','PRACTICE'),
('ws-m2j-04','subskill-m2j','4','MIXED'),
('ws-m2j-05','subskill-m2j','5','MASTERY_CHECK'),
('ws-m2r-01','subskill-m2r','1','PRACTICE'),
('ws-m2r-02','subskill-m2r','2','PRACTICE'),
('ws-m2r-03','subskill-m2r','3','PRACTICE'),
('ws-m2r-04','subskill-m2r','4','MIXED'),
('ws-m2r-05','subskill-m2r','5','MASTERY_CHECK'),
('ws-m3a-01','subskill-m3a','1','PRACTICE'),
('ws-m3a-02','subskill-m3a','2','PRACTICE'),
('ws-m3a-03','subskill-m3a','3','PRACTICE'),
('ws-m3a-04','subskill-m3a','4','MIXED'),
('ws-m3a-05','subskill-m3a','5','MASTERY_CHECK'),
('ws-m3b-01','subskill-m3b','1','PRACTICE'),
('ws-m3b-02','subskill-m3b','2','PRACTICE'),
('ws-m3b-03','subskill-m3b','3','PRACTICE'),
('ws-m3b-04','subskill-m3b','4','MIXED'),
('ws-m3b-05','subskill-m3b','5','MASTERY_CHECK'),
('ws-m3c-01','subskill-m3c','1','PRACTICE'),
('ws-m3c-02','subskill-m3c','2','PRACTICE'),
('ws-m3c-03','subskill-m3c','3','PRACTICE'),
('ws-m3c-04','subskill-m3c','4','MIXED'),
('ws-m3c-05','subskill-m3c','5','MASTERY_CHECK'),
('ws-m3d-01','subskill-m3d','1','PRACTICE'),
('ws-m3d-02','subskill-m3d','2','PRACTICE'),
('ws-m3d-03','subskill-m3d','3','PRACTICE'),
('ws-m3d-04','subskill-m3d','4','MIXED'),
('ws-m3d-05','subskill-m3d','5','MASTERY_CHECK'),
('ws-m3e-01','subskill-m3e','1','PRACTICE'),
('ws-m3e-02','subskill-m3e','2','PRACTICE'),
('ws-m3e-03','subskill-m3e','3','PRACTICE'),
('ws-m3e-04','subskill-m3e','4','MIXED'),
('ws-m3e-05','subskill-m3e','5','MASTERY_CHECK'),
('ws-m3f-01','subskill-m3f','1','PRACTICE'),
('ws-m3f-02','subskill-m3f','2','PRACTICE'),
('ws-m3f-03','subskill-m3f','3','PRACTICE'),
('ws-m3f-04','subskill-m3f','4','MIXED'),
('ws-m3f-05','subskill-m3f','5','MASTERY_CHECK'),
('ws-m3g-01','subskill-m3g','1','PRACTICE'),
('ws-m3g-02','subskill-m3g','2','PRACTICE'),
('ws-m3g-03','subskill-m3g','3','PRACTICE'),
('ws-m3g-04','subskill-m3g','4','MIXED'),
('ws-m3g-05','subskill-m3g','5','MASTERY_CHECK'),
('ws-m3h-01','subskill-m3h','1','PRACTICE'),
('ws-m3h-02','subskill-m3h','2','PRACTICE'),
('ws-m3h-03','subskill-m3h','3','PRACTICE'),
('ws-m3h-04','subskill-m3h','4','MIXED'),
('ws-m3h-05','subskill-m3h','5','MASTERY_CHECK'),
('ws-m3i-01','subskill-m3i','1','PRACTICE'),
('ws-m3i-02','subskill-m3i','2','PRACTICE'),
('ws-m3i-03','subskill-m3i','3','PRACTICE'),
('ws-m3i-04','subskill-m3i','4','MIXED'),
('ws-m3i-05','subskill-m3i','5','MASTERY_CHECK'),
('ws-m3j-01','subskill-m3j','1','PRACTICE'),
('ws-m3j-02','subskill-m3j','2','PRACTICE'),
('ws-m3j-03','subskill-m3j','3','PRACTICE'),
('ws-m3j-04','subskill-m3j','4','MIXED'),
('ws-m3j-05','subskill-m3j','5','MASTERY_CHECK'),
('ws-m3k-01','subskill-m3k','1','PRACTICE'),
('ws-m3k-02','subskill-m3k','2','PRACTICE'),
('ws-m3k-03','subskill-m3k','3','PRACTICE'),
('ws-m3k-04','subskill-m3k','4','MIXED'),
('ws-m3k-05','subskill-m3k','5','MASTERY_CHECK'),
('ws-m3l-01','subskill-m3l','1','PRACTICE'),
('ws-m3l-02','subskill-m3l','2','PRACTICE'),
('ws-m3l-03','subskill-m3l','3','PRACTICE'),
('ws-m3l-04','subskill-m3l','4','MIXED'),
('ws-m3l-05','subskill-m3l','5','MASTERY_CHECK'),
('ws-m3r-01','subskill-m3r','1','PRACTICE'),
('ws-m3r-02','subskill-m3r','2','PRACTICE'),
('ws-m3r-03','subskill-m3r','3','PRACTICE'),
('ws-m3r-04','subskill-m3r','4','MIXED'),
('ws-m3r-05','subskill-m3r','5','MASTERY_CHECK'),
('ws-d1a-01','subskill-d1a','1','PRACTICE'),
('ws-d1a-02','subskill-d1a','2','PRACTICE'),
('ws-d1a-03','subskill-d1a','3','PRACTICE'),
('ws-d1a-04','subskill-d1a','4','MIXED'),
('ws-d1a-05','subskill-d1a','5','MASTERY_CHECK'),
('ws-d1b-01','subskill-d1b','1','PRACTICE'),
('ws-d1b-02','subskill-d1b','2','PRACTICE'),
('ws-d1b-03','subskill-d1b','3','PRACTICE'),
('ws-d1b-04','subskill-d1b','4','MIXED'),
('ws-d1b-05','subskill-d1b','5','MASTERY_CHECK'),
('ws-d1c-01','subskill-d1c','1','PRACTICE'),
('ws-d1c-02','subskill-d1c','2','PRACTICE'),
('ws-d1c-03','subskill-d1c','3','PRACTICE'),
('ws-d1c-04','subskill-d1c','4','MIXED'),
('ws-d1c-05','subskill-d1c','5','MASTERY_CHECK'),
('ws-d1d-01','subskill-d1d','1','PRACTICE'),
('ws-d1d-02','subskill-d1d','2','PRACTICE'),
('ws-d1d-03','subskill-d1d','3','PRACTICE'),
('ws-d1d-04','subskill-d1d','4','MIXED'),
('ws-d1d-05','subskill-d1d','5','MASTERY_CHECK'),
('ws-d1e-01','subskill-d1e','1','PRACTICE'),
('ws-d1e-02','subskill-d1e','2','PRACTICE'),
('ws-d1e-03','subskill-d1e','3','PRACTICE'),
('ws-d1e-04','subskill-d1e','4','MIXED'),
('ws-d1e-05','subskill-d1e','5','MASTERY_CHECK'),
('ws-d1f-01','subskill-d1f','1','PRACTICE'),
('ws-d1f-02','subskill-d1f','2','PRACTICE'),
('ws-d1f-03','subskill-d1f','3','PRACTICE'),
('ws-d1f-04','subskill-d1f','4','MIXED'),
('ws-d1f-05','subskill-d1f','5','MASTERY_CHECK'),
('ws-d1r-01','subskill-d1r','1','PRACTICE'),
('ws-d1r-02','subskill-d1r','2','PRACTICE'),
('ws-d1r-03','subskill-d1r','3','PRACTICE'),
('ws-d1r-04','subskill-d1r','4','MIXED'),
('ws-d1r-05','subskill-d1r','5','MASTERY_CHECK'),
('ws-d2a-01','subskill-d2a','1','PRACTICE'),
('ws-d2a-02','subskill-d2a','2','PRACTICE'),
('ws-d2a-03','subskill-d2a','3','PRACTICE'),
('ws-d2a-04','subskill-d2a','4','MIXED'),
('ws-d2a-05','subskill-d2a','5','MASTERY_CHECK'),
('ws-d2b-01','subskill-d2b','1','PRACTICE'),
('ws-d2b-02','subskill-d2b','2','PRACTICE'),
('ws-d2b-03','subskill-d2b','3','PRACTICE'),
('ws-d2b-04','subskill-d2b','4','MIXED'),
('ws-d2b-05','subskill-d2b','5','MASTERY_CHECK'),
('ws-d2c-01','subskill-d2c','1','PRACTICE'),
('ws-d2c-02','subskill-d2c','2','PRACTICE'),
('ws-d2c-03','subskill-d2c','3','PRACTICE'),
('ws-d2c-04','subskill-d2c','4','MIXED'),
('ws-d2c-05','subskill-d2c','5','MASTERY_CHECK'),
('ws-d2d-01','subskill-d2d','1','PRACTICE'),
('ws-d2d-02','subskill-d2d','2','PRACTICE'),
('ws-d2d-03','subskill-d2d','3','PRACTICE'),
('ws-d2d-04','subskill-d2d','4','MIXED'),
('ws-d2d-05','subskill-d2d','5','MASTERY_CHECK'),
('ws-d2e-01','subskill-d2e','1','PRACTICE'),
('ws-d2e-02','subskill-d2e','2','PRACTICE'),
('ws-d2e-03','subskill-d2e','3','PRACTICE'),
('ws-d2e-04','subskill-d2e','4','MIXED'),
('ws-d2e-05','subskill-d2e','5','MASTERY_CHECK'),
('ws-d2f-01','subskill-d2f','1','PRACTICE'),
('ws-d2f-02','subskill-d2f','2','PRACTICE'),
('ws-d2f-03','subskill-d2f','3','PRACTICE'),
('ws-d2f-04','subskill-d2f','4','MIXED'),
('ws-d2f-05','subskill-d2f','5','MASTERY_CHECK'),
('ws-d2r-01','subskill-d2r','1','PRACTICE'),
('ws-d2r-02','subskill-d2r','2','PRACTICE'),
('ws-d2r-03','subskill-d2r','3','PRACTICE'),
('ws-d2r-04','subskill-d2r','4','MIXED'),
('ws-d2r-05','subskill-d2r','5','MASTERY_CHECK'),
('ws-d3a-01','subskill-d3a','1','PRACTICE'),
('ws-d3a-02','subskill-d3a','2','PRACTICE'),
('ws-d3a-03','subskill-d3a','3','PRACTICE'),
('ws-d3a-04','subskill-d3a','4','MIXED'),
('ws-d3a-05','subskill-d3a','5','MASTERY_CHECK'),
('ws-d3b-01','subskill-d3b','1','PRACTICE'),
('ws-d3b-02','subskill-d3b','2','PRACTICE'),
('ws-d3b-03','subskill-d3b','3','PRACTICE'),
('ws-d3b-04','subskill-d3b','4','MIXED'),
('ws-d3b-05','subskill-d3b','5','MASTERY_CHECK'),
('ws-d3c-01','subskill-d3c','1','PRACTICE'),
('ws-d3c-02','subskill-d3c','2','PRACTICE'),
('ws-d3c-03','subskill-d3c','3','PRACTICE'),
('ws-d3c-04','subskill-d3c','4','MIXED'),
('ws-d3c-05','subskill-d3c','5','MASTERY_CHECK'),
('ws-d3d-01','subskill-d3d','1','PRACTICE'),
('ws-d3d-02','subskill-d3d','2','PRACTICE'),
('ws-d3d-03','subskill-d3d','3','PRACTICE'),
('ws-d3d-04','subskill-d3d','4','MIXED'),
('ws-d3d-05','subskill-d3d','5','MASTERY_CHECK'),
('ws-d3e-01','subskill-d3e','1','PRACTICE'),
('ws-d3e-02','subskill-d3e','2','PRACTICE'),
('ws-d3e-03','subskill-d3e','3','PRACTICE'),
('ws-d3e-04','subskill-d3e','4','MIXED'),
('ws-d3e-05','subskill-d3e','5','MASTERY_CHECK'),
('ws-d3f-01','subskill-d3f','1','PRACTICE'),
('ws-d3f-02','subskill-d3f','2','PRACTICE'),
('ws-d3f-03','subskill-d3f','3','PRACTICE'),
('ws-d3f-04','subskill-d3f','4','MIXED'),
('ws-d3f-05','subskill-d3f','5','MASTERY_CHECK'),
('ws-d3g-01','subskill-d3g','1','PRACTICE'),
('ws-d3g-02','subskill-d3g','2','PRACTICE'),
('ws-d3g-03','subskill-d3g','3','PRACTICE'),
('ws-d3g-04','subskill-d3g','4','MIXED'),
('ws-d3g-05','subskill-d3g','5','MASTERY_CHECK'),
('ws-d3r-01','subskill-d3r','1','PRACTICE'),
('ws-d3r-02','subskill-d3r','2','PRACTICE'),
('ws-d3r-03','subskill-d3r','3','PRACTICE'),
('ws-d3r-04','subskill-d3r','4','MIXED'),
('ws-d3r-05','subskill-d3r','5','MASTERY_CHECK'),
('ws-d4a-01','subskill-d4a','1','PRACTICE'),
('ws-d4a-02','subskill-d4a','2','PRACTICE'),
('ws-d4a-03','subskill-d4a','3','PRACTICE'),
('ws-d4a-04','subskill-d4a','4','MIXED'),
('ws-d4a-05','subskill-d4a','5','MASTERY_CHECK'),
('ws-d4b-01','subskill-d4b','1','PRACTICE'),
('ws-d4b-02','subskill-d4b','2','PRACTICE'),
('ws-d4b-03','subskill-d4b','3','PRACTICE'),
('ws-d4b-04','subskill-d4b','4','MIXED'),
('ws-d4b-05','subskill-d4b','5','MASTERY_CHECK'),
('ws-d4c-01','subskill-d4c','1','PRACTICE'),
('ws-d4c-02','subskill-d4c','2','PRACTICE'),
('ws-d4c-03','subskill-d4c','3','PRACTICE'),
('ws-d4c-04','subskill-d4c','4','MIXED'),
('ws-d4c-05','subskill-d4c','5','MASTERY_CHECK'),
('ws-d4d-01','subskill-d4d','1','PRACTICE'),
('ws-d4d-02','subskill-d4d','2','PRACTICE'),
('ws-d4d-03','subskill-d4d','3','PRACTICE'),
('ws-d4d-04','subskill-d4d','4','MIXED'),
('ws-d4d-05','subskill-d4d','5','MASTERY_CHECK'),
('ws-d4e-01','subskill-d4e','1','PRACTICE'),
('ws-d4e-02','subskill-d4e','2','PRACTICE'),
('ws-d4e-03','subskill-d4e','3','PRACTICE'),
('ws-d4e-04','subskill-d4e','4','MIXED'),
('ws-d4e-05','subskill-d4e','5','MASTERY_CHECK'),
('ws-d4r-01','subskill-d4r','1','PRACTICE'),
('ws-d4r-02','subskill-d4r','2','PRACTICE'),
('ws-d4r-03','subskill-d4r','3','PRACTICE'),
('ws-d4r-04','subskill-d4r','4','MIXED'),
('ws-d4r-05','subskill-d4r','5','MASTERY_CHECK'),
('ws-d5a-01','subskill-d5a','1','PRACTICE'),
('ws-d5a-02','subskill-d5a','2','PRACTICE'),
('ws-d5a-03','subskill-d5a','3','PRACTICE'),
('ws-d5a-04','subskill-d5a','4','MIXED'),
('ws-d5a-05','subskill-d5a','5','MASTERY_CHECK'),
('ws-d5b-01','subskill-d5b','1','PRACTICE'),
('ws-d5b-02','subskill-d5b','2','PRACTICE'),
('ws-d5b-03','subskill-d5b','3','PRACTICE'),
('ws-d5b-04','subskill-d5b','4','MIXED'),
('ws-d5b-05','subskill-d5b','5','MASTERY_CHECK'),
('ws-d5c-01','subskill-d5c','1','PRACTICE'),
('ws-d5c-02','subskill-d5c','2','PRACTICE'),
('ws-d5c-03','subskill-d5c','3','PRACTICE'),
('ws-d5c-04','subskill-d5c','4','MIXED'),
('ws-d5c-05','subskill-d5c','5','MASTERY_CHECK'),
('ws-d5d-01','subskill-d5d','1','PRACTICE'),
('ws-d5d-02','subskill-d5d','2','PRACTICE'),
('ws-d5d-03','subskill-d5d','3','PRACTICE'),
('ws-d5d-04','subskill-d5d','4','MIXED'),
('ws-d5d-05','subskill-d5d','5','MASTERY_CHECK'),
('ws-d5e-01','subskill-d5e','1','PRACTICE'),
('ws-d5e-02','subskill-d5e','2','PRACTICE'),
('ws-d5e-03','subskill-d5e','3','PRACTICE'),
('ws-d5e-04','subskill-d5e','4','MIXED'),
('ws-d5e-05','subskill-d5e','5','MASTERY_CHECK'),
('ws-d5r-01','subskill-d5r','1','PRACTICE'),
('ws-d5r-02','subskill-d5r','2','PRACTICE'),
('ws-d5r-03','subskill-d5r','3','PRACTICE'),
('ws-d5r-04','subskill-d5r','4','MIXED'),
('ws-d5r-05','subskill-d5r','5','MASTERY_CHECK'),
('ws-d6a-01','subskill-d6a','1','PRACTICE'),
('ws-d6a-02','subskill-d6a','2','PRACTICE'),
('ws-d6a-03','subskill-d6a','3','PRACTICE'),
('ws-d6a-04','subskill-d6a','4','MIXED'),
('ws-d6a-05','subskill-d6a','5','MASTERY_CHECK'),
('ws-d6b-01','subskill-d6b','1','PRACTICE'),
('ws-d6b-02','subskill-d6b','2','PRACTICE'),
('ws-d6b-03','subskill-d6b','3','PRACTICE'),
('ws-d6b-04','subskill-d6b','4','MIXED'),
('ws-d6b-05','subskill-d6b','5','MASTERY_CHECK'),
('ws-d6c-01','subskill-d6c','1','PRACTICE'),
('ws-d6c-02','subskill-d6c','2','PRACTICE'),
('ws-d6c-03','subskill-d6c','3','PRACTICE'),
('ws-d6c-04','subskill-d6c','4','MIXED'),
('ws-d6c-05','subskill-d6c','5','MASTERY_CHECK'),
('ws-d7a-01','subskill-d7a','1','PRACTICE'),
('ws-d7a-02','subskill-d7a','2','PRACTICE'),
('ws-d7a-03','subskill-d7a','3','PRACTICE'),
('ws-d7a-04','subskill-d7a','4','MIXED'),
('ws-d7a-05','subskill-d7a','5','MASTERY_CHECK'),
('ws-d7b-01','subskill-d7b','1','PRACTICE'),
('ws-d7b-02','subskill-d7b','2','PRACTICE'),
('ws-d7b-03','subskill-d7b','3','PRACTICE'),
('ws-d7b-04','subskill-d7b','4','MIXED'),
('ws-d7b-05','subskill-d7b','5','MASTERY_CHECK'),
('ws-d7c-01','subskill-d7c','1','PRACTICE'),
('ws-d7c-02','subskill-d7c','2','PRACTICE'),
('ws-d7c-03','subskill-d7c','3','PRACTICE'),
('ws-d7c-04','subskill-d7c','4','MIXED'),
('ws-d7c-05','subskill-d7c','5','MASTERY_CHECK'),
('ws-d7d-01','subskill-d7d','1','PRACTICE'),
('ws-d7d-02','subskill-d7d','2','PRACTICE'),
('ws-d7d-03','subskill-d7d','3','PRACTICE'),
('ws-d7d-04','subskill-d7d','4','MIXED'),
('ws-d7d-05','subskill-d7d','5','MASTERY_CHECK'),
('ws-d-r-01','subskill-d-r','1','PRACTICE'),
('ws-d-r-02','subskill-d-r','2','PRACTICE'),
('ws-d-r-03','subskill-d-r','3','PRACTICE'),
('ws-d-r-04','subskill-d-r','4','MIXED'),
('ws-d-r-05','subskill-d-r','5','MASTERY_CHECK'),
('ws-g1a-01','subskill-g1a','1','PRACTICE'),
('ws-g1a-02','subskill-g1a','2','PRACTICE'),
('ws-g1a-03','subskill-g1a','3','PRACTICE'),
('ws-g1a-04','subskill-g1a','4','MIXED'),
('ws-g1a-05','subskill-g1a','5','MASTERY_CHECK'),
('ws-g1b-01','subskill-g1b','1','PRACTICE'),
('ws-g1b-02','subskill-g1b','2','PRACTICE'),
('ws-g1b-03','subskill-g1b','3','PRACTICE'),
('ws-g1b-04','subskill-g1b','4','MIXED'),
('ws-g1b-05','subskill-g1b','5','MASTERY_CHECK'),
('ws-g1c-01','subskill-g1c','1','PRACTICE'),
('ws-g1c-02','subskill-g1c','2','PRACTICE'),
('ws-g1c-03','subskill-g1c','3','PRACTICE'),
('ws-g1c-04','subskill-g1c','4','MIXED'),
('ws-g1c-05','subskill-g1c','5','MASTERY_CHECK'),
('ws-g1d-01','subskill-g1d','1','PRACTICE'),
('ws-g1d-02','subskill-g1d','2','PRACTICE'),
('ws-g1d-03','subskill-g1d','3','PRACTICE'),
('ws-g1d-04','subskill-g1d','4','MIXED'),
('ws-g1d-05','subskill-g1d','5','MASTERY_CHECK'),
('ws-g1e-01','subskill-g1e','1','PRACTICE'),
('ws-g1e-02','subskill-g1e','2','PRACTICE'),
('ws-g1e-03','subskill-g1e','3','PRACTICE'),
('ws-g1e-04','subskill-g1e','4','MIXED'),
('ws-g1e-05','subskill-g1e','5','MASTERY_CHECK'),
('ws-g1f-01','subskill-g1f','1','PRACTICE'),
('ws-g1f-02','subskill-g1f','2','PRACTICE'),
('ws-g1f-03','subskill-g1f','3','PRACTICE'),
('ws-g1f-04','subskill-g1f','4','MIXED'),
('ws-g1f-05','subskill-g1f','5','MASTERY_CHECK'),
('ws-g1g-01','subskill-g1g','1','PRACTICE'),
('ws-g1g-02','subskill-g1g','2','PRACTICE'),
('ws-g1g-03','subskill-g1g','3','PRACTICE'),
('ws-g1g-04','subskill-g1g','4','MIXED'),
('ws-g1g-05','subskill-g1g','5','MASTERY_CHECK'),
('ws-g1r-01','subskill-g1r','1','PRACTICE'),
('ws-g1r-02','subskill-g1r','2','PRACTICE'),
('ws-g1r-03','subskill-g1r','3','PRACTICE'),
('ws-g1r-04','subskill-g1r','4','MIXED'),
('ws-g1r-05','subskill-g1r','5','MASTERY_CHECK'),
('ws-g2a-01','subskill-g2a','1','PRACTICE'),
('ws-g2a-02','subskill-g2a','2','PRACTICE'),
('ws-g2a-03','subskill-g2a','3','PRACTICE'),
('ws-g2a-04','subskill-g2a','4','MIXED'),
('ws-g2a-05','subskill-g2a','5','MASTERY_CHECK'),
('ws-g2b-01','subskill-g2b','1','PRACTICE'),
('ws-g2b-02','subskill-g2b','2','PRACTICE'),
('ws-g2b-03','subskill-g2b','3','PRACTICE'),
('ws-g2b-04','subskill-g2b','4','MIXED'),
('ws-g2b-05','subskill-g2b','5','MASTERY_CHECK'),
('ws-g2c-01','subskill-g2c','1','PRACTICE'),
('ws-g2c-02','subskill-g2c','2','PRACTICE'),
('ws-g2c-03','subskill-g2c','3','PRACTICE'),
('ws-g2c-04','subskill-g2c','4','MIXED'),
('ws-g2c-05','subskill-g2c','5','MASTERY_CHECK'),
('ws-g2d-01','subskill-g2d','1','PRACTICE'),
('ws-g2d-02','subskill-g2d','2','PRACTICE'),
('ws-g2d-03','subskill-g2d','3','PRACTICE'),
('ws-g2d-04','subskill-g2d','4','MIXED'),
('ws-g2d-05','subskill-g2d','5','MASTERY_CHECK'),
('ws-g2e-01','subskill-g2e','1','PRACTICE'),
('ws-g2e-02','subskill-g2e','2','PRACTICE'),
('ws-g2e-03','subskill-g2e','3','PRACTICE'),
('ws-g2e-04','subskill-g2e','4','MIXED'),
('ws-g2e-05','subskill-g2e','5','MASTERY_CHECK'),
('ws-g2f-01','subskill-g2f','1','PRACTICE'),
('ws-g2f-02','subskill-g2f','2','PRACTICE'),
('ws-g2f-03','subskill-g2f','3','PRACTICE'),
('ws-g2f-04','subskill-g2f','4','MIXED'),
('ws-g2f-05','subskill-g2f','5','MASTERY_CHECK'),
('ws-g2g-01','subskill-g2g','1','PRACTICE'),
('ws-g2g-02','subskill-g2g','2','PRACTICE'),
('ws-g2g-03','subskill-g2g','3','PRACTICE'),
('ws-g2g-04','subskill-g2g','4','MIXED'),
('ws-g2g-05','subskill-g2g','5','MASTERY_CHECK'),
('ws-g2r-01','subskill-g2r','1','PRACTICE'),
('ws-g2r-02','subskill-g2r','2','PRACTICE'),
('ws-g2r-03','subskill-g2r','3','PRACTICE'),
('ws-g2r-04','subskill-g2r','4','MIXED'),
('ws-g2r-05','subskill-g2r','5','MASTERY_CHECK'),
('ws-g3a-01','subskill-g3a','1','PRACTICE'),
('ws-g3a-02','subskill-g3a','2','PRACTICE'),
('ws-g3a-03','subskill-g3a','3','PRACTICE'),
('ws-g3a-04','subskill-g3a','4','MIXED'),
('ws-g3a-05','subskill-g3a','5','MASTERY_CHECK'),
('ws-g3b-01','subskill-g3b','1','PRACTICE'),
('ws-g3b-02','subskill-g3b','2','PRACTICE'),
('ws-g3b-03','subskill-g3b','3','PRACTICE'),
('ws-g3b-04','subskill-g3b','4','MIXED'),
('ws-g3b-05','subskill-g3b','5','MASTERY_CHECK'),
('ws-g3c-01','subskill-g3c','1','PRACTICE'),
('ws-g3c-02','subskill-g3c','2','PRACTICE'),
('ws-g3c-03','subskill-g3c','3','PRACTICE'),
('ws-g3c-04','subskill-g3c','4','MIXED'),
('ws-g3c-05','subskill-g3c','5','MASTERY_CHECK'),
('ws-g3d-01','subskill-g3d','1','PRACTICE'),
('ws-g3d-02','subskill-g3d','2','PRACTICE'),
('ws-g3d-03','subskill-g3d','3','PRACTICE'),
('ws-g3d-04','subskill-g3d','4','MIXED'),
('ws-g3d-05','subskill-g3d','5','MASTERY_CHECK'),
('ws-g3e-01','subskill-g3e','1','PRACTICE'),
('ws-g3e-02','subskill-g3e','2','PRACTICE'),
('ws-g3e-03','subskill-g3e','3','PRACTICE'),
('ws-g3e-04','subskill-g3e','4','MIXED'),
('ws-g3e-05','subskill-g3e','5','MASTERY_CHECK'),
('ws-g3f-01','subskill-g3f','1','PRACTICE'),
('ws-g3f-02','subskill-g3f','2','PRACTICE'),
('ws-g3f-03','subskill-g3f','3','PRACTICE'),
('ws-g3f-04','subskill-g3f','4','MIXED'),
('ws-g3f-05','subskill-g3f','5','MASTERY_CHECK'),
('ws-g3g-01','subskill-g3g','1','PRACTICE'),
('ws-g3g-02','subskill-g3g','2','PRACTICE'),
('ws-g3g-03','subskill-g3g','3','PRACTICE'),
('ws-g3g-04','subskill-g3g','4','MIXED'),
('ws-g3g-05','subskill-g3g','5','MASTERY_CHECK'),
('ws-g3r-01','subskill-g3r','1','PRACTICE'),
('ws-g3r-02','subskill-g3r','2','PRACTICE'),
('ws-g3r-03','subskill-g3r','3','PRACTICE'),
('ws-g3r-04','subskill-g3r','4','MIXED'),
('ws-g3r-05','subskill-g3r','5','MASTERY_CHECK'),
('ws-g4f-01','subskill-g4f','1','PRACTICE'),
('ws-g4f-02','subskill-g4f','2','PRACTICE'),
('ws-g4f-03','subskill-g4f','3','PRACTICE'),
('ws-g4f-04','subskill-g4f','4','MIXED'),
('ws-g4f-05','subskill-g4f','5','MASTERY_CHECK'),
('ws-g4a-01','subskill-g4a','1','PRACTICE'),
('ws-g4a-02','subskill-g4a','2','PRACTICE'),
('ws-g4a-03','subskill-g4a','3','PRACTICE'),
('ws-g4a-04','subskill-g4a','4','MIXED'),
('ws-g4a-05','subskill-g4a','5','MASTERY_CHECK'),
('ws-g4b-01','subskill-g4b','1','PRACTICE'),
('ws-g4b-02','subskill-g4b','2','PRACTICE'),
('ws-g4b-03','subskill-g4b','3','PRACTICE'),
('ws-g4b-04','subskill-g4b','4','MIXED'),
('ws-g4b-05','subskill-g4b','5','MASTERY_CHECK'),
('ws-g4c-01','subskill-g4c','1','PRACTICE'),
('ws-g4c-02','subskill-g4c','2','PRACTICE'),
('ws-g4c-03','subskill-g4c','3','PRACTICE'),
('ws-g4c-04','subskill-g4c','4','MIXED'),
('ws-g4c-05','subskill-g4c','5','MASTERY_CHECK'),
('ws-g4d-01','subskill-g4d','1','PRACTICE'),
('ws-g4d-02','subskill-g4d','2','PRACTICE'),
('ws-g4d-03','subskill-g4d','3','PRACTICE'),
('ws-g4d-04','subskill-g4d','4','MIXED'),
('ws-g4d-05','subskill-g4d','5','MASTERY_CHECK'),
('ws-g4e-01','subskill-g4e','1','PRACTICE'),
('ws-g4e-02','subskill-g4e','2','PRACTICE'),
('ws-g4e-03','subskill-g4e','3','PRACTICE'),
('ws-g4e-04','subskill-g4e','4','MIXED'),
('ws-g4e-05','subskill-g4e','5','MASTERY_CHECK'),
('ws-g4g-01','subskill-g4g','1','PRACTICE'),
('ws-g4g-02','subskill-g4g','2','PRACTICE'),
('ws-g4g-03','subskill-g4g','3','PRACTICE'),
('ws-g4g-04','subskill-g4g','4','MIXED'),
('ws-g4g-05','subskill-g4g','5','MASTERY_CHECK'),
('ws-g4h-01','subskill-g4h','1','PRACTICE'),
('ws-g4h-02','subskill-g4h','2','PRACTICE'),
('ws-g4h-03','subskill-g4h','3','PRACTICE'),
('ws-g4h-04','subskill-g4h','4','MIXED'),
('ws-g4h-05','subskill-g4h','5','MASTERY_CHECK'),
('ws-g4r-01','subskill-g4r','1','PRACTICE'),
('ws-g4r-02','subskill-g4r','2','PRACTICE'),
('ws-g4r-03','subskill-g4r','3','PRACTICE'),
('ws-g4r-04','subskill-g4r','4','MIXED'),
('ws-g4r-05','subskill-g4r','5','MASTERY_CHECK');

INSERT INTO mastery_students (id,display_name,placement_level_index,current_level_id,daily_page_target) VALUES ('demo-student','Alex',1,'subskill-f1a',3);

PRAGMA foreign_keys = ON;

PRAGMA optimize;
