"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, LockKeyhole, RotateCcw, X } from "lucide-react";
import { BlockMath } from "react-katex";
import { RoleGuard, useApp } from "./AppProvider";
import { accentColor, getCategoryForTopic, getSkill, type DrillUnit, type Question } from "@/lib/curriculum";

const unitStatus = { complete: "Complete", in_progress: "In Progress", available: "Not Started", locked: "Locked", review: "Review Required" } as const;

function QuestionView({ question, position, total, onComplete }: { question: Question; position: number; total: number; onComplete: () => void }) {
  const { addError } = useApp();
  const [answer, setAnswer] = useState(""); const [attempts, setAttempts] = useState(0);
  const [state, setState] = useState<"idle" | "retry" | "correct" | "explain">("idle");
  useEffect(() => { setAnswer(""); setAttempts(0); setState("idle"); }, [question.id]);
  const check = () => {
    if (!answer) return; const correct = answer.trim().toLowerCase() === question.correctAnswer.trim().toLowerCase();
    if (correct) return setState("correct");
    if (attempts === 0) { addError(question.id, question.skillId); setAttempts(1); setState("retry"); setAnswer(""); } else setState("explain");
  };
  return <div className="mx-auto w-full max-w-[820px]">
    <div className="mb-8 flex items-center justify-between border-b border-[#dfe3e7] pb-4"><span className="label capitalize text-[#677386]">{question.difficulty} · {position} of {total}</span><div className="flex gap-1">{Array.from({ length: total }, (_, i) => <span key={i} className={`h-1.5 w-7 ${i < position ? "bg-[#17365f]" : "bg-[#dfe3e7]"}`}/>)}</div></div>
    <div className="min-h-[330px]"><p className="mb-3 text-xs font-bold text-[#677386]">Target: {question.frameworkTarget}</p><h2 className="academic-heading max-w-[760px] text-[clamp(25px,4vw,36px)] leading-[1.35]">{question.prompt}</h2>{question.math && <BlockMath math={question.math}/>}<div className="mt-9 space-y-3">
      {question.questionType === "multiple_choice" ? question.choices?.map((choice, i) => <button type="button" key={choice} onClick={() => !["correct", "explain"].includes(state) && setAnswer(choice)} className={`flex w-full items-center gap-4 border px-4 py-3.5 text-left text-sm ${answer === choice ? "border-[#17365f] bg-[#f2f5f8]" : "border-[#dfe3e7] bg-white hover:border-[#9da8b5]"}`}><span className="grid size-7 shrink-0 place-items-center border border-[#b8c0c9] font-bold">{String.fromCharCode(65 + i)}</span>{choice}</button>) : <label className="label block max-w-xs text-[#677386]">Enter your answer<input value={answer} onChange={(e) => setAnswer(e.target.value)} className="field mt-2 text-lg" disabled={["correct", "explain"].includes(state)}/></label>}
    </div></div>
    {state !== "idle" && <div className={`mb-5 border-l-2 px-4 py-3 text-sm ${state === "correct" ? "border-[#4f7a66] bg-[#f3f7f4] text-[#315c47]" : "border-[#a1623c] bg-[#fbf6f2] text-[#76472b]"}`}><div className="flex items-center gap-2 font-bold">{state === "correct" ? <><Check size={16}/>Correct.</> : state === "retry" ? <><RotateCcw size={15}/>Try again.</> : <><X size={15}/>Review the solution.</>}</div>{state === "explain" && <p className="mt-2 leading-6">{question.explanation}</p>}</div>}
    <div className="flex justify-end">{["correct", "explain"].includes(state) ? <button className="btn-primary" onClick={onComplete}>Next <ArrowRight size={16}/></button> : <button className="btn-primary" disabled={!answer} onClick={check}>Check Answer</button>}</div>
  </div>;
}

export function DrillExperience() {
  const params = useParams<{ topic: string }>(); const skill = getSkill(params.topic); const category = getCategoryForTopic(params.topic); const { data } = useApp();
  if (!skill || !category) return <RoleGuard role="student"><div className="p-10">Skill not found.</div></RoleGuard>;
  const units = data.drillUnits.filter((item) => item.skillId === skill.id && item.isActive).sort((a, b) => a.order - b.order);
  const completeCount = units.filter((item) => data.unitProgress[item.id]?.status === "complete").length;
  const allComplete = units.length > 0 && completeCount === units.length; const progress = data.progress[skill.id]; const gatePassed = progress?.gateScore === skill.gateThreshold;
  const color = accentColor[category.accent];
  return <RoleGuard role="student"><main className="min-h-screen bg-[#fafaf8]"><header className="border-b border-[#dfe3e7] bg-white"><div className="mx-auto flex h-[68px] max-w-[1120px] items-center justify-between px-5"><Link href={`/category/${category.id}`} className="flex items-center gap-2 text-xs font-bold text-[#677386]"><ArrowLeft size={14}/>{category.shortName}</Link><div className="label" style={{ color }}>{skill.code} · Official SAT skill</div></div></header>
    <div className="mx-auto max-w-[960px] px-5 py-10"><div className="mb-9 border-b border-[#dfe3e7] pb-7"><p className="label" style={{ color }}>{skill.code}</p><h1 className="academic-heading mt-2 text-4xl">{skill.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#677386]">Complete each workbook section in order. The skill gate samples across the full framework coverage.</p><div className="mt-5 flex items-center gap-4"><div className="progress-track max-w-sm flex-1" style={{ "--accent": color } as React.CSSProperties}><div className="progress-fill" style={{ width: `${(completeCount / Math.max(1, units.length)) * 100}%` }}/></div><b className="text-xs">{completeCount} / {units.length} units</b></div>
      <section className="panel overflow-hidden">{units.map((unit, index) => { const state = data.unitProgress[unit.id]?.status ?? "locked"; const locked = state === "locked"; return <div key={unit.id} className="grid gap-4 border-b border-[#e4e7e9] p-5 last:border-0 sm:grid-cols-[64px_1fr_auto] sm:items-center"><div className="font-serif text-xl text-[#7d8794]">{unit.code}</div><div><h2 className="text-[15px] font-extrabold">{unit.name}</h2><p className="mt-1 text-xs leading-5 text-[#677386]">{unit.frameworkTargets.length} framework target{unit.frameworkTargets.length === 1 ? "" : "s"} · {unit.easyQuestionCount} Easy · {unit.mediumQuestionCount} Medium</p><p className={`mt-2 text-xs font-bold ${state === "complete" ? "text-[#4f7a66]" : "text-[#7d8794]"}`}>{state === "complete" && <Check className="mr-1 inline" size={13}/>} {locked && <LockKeyhole className="mr-1 inline" size={12}/>} {unitStatus[state]}</p></div>{locked ? <span className="text-xs text-[#9aa2ad]">Complete {units[index - 1]?.code}</span> : <Link className="btn-secondary" href={`/topic/${skill.id}/unit/${unit.id}`}>{state === "complete" ? "Review" : state === "in_progress" ? "Continue" : "Begin"}<ArrowRight size={14}/></Link>}</div>; })}
        <div className="grid gap-4 border-b border-[#e4e7e9] bg-[#f7f6f2] p-5 sm:grid-cols-[64px_1fr_auto] sm:items-center"><div className="font-serif text-xl text-[#7d8794]">Gate</div><div><h2 className="text-[15px] font-extrabold">{skill.code} Skill Gate</h2><p className="mt-1 text-xs text-[#677386]">{skill.gateQuestionCount} questions · {skill.gateThreshold}/{skill.gateQuestionCount} required</p></div>{allComplete ? <Link className="btn-secondary" href={`/topic/${skill.id}/gate`}>{gatePassed ? "Review" : "Open gate"}<ArrowRight size={14}/></Link> : <span className="text-xs text-[#9aa2ad]"><LockKeyhole className="mr-1 inline" size={12}/>Locked</span>}</div>
        <div className="grid gap-4 bg-[#f7f6f2] p-5 sm:grid-cols-[64px_1fr_auto] sm:items-center"><div className="font-serif text-xl text-[#7d8794]">Live</div><div><h2 className="text-[15px] font-extrabold">Live Challenge</h2><p className="mt-1 text-xs text-[#677386]">Hard reasoning, recognition, strategy, and teacher guidance</p></div>{gatePassed ? <Link className="btn-primary" href={`/topic/${skill.id}/challenge`}>Open challenge<ArrowRight size={14}/></Link> : <span className="text-xs text-[#9aa2ad]"><LockKeyhole className="mr-1 inline" size={12}/>Pass the skill gate</span>}</div>
      </section></div></div></main></RoleGuard>;
}

type UnitStage = "concept" | "example" | "easy" | "easyDone" | "medium" | "complete";
export function DrillUnitExperience() {
  const params = useParams<{ topic: string; unit: string }>(); const skill = getSkill(params.topic); const category = getCategoryForTopic(params.topic); const { data, updateUnitProgress } = useApp();
  const unit = data.drillUnits.find((item) => item.id === params.unit && item.skillId === params.topic); const progress = data.unitProgress[params.unit];
  const easy = useMemo(() => data.questions.filter((q) => q.drillUnitId === params.unit && q.difficulty === "easy" && !q.isGate).sort((a,b) => a.order-b.order).slice(0, unit?.easyQuestionCount ?? 3), [data.questions, params.unit, unit?.easyQuestionCount]);
  const medium = useMemo(() => data.questions.filter((q) => q.drillUnitId === params.unit && q.difficulty === "medium" && !q.isGate).sort((a,b) => a.order-b.order).slice(0, unit?.mediumQuestionCount ?? 2), [data.questions, params.unit, unit?.mediumQuestionCount]);
  const [stage, setStage] = useState<UnitStage>(progress?.status === "complete" ? "complete" : progress?.mediumCompleted ? "medium" : progress?.easyCompleted ? "easy" : "concept");
  const [easyIndex, setEasyIndex] = useState(Math.min(progress?.easyCompleted ?? 0, Math.max(0, easy.length - 1))); const [mediumIndex, setMediumIndex] = useState(Math.min(progress?.mediumCompleted ?? 0, Math.max(0, medium.length - 1)));
  if (!skill || !category || !unit || !progress) return <RoleGuard role="student"><div className="p-10">Drill unit not found.</div></RoleGuard>;
  if (progress.status === "locked") return <RoleGuard role="student"><main className="grid min-h-screen place-items-center bg-[#fafaf8] p-6"><div className="panel max-w-md p-8 text-center"><LockKeyhole className="mx-auto text-[#8a939f]"/><h1 className="academic-heading mt-4 text-3xl">This section is locked.</h1><p className="mt-3 text-sm text-[#677386]">Complete the prior drill unit first.</p><Link className="btn-primary mt-6" href={`/topic/${skill.id}`}>Return to skill</Link></div></main></RoleGuard>;
  const units = data.drillUnits.filter((item) => item.skillId === skill.id && item.isActive).sort((a,b) => a.order-b.order); const next = units[units.findIndex((item) => item.id === unit.id) + 1]; const color = accentColor[category.accent];
  const finish = (kind: "easy" | "medium") => {
    if (kind === "easy") { const count = easyIndex + 1; updateUnitProgress(unit.id, { easyCompleted: Math.max(progress.easyCompleted, count), status: "in_progress" }); if (count >= easy.length) setStage("easyDone"); else setEasyIndex(count); }
    else { const count = mediumIndex + 1; const done = count >= medium.length; updateUnitProgress(unit.id, { mediumCompleted: Math.max(progress.mediumCompleted, count), status: done ? "complete" : "in_progress" }); if (done) setStage("complete"); else setMediumIndex(count); }
  };
  return <RoleGuard role="student"><main className="min-h-screen bg-[#fafaf8]"><header className="border-b border-[#dfe3e7] bg-white"><div className="mx-auto flex h-[68px] max-w-[1120px] items-center justify-between px-5"><Link href={`/topic/${skill.id}`} className="flex items-center gap-2 text-xs font-bold text-[#677386]"><ArrowLeft size={14}/>Exit section</Link><div className="text-right"><div className="label" style={{ color }}>{skill.code} · {unit.code}</div><div className="text-xs font-extrabold">{unit.name}</div></div></div></header><div className="mx-auto max-w-[960px] px-5 py-9"><div className="mb-9 flex flex-wrap items-end justify-between gap-4 border-b border-[#dfe3e7] pb-6"><div><p className="label" style={{ color }}>{unit.code} · Workbook section</p><h1 className="academic-heading mt-2 text-3xl">{unit.name}</h1></div><div className="flex gap-1 text-[10px] font-bold uppercase tracking-[.06em]">{["Concept","Example","Easy","Medium","Complete"].map((label, i) => <span key={label} className={`border px-2 py-1.5 ${stage.toLowerCase().startsWith(label.toLowerCase()) || (stage === "easyDone" && label === "Easy") ? "border-[#17365f] bg-[#17365f] text-white" : "border-[#dfe3e7] bg-white text-[#7c8693]"}`}>{i + 1}. {label}</span>)}</div></div>
    {stage === "concept" && <div className="mx-auto max-w-[820px]"><p className="label" style={{ color }}>Concept</p><h2 className="academic-heading mt-2 text-4xl">{unit.name}</h2><p className="mt-4 max-w-2xl text-base leading-7 text-[#435064]">{unit.description}</p><div className="mt-7 flex justify-end"><button className="btn-primary" onClick={() => setStage("example")}>Worked example <ArrowRight size={16}/></button></div></div>}
    {stage === "example" && <div className="mx-auto max-w-[820px]"><p className="label" style={{ color }}>Worked example</p><h2 className="academic-heading mt-3 text-3xl leading-[1.35]">{unit.workedExample.prompt}</h2><div className="hairline-grid mt-8 min-h-[280px] border border-[#dfe3e7] bg-white p-8"><div className="max-w-md space-y-4 bg-white/95 p-3">{unit.workedExample.steps.map((step, i) => <div key={step} className="flex gap-4"><span className="text-xs font-bold text-[#8a939f]">{i + 1}</span><p>{step}</p></div>)}</div></div><div className="mt-7 flex justify-end"><button className="btn-primary" onClick={() => setStage("easy")}>Begin Easy drill <ArrowRight size={16}/></button></div></div>}
    {stage === "easy" && easy[easyIndex] && (
      <QuestionView question={easy[easyIndex]} position={easyIndex + 1} total={easy.length} onComplete={() => finish("easy")}/>
    )}
    {stage === "easyDone" && <div className="mx-auto max-w-[680px] border-y border-[#dfe3e7] py-16 text-center"><p className="label text-[#4f7a66]">Easy drill complete</p><h2 className="academic-heading mt-3 text-4xl">Apply the same target in less direct questions.</h2><button className="btn-primary mt-8" onClick={() => setStage("medium")}>Continue to Medium <ArrowRight size={16}/></button></div>}
    {stage === "medium" && medium[mediumIndex] && (
      <QuestionView question={medium[mediumIndex]} position={mediumIndex + 1} total={medium.length} onComplete={() => finish("medium")}/>
    )}
    {stage === "complete" && <div className="mx-auto max-w-[680px] border-y-2 border-[#10233f] py-14 text-center"><Check className="mx-auto text-[#4f7a66]"/><p className="label mt-4 text-[#4f7a66]">Unit complete</p><h2 className="academic-heading mt-3 text-4xl">{unit.code} is complete.</h2><p className="mt-4 text-sm text-[#677386]">Your progress has been saved. {next ? `${next.code} is now available.` : `The ${skill.code} Skill Gate is now available.`}</p><div className="mt-8 flex justify-center gap-3"><Link className="btn-secondary" href={`/topic/${skill.id}`}>Skill overview</Link><Link className="btn-primary" href={next ? `/topic/${skill.id}/unit/${next.id}` : `/topic/${skill.id}/gate`}>{next ? `Continue to ${next.code}` : "Open Skill Gate"}<ArrowRight size={16}/></Link></div></div>}
  </div></main></RoleGuard>;
}

export function SkillGateExperience() {
  const params = useParams<{ topic: string }>(); const skill = getSkill(params.topic); const category = getCategoryForTopic(params.topic); const { data, updateProgress } = useApp();
  const [answers, setAnswers] = useState<Record<string, string>>({}); const [result, setResult] = useState<number | null>(null);
  if (!skill || !category) return <RoleGuard role="student"><div className="p-10">Skill not found.</div></RoleGuard>;
  const allComplete = data.drillUnits.filter((item) => item.skillId === skill.id && item.isActive).every((item) => data.unitProgress[item.id]?.status === "complete");
  const gate = data.questions.filter((question) => question.skillId === skill.id && question.isGate).sort((a,b) => a.order-b.order).slice(0, skill.gateQuestionCount);
  if (!allComplete) return <RoleGuard role="student"><main className="grid min-h-screen place-items-center bg-[#fafaf8]"><div className="panel max-w-md p-8 text-center"><LockKeyhole className="mx-auto text-[#8a939f]"/><h1 className="academic-heading mt-4 text-3xl">Skill Gate locked</h1><p className="mt-3 text-sm text-[#677386]">Complete all {skill.drillUnits.length} drill units first.</p><Link className="btn-primary mt-6" href={`/topic/${skill.id}`}>Return to skill</Link></div></main></RoleGuard>;
  const submit = () => { const score = gate.filter((q) => answers[q.id]?.trim().toLowerCase() === q.correctAnswer.trim().toLowerCase()).length; setResult(score); updateProgress(skill.id, { gateScore: score, status: score >= skill.gateThreshold ? "complete" : "review" }); };
  return <RoleGuard role="student"><main className="min-h-screen bg-[#fafaf8]"><header className="border-b border-[#dfe3e7] bg-white"><div className="mx-auto flex h-[68px] max-w-[960px] items-center px-5"><Link href={`/topic/${skill.id}`} className="flex items-center gap-2 text-xs font-bold text-[#677386]"><ArrowLeft size={14}/>Exit gate</Link></div></header><div className="mx-auto max-w-[860px] px-5 py-10">{result === null ? <><div className="mb-8 border-b-2 border-[#10233f] pb-5"><p className="label text-[#677386]">{skill.code} Skill Gate</p><h1 className="academic-heading mt-2 text-4xl">Show mastery across the whole skill.</h1><p className="mt-3 text-sm text-[#677386]">Answer all {gate.length}. A score of {skill.gateThreshold}/{skill.gateQuestionCount} unlocks Live Challenge.</p></div><div className="space-y-10">{gate.map((question, qi) => <section key={question.id}><p className="mb-2 text-xs text-[#677386]">{question.frameworkTarget}</p><div className="mb-4 flex gap-4"><span className="font-serif text-2xl text-[#8a939f]">{qi + 1}</span><h2 className="text-lg font-bold leading-7">{question.prompt}</h2></div><div className="ml-10 grid gap-2 sm:grid-cols-2">{question.choices?.map((choice, i) => <label key={choice} className={`flex cursor-pointer items-center gap-3 border px-3 py-3 text-sm ${answers[question.id] === choice ? "border-[#17365f] bg-[#f2f5f8]" : "border-[#dfe3e7] bg-white"}`}><input type="radio" name={question.id} checked={answers[question.id] === choice} onChange={() => setAnswers((old) => ({ ...old, [question.id]: choice }))}/><b>{String.fromCharCode(65 + i)}</b>{choice}</label>)}</div></section>)}</div><div className="mt-10 flex justify-end border-t border-[#dfe3e7] pt-6"><button className="btn-primary" disabled={Object.keys(answers).length < gate.length} onClick={submit}>Submit Skill Gate</button></div></> : <div className="border-y-2 border-[#10233f] py-14 text-center"><p className="label text-[#677386]">Skill Gate result</p><div className="mt-4 font-serif text-7xl">{result} <span className="text-3xl text-[#8a939f]">/ {skill.gateQuestionCount}</span></div><h1 className="academic-heading mt-5 text-4xl">{result >= skill.gateThreshold ? "Skill Cleared" : "Review Required"}</h1><p className="mx-auto mt-4 max-w-lg text-sm leading-6 text-[#677386]">{result >= skill.gateThreshold ? "Live Challenge is unlocked as a separate hard-question lesson." : "Review the unit sequence, then return when you are ready."}</p><div className="mt-8 flex justify-center gap-3"><Link className="btn-secondary" href={`/topic/${skill.id}`}>Skill overview</Link>{result >= skill.gateThreshold && <Link className="btn-primary" href={`/topic/${skill.id}/challenge`}>Live Challenge <ArrowRight size={16}/></Link>}</div></div>}</div></main></RoleGuard>;
}
