/** Narrow SAT-aligned generation targets keyed by internal drill-unit code. */
export const frameworkTargetsByUnit: Record<string, readonly string[]> = {
  A1a: [
    "solve a one-step linear equation using inverse operations",
    "solve a multistep linear equation by distributing and combining like terms",
    "solve a linear equation with the variable on both sides",
    "solve a linear equation containing fractions or decimals",
  ],
  A1b: [
    "use a common factor or grouped expression to simplify a linear equation",
    "recognize equivalent forms of a linear equation before solving",
    "isolate a repeated expression as a single quantity",
    "choose an efficient sequence of algebraic operations for a linear equation",
  ],
  A1c: [
    "determine whether a linear equation has one solution, no solution, or infinitely many solutions",
    "identify a parameter value that produces no solution",
    "identify a parameter value that produces infinitely many solutions",
    "justify the number of solutions after simplifying both sides of an equation",
  ],
  A1d: [
    "translate a one-variable verbal relationship into a linear equation",
    "create a linear equation from a fixed fee and a variable rate",
    "create and solve a linear equation for an unknown amount in context",
    "select the linear equation that represents a stated constraint",
  ],
  A1e: [
    "interpret a variable in a one-variable linear equation in context",
    "interpret a coefficient or constant in a one-variable linear equation",
    "interpret the solution of a linear equation with its correct units",
    "explain the meaning of a term or factor in a contextual equation",
  ],
  A2a: [
    "find one variable value in a two-variable linear equation when the other value is given",
    "determine whether an ordered pair satisfies a two-variable linear equation",
    "find a missing coordinate of a point on a line",
    "interpret an ordered-pair solution in context",
  ],
  A2b: [
    "complete a table of values for a two-variable linear equation",
    "select the graph that represents a given linear equation",
    "select the equation represented by a linear table or graph",
    "connect the intercepts of a line across equation, table, and graph representations",
  ],
  A2c: [
    "calculate slope from two points",
    "calculate slope from a table or graph",
    "identify slope and intercept from a linear equation",
    "rewrite a linear equation to reveal its slope and intercept",
    "interpret the sign and magnitude of a line's slope",
  ],
  A2d: [
    "write a line from its slope and y-intercept",
    "write a line from one point and its slope",
    "write a line through two given points",
    "write a line represented by a graph or table",
  ],
  A2e: [
    "determine the slope of a line parallel to a given line",
    "determine the slope of a line perpendicular to a given line",
    "write an equation of a parallel line through a given point",
    "write an equation of a perpendicular line through a given point",
  ],
  A2f: [
    "create a two-variable linear equation from a contextual relationship",
    "interpret slope as a rate in a two-variable context",
    "interpret an intercept in a two-variable context",
    "use a two-variable equation to determine a requested contextual value",
    "interpret a point on a contextual line",
  ],
  A3a: [
    "evaluate a linear function for a given input",
    "find an input that produces a specified output of a linear function",
    "interpret an ordered input-output pair for a linear function",
    "translate between function notation and an equation in two variables",
  ],
  A3b: [
    "determine the rate of change of a linear function from a table, graph, or equation",
    "determine the initial value of a linear function from a table, graph, or equation",
    "interpret a linear rate of change in context",
    "interpret a linear function's initial value in context",
  ],
  A3c: [
    "match a linear function equation to its table",
    "match a linear function equation to its graph",
    "determine a missing table value using a linear pattern",
    "compare two linear functions given in different representations",
  ],
  A3d: [
    "create a linear function from a constant rate and initial value",
    "create a linear function from two input-output pairs",
    "create a linear function from a contextual relationship",
    "select the linear function that models a stated situation",
  ],
  A3e: [
    "interpret the input and output variables of a linear function in context",
    "interpret a coefficient or constant in a contextual linear function",
    "interpret a point or intercept on a contextual linear-function graph",
    "use a linear function to make an in-range prediction",
  ],
  A4a: [
    "solve a system of two linear equations by direct substitution",
    "rearrange one equation before using substitution",
    "use substitution when one variable or expression is already isolated",
    "verify a system solution in both equations",
  ],
  A4b: [
    "solve a system by adding or subtracting equations to eliminate a variable",
    "multiply one equation before elimination",
    "multiply both equations before elimination",
    "choose an efficient variable to eliminate",
  ],
  A4c: [
    "identify a system solution as the intersection of two lines",
    "connect an algebraic system solution to its graph",
    "estimate a system solution from a graph",
    "determine an unknown coefficient using a given system solution",
  ],
  A4d: [
    "determine whether a linear system has one solution, no solution, or infinitely many solutions",
    "identify a parameter value that makes two lines parallel",
    "identify a parameter value that makes two equations equivalent",
    "connect slopes and intercepts to the number of system solutions",
  ],
  A4e: [
    "create a system of two linear equations from a context",
    "solve a contextual system and identify the requested quantity",
    "interpret the intersection of two contextual linear models",
    "select the system that represents two contextual constraints",
  ],
  A5a: [
    "solve a one-step linear inequality",
    "solve a multistep linear inequality",
    "reverse the inequality sign when multiplying or dividing by a negative number",
    "represent a one-variable inequality solution on a number line",
    "interpret an inequality solution in context",
  ],
  A5b: [
    "determine whether a point satisfies a two-variable linear inequality",
    "identify the boundary line of a two-variable linear inequality",
    "determine which side of a boundary line satisfies an inequality",
    "write a two-variable linear inequality from a stated constraint",
  ],
  A5c: [
    "match a linear inequality to its graph",
    "match a shaded region to its linear inequality",
    "use a table to test solutions of a linear inequality",
    "distinguish solid and dashed boundary lines from inequality symbols",
  ],
  A5d: [
    "determine whether a point satisfies a system of linear inequalities",
    "identify the overlapping solution region of two linear inequalities",
    "match a system of inequalities to its graph",
    "write a system of inequalities for multiple constraints",
  ],
  A5e: [
    "create a one-variable inequality from a contextual constraint",
    "create a two-variable inequality from a contextual constraint",
    "interpret a boundary value or solution region in context",
    "identify a feasible contextual solution to one or more inequalities",
  ],
  AM1a: [
    "add or subtract polynomial expressions",
    "multiply a monomial by a polynomial",
    "multiply two binomials or other low-degree polynomials",
    "combine like terms and distribute to produce an equivalent polynomial expression",
  ],
  AM1b: [
    "factor the greatest common numerical factor from a polynomial",
    "factor a common variable factor from a polynomial",
    "factor a common monomial from a polynomial expression",
    "use common-factor factoring to reveal an equivalent form",
  ],
  AM1c: [
    "factor a difference of two squares",
    "factor a monic quadratic trinomial",
    "factor a nonmonic quadratic trinomial",
    "recognize a quadratic expression from its factored form",
  ],
  AM1d: [
    "factor a polynomial by grouping",
    "factor a polynomial after first removing a common factor",
    "factor a polynomial after rearranging terms to reveal common structure",
    "select a factored form that exposes specified zeros or factors",
  ],
  AM1e: [
    "cancel common polynomial factors in a rational expression while retaining domain restrictions",
    "combine simple rational expressions with a common denominator",
    "rewrite a rational expression by factoring its numerator or denominator",
    "identify an equivalent form of a simple rational expression",
  ],
  AM1f: [
    "rewrite a rational exponent in radical form",
    "rewrite a radical in rational-exponent form",
    "apply exponent rules to expressions with rational exponents",
    "simplify an expression involving compatible radicals or rational exponents",
  ],
  AM1g: [
    "choose an equivalent form that reveals zeros",
    "choose an equivalent form that reveals a constant term or coefficient",
    "choose an equivalent form that makes evaluation efficient",
    "use a given equivalent-expression condition to determine an unknown coefficient",
  ],
  AM2a: [
    "solve a quadratic equation by factoring",
    "use the zero-product property with a factored quadratic",
    "rewrite a quadratic to expose a factorable structure before solving",
    "solve a quadratic-like equation by treating a repeated expression as one quantity",
  ],
  AM2b: [
    "solve a quadratic equation of the form x² = c",
    "isolate a squared expression before taking square roots",
    "account for both positive and negative square-root solutions",
    "solve a translated squared-expression equation using square-root structure",
  ],
  AM2c: [
    "identify coefficients a, b, and c for use in the quadratic formula",
    "solve a quadratic equation using the quadratic formula",
    "use the quadratic formula when factoring is impractical",
    "interpret an exact or approximate solution produced by the quadratic formula",
  ],
  AM2d: [
    "complete the square for a monic quadratic expression",
    "complete the square when the leading coefficient is not 1",
    "solve a quadratic equation by completing the square",
    "rewrite a quadratic equation in vertex form by completing the square",
  ],
  AM2e: [
    "use the discriminant to determine the number of real quadratic solutions",
    "determine a parameter value that gives exactly one real solution",
    "determine a parameter range that gives two or no real solutions",
    "connect x-intercepts of a quadratic graph to the number of real solutions",
  ],
  AM2f: [
    "solve an equation of the form |ax + b| = c",
    "write and solve the two linear cases of an absolute-value equation",
    "recognize when a linear absolute-value equation has no solution",
    "verify candidate solutions of an absolute-value equation",
  ],
  AM2g: [
    "isolate a square root before solving a radical equation",
    "solve a simple radical equation by squaring both sides",
    "check for an extraneous solution after squaring",
    "determine a parameter or missing value in a simple radical equation",
  ],
  AM2h: [
    "solve a simple rational equation by clearing denominators",
    "state excluded values before solving a rational equation",
    "check a candidate solution against denominator restrictions",
    "solve a rational equation arising from a simple rate relationship",
  ],
  AM2i: [
    "solve a polynomial equation already written as a product of factors",
    "apply the zero-product property to three or more factors",
    "identify all real zeros from a factored polynomial equation",
    "determine an unknown factor or parameter from a stated polynomial solution",
  ],
  AM2j: [
    "solve a system containing one linear and one quadratic equation by substitution",
    "identify intersection points of a line and a parabola",
    "determine the number of solutions to a linear-nonlinear system",
    "solve a contextual problem modeled by one linear and one nonlinear equation",
  ],
  AM2k: [
    "isolate a specified variable in a multivariable linear equation",
    "rearrange a formula containing products or quotients",
    "rearrange a formula containing a squared variable or square root",
    "use a rearranged formula to evaluate a requested quantity",
  ],
  AM3a: [
    "evaluate a nonlinear function for a given input",
    "find an input that produces a specified nonlinear-function output",
    "interpret an input-output pair for a nonlinear function",
    "evaluate a nonlinear function given by a table, graph, or formula",
  ],
  AM3b: [
    "identify zeros or x-intercepts of a quadratic function",
    "identify the y-intercept of a quadratic function",
    "identify the vertex and axis of symmetry of a parabola",
    "determine a quadratic function's maximum or minimum value",
    "interpret a quadratic key feature in context",
  ],
  AM3c: [
    "match a quadratic equation to its graph or table",
    "choose factored form to reveal zeros of a quadratic",
    "choose vertex form to reveal a quadratic's vertex",
    "interpret a horizontal or vertical translation of a quadratic graph",
    "determine how a coefficient changes a parabola's opening or width",
  ],
  AM3d: [
    "distinguish exponential growth from exponential decay",
    "determine an exponential growth or decay factor from a percent rate",
    "evaluate an exponential model at a given input",
    "interpret repeated multiplicative change in context",
  ],
  AM3e: [
    "match an exponential equation to its graph or table",
    "identify the initial value and growth factor of an exponential function",
    "interpret a horizontal or vertical translation of an exponential graph",
    "compare equivalent forms of an exponential function with different time intervals",
  ],
  AM3f: [
    "identify zeros and intercepts of a polynomial function from its equation or graph",
    "determine polynomial end behavior from a graph in an SAT-level context",
    "evaluate a polynomial function for a given input",
    "connect repeated factors to a polynomial graph touching or crossing the x-axis",
  ],
  AM3g: [
    "identify the domain restriction of a simple rational function",
    "identify a vertical or horizontal asymptote from a simple rational equation or graph",
    "evaluate a simple rational function",
    "interpret how a parameter changes a simple rational-function graph",
  ],
  AM3h: [
    "evaluate a radical or other explicitly defined nonlinear function",
    "identify the domain of a square-root function",
    "match a radical function to its graph",
    "interpret a transformation of a square-root or other simple nonlinear graph",
  ],
  AM3i: [
    "match a nonlinear table, equation, and graph",
    "identify a nonlinear function type from its pattern of change",
    "compare key features of two nonlinear functions in different representations",
    "use one representation to determine a missing feature in another representation",
  ],
  AM3j: [
    "select a quadratic model for data with approximately constant second differences",
    "select an exponential model for data with an approximately constant ratio",
    "create a quadratic model from stated zeros and one additional condition",
    "create an exponential model from an initial value and growth or decay factor",
    "choose between quadratic and exponential models for a context",
  ],
  AM3k: [
    "interpret a zero, intercept, vertex, maximum, or minimum in context",
    "interpret a parameter in a quadratic or exponential model",
    "choose a function form that reveals the requested key feature",
    "interpret an interval where a nonlinear function increases or decreases",
    "use a nonlinear graph's key features to answer a contextual question",
  ],
  P1a: [
    "simplify or compare two ratios",
    "find a missing value in a proportional relationship",
    "use a ratio to partition a total into parts",
    "determine whether two quantities are proportional",
  ],
  P1b: [
    "calculate a unit rate from two quantities",
    "use a unit rate to determine an unknown quantity",
    "compare rates expressed with the same units",
    "interpret a rate and its units in context",
  ],
  P1c: [
    "solve a multistep proportional relationship in context",
    "use a drawing scale to determine an actual length",
    "use an actual length to determine a drawing length",
    "determine or use the scale of a map or diagram",
  ],
  P1d: [
    "convert a measurement using one stated conversion factor",
    "choose the correct orientation of a conversion factor",
    "convert between units within the same measurement system",
    "retain and interpret units during a one-step conversion",
  ],
  P1e: [
    "perform a conversion requiring two or more conversion factors",
    "convert a squared unit such as area",
    "convert a cubed unit such as volume",
    "convert a rate containing units in both numerator and denominator",
  ],
  P1f: [
    "compute a quantity with derived units formed by multiplication",
    "compute a quantity with derived units formed by division",
    "determine the units of a product or quotient of measured quantities",
    "interpret a derived unit such as density, speed, or cost per unit",
  ],
  P1g: [
    "use a linear scale factor in a proportional relationship",
    "determine a scale factor from corresponding quantities",
    "apply the same proportional scale factor to another quantity",
    "distinguish a proportional scale factor from an additive change",
  ],
  P2a: [
    "find a percentage of a given amount",
    "find what percent one quantity is of another",
    "convert among percent, decimal, and fraction forms",
    "work with percentages greater than 100 percent or less than 1 percent",
  ],
  P2b: [
    "find an original amount given a percentage of it",
    "find an original amount after a stated percent increase",
    "find an original amount after a stated percent decrease",
    "distinguish the original base from the resulting amount",
  ],
  P2c: [
    "calculate a percent increase from original and new values",
    "calculate a percent decrease from original and new values",
    "determine a new value after a percent increase or decrease",
    "compare an absolute change with a percent change",
  ],
  P2d: [
    "convert a percent increase to a multiplicative growth factor",
    "convert a percent decrease to a multiplicative decay factor",
    "determine percent change from a growth or decay factor",
    "apply a growth factor over one or more equal intervals",
  ],
  P2e: [
    "calculate tax, tip, markup, or discount",
    "determine a final price after multiple percentage adjustments",
    "calculate simple interest or another SAT-level percent application",
    "model repeated percentage change with multiplication",
    "interpret which amount serves as the percent base in context",
  ],
  P3a: [
    "read a frequency from a one-variable frequency table",
    "determine a total frequency or missing frequency",
    "calculate a relative frequency from a frequency table",
    "use a frequency table to compare categories or values",
  ],
  P3b: [
    "identify the number of observations represented by a histogram or dot plot",
    "estimate or compare center from histograms or dot plots",
    "compare spread from histograms or dot plots",
    "identify clusters, gaps, skew, or outliers in a displayed distribution",
  ],
  P3c: [
    "read the minimum, quartiles, median, and maximum from a box plot",
    "calculate or compare interquartile ranges from box plots",
    "compare centers and spreads of two box plots",
    "interpret what a box-plot interval represents about a distribution",
  ],
  P3d: [
    "calculate the mean of a small data set",
    "calculate the median of a data set",
    "calculate the range of a data set",
    "determine a missing data value from a stated mean",
    "choose an appropriate measure of center for a displayed distribution",
  ],
  P3e: [
    "determine how adding or removing an outlier changes the mean",
    "determine how adding or removing an outlier changes the median",
    "determine how an outlier changes the range or interquartile range",
    "compare the sensitivity of mean and median to an extreme value",
  ],
  P3f: [
    "compare two distributions using their centers",
    "compare two distributions using range or interquartile range",
    "interpret a larger standard deviation as greater spread",
    "compare standard deviations from graphs or summary statistics without hand calculation",
    "recognize that shifting every value changes center but not standard deviation",
  ],
  P4a: [
    "describe the direction of association in a scatterplot",
    "describe the strength of association in a scatterplot",
    "identify an outlier or cluster in a scatterplot",
    "distinguish linear from nonlinear association",
  ],
  P4b: [
    "use a line or curve of best fit to make an interpolation",
    "use a fitted model to make an extrapolation and recognize its limitation",
    "estimate a response value from a scatterplot",
    "interpret a residual as actual value minus predicted value",
  ],
  P4c: [
    "select a reasonable line of best fit for a scatterplot",
    "estimate slope and intercept of a fitted linear model",
    "interpret slope of a fitted linear model in context",
    "interpret the intercept of a fitted linear model when meaningful",
    "use a linear model to predict a value",
  ],
  P4d: [
    "select a quadratic model for curved data with a turning point",
    "select an exponential model for data with multiplicative growth or decay",
    "use a fitted quadratic model to predict or interpret a value",
    "use a fitted exponential model to predict or interpret a value",
    "compare model fit using the pattern shown in data or residuals",
  ],
  P4e: [
    "interpret a point on a graph relating two contextual quantities",
    "interpret an intercept on a graph relating two contextual quantities",
    "interpret increasing, decreasing, or constant portions of a contextual graph",
    "identify a maximum, minimum, or change in rate from a contextual graph",
  ],
  P4f: [
    "distinguish constant additive growth from constant multiplicative growth",
    "compare linear and exponential models over a stated interval",
    "identify when an exponential quantity overtakes a linear quantity",
    "interpret differences in long-term behavior of linear and exponential growth",
  ],
  P5a: [
    "calculate a relative frequency from a one-way table",
    "calculate a joint or marginal relative frequency from a two-way table",
    "interpret frequencies represented by a table, tree, or area model",
    "complete a data representation using given frequencies or totals",
  ],
  P5b: [
    "calculate probability as favorable outcomes divided by total outcomes",
    "calculate the probability of a complementary event",
    "use equally likely outcomes to determine a probability",
    "compare probabilities expressed as fractions, decimals, or percentages",
  ],
  P5c: [
    "calculate conditional probability from a two-way table",
    "identify the correct restricted denominator for a conditional probability",
    "compare a conditional probability with an overall probability",
    "determine whether two events appear independent from provided probabilities",
  ],
  P5d: [
    "interpret a probability as a long-run relative frequency",
    "use an experimental probability to predict an expected count",
    "compare theoretical and observed probability in context",
    "interpret the meaning of a conditional probability statement",
  ],
  P5e: [
    "find a missing frequency from a stated probability and total",
    "find a missing cell in a two-way table using a conditional probability",
    "find a missing favorable-outcome count from a relative frequency",
    "check a recovered frequency against row, column, or grand totals",
  ],
  P6a: [
    "use a sample mean as an estimate of a population mean",
    "identify the population parameter estimated by a sample mean",
    "compare sample-mean estimates from representative samples",
    "interpret sampling variability in estimates of a population mean",
  ],
  P6b: [
    "use a sample proportion as an estimate of a population proportion",
    "convert a sample proportion into an estimated population count",
    "identify the population parameter estimated by a sample proportion",
    "interpret sampling variability in estimates of a population proportion",
  ],
  P6c: [
    "interpret a reported estimate together with its margin of error",
    "construct an interval estimate from an estimate and margin of error",
    "compare the precision of estimates using their margins of error",
    "determine whether a claimed population value is plausible within a stated margin of error",
  ],
  P6d: [
    "explain that a larger random sample generally produces a smaller margin of error",
    "compare likely margins of error for studies with different sample sizes",
    "identify a sample-size change that would improve precision",
    "distinguish the effect of sample size on precision from bias in sampling",
  ],
  P7a: [
    "identify the population to which a random sample can reasonably generalize",
    "determine whether a sampling process is random",
    "explain why random sampling supports population generalization",
    "distinguish a sample from its target population",
  ],
  P7b: [
    "identify convenience, voluntary-response, or other biased sampling",
    "identify undercoverage or nonresponse as a sampling limitation",
    "explain how a sampling method can bias an estimate",
    "select a more representative sampling method for a stated population",
  ],
  P7c: [
    "distinguish an observational study from a controlled experiment",
    "identify explanatory and response variables in a study",
    "recognize when researchers impose a treatment",
    "determine which conclusions are supported by an observational study versus an experiment",
  ],
  P7d: [
    "determine whether subjects were randomly assigned to treatments",
    "explain how random assignment supports a causal conclusion",
    "distinguish random assignment from random sampling",
    "decide whether a study supports causation, generalization, both, or neither",
  ],
  G1a: [
    "calculate the perimeter of a polygon from given side lengths",
    "calculate the area of a rectangle, triangle, parallelogram, or trapezoid",
    "calculate the area or circumference of a circle",
    "determine the area of a composite two-dimensional figure",
    "select and apply an area or perimeter formula in context",
  ],
  G1b: [
    "calculate the surface area of a rectangular prism",
    "calculate the surface area of a cylinder",
    "calculate the surface area of a pyramid, cone, or other SAT-provided solid",
    "determine a missing measure from a given surface area",
    "select and apply a surface-area formula in context",
  ],
  G1c: [
    "calculate the volume of a rectangular prism",
    "calculate the volume of a cylinder",
    "calculate the volume of a pyramid or cone",
    "calculate the volume of a sphere",
    "select and apply a volume formula in context",
  ],
  G1d: [
    "determine a missing side length from a given perimeter",
    "determine a missing base, height, or radius from a given area",
    "determine a missing dimension from a given surface area",
    "determine a missing dimension from a given volume",
    "interpret a recovered geometric measure with correct units",
  ],
  G1e: [
    "determine a new length using linear scale factor k",
    "determine linear scale factor k from corresponding lengths",
    "determine a new area using area scale factor k²",
    "determine area scale factor from linear scale factor k",
    "determine a new volume using volume scale factor k³",
    "determine volume scale factor from linear scale factor k",
    "work backward from an area or volume scale factor to a positive linear scale factor when appropriate",
  ],
  G1f: [
    "select the correct perimeter, area, surface-area, or volume formula for a stated quantity",
    "distinguish linear, square, and cubic units in a mixed-measurement problem",
    "combine two geometric formulas to determine a requested measure",
    "compare two figures using more than one type of measurement",
    "apply a provided SAT reference-sheet formula to a contextual figure",
  ],
  G2a: [
    "use vertical angles to determine an unknown angle measure",
    "use a linear pair or supplementary angles to determine an unknown angle",
    "use complementary angles to determine an unknown angle",
    "translate a stated angle relationship into a linear equation",
  ],
  G2b: [
    "use the triangle angle-sum theorem to determine an unknown interior angle",
    "use an exterior-angle relationship to determine an unknown angle",
    "determine an angle in an isosceles or equilateral triangle",
    "create and solve a linear equation from triangle angle expressions",
  ],
  G2c: [
    "use corresponding angles formed by parallel lines and a transversal",
    "use alternate interior or alternate exterior angles",
    "use same-side interior supplementary angles",
    "determine whether two lines are parallel from stated angle relationships",
  ],
  G2d: [
    "establish triangle similarity using angle-angle reasoning",
    "use corresponding sides of similar triangles to form a proportion",
    "determine a missing side length in similar triangles",
    "identify corresponding vertices or sides in similar triangles",
  ],
  G2e: [
    "establish triangle congruence from sufficient side and angle information",
    "use corresponding parts of congruent triangles to determine a missing measure",
    "distinguish congruence from similarity",
    "identify a rigid transformation or condition that preserves congruence",
  ],
  G2f: [
    "determine a linear scale factor between similar figures",
    "use a scale factor to determine a corresponding side length",
    "work backward from corresponding sides to find a scale factor",
    "recognize that corresponding angles remain equal under similarity",
  ],
  G2g: [
    "identify information sufficient to prove two triangles similar",
    "identify information sufficient to prove two triangles congruent",
    "select a theorem that justifies an angle or side relationship",
    "determine whether an additional geometric statement is sufficient to reach a conclusion",
  ],
  G3a: [
    "determine the hypotenuse of a right triangle using the Pythagorean theorem",
    "determine a missing leg of a right triangle using the Pythagorean theorem",
    "determine whether three side lengths form a right triangle",
    "apply the Pythagorean theorem in a coordinate or contextual problem",
  ],
  G3b: [
    "determine the hypotenuse from a leg in a 45-45-90 triangle",
    "determine a leg from the hypotenuse in a 45-45-90 triangle",
    "recognize the 1:1:√2 side ratio",
    "apply a 45-45-90 relationship in a geometric context",
  ],
  G3c: [
    "determine the hypotenuse from the short leg in a 30-60-90 triangle",
    "determine the long leg from the short leg in a 30-60-90 triangle",
    "determine a leg from the hypotenuse in a 30-60-90 triangle",
    "recognize the 1:√3:2 side ratio",
    "apply a 30-60-90 relationship in a geometric context",
  ],
  G3d: [
    "select sine, cosine, or tangent for a right-triangle side relationship",
    "determine a missing side using a trigonometric ratio",
    "determine an acute angle using an inverse trigonometric ratio",
    "interpret opposite, adjacent, and hypotenuse relative to a reference angle",
  ],
  G3e: [
    "use similar right triangles to show a trigonometric ratio is constant",
    "determine sine, cosine, or tangent from proportional side lengths",
    "transfer a trigonometric ratio between similar right triangles",
    "determine a missing side using similarity and a trigonometric ratio",
  ],
  G3f: [
    "use sin(θ) = cos(90° − θ) for complementary acute angles",
    "use cos(θ) = sin(90° − θ) for complementary acute angles",
    "identify complementary angles in a right triangle",
    "rewrite a sine expression as the cosine of a complementary angle or vice versa",
  ],
  G3g: [
    "model a height or distance with a right triangle",
    "use an angle of elevation or depression to determine a length",
    "combine the Pythagorean theorem with a contextual right-triangle relationship",
    "choose an appropriate special-triangle or trigonometric method in context",
    "interpret a computed right-triangle measure with correct units",
  ],
  G4a: [
    "determine radius from diameter or diameter from radius",
    "calculate circumference from radius or diameter",
    "calculate circle area from radius or diameter",
    "use a basic circle relationship to determine a missing measure",
  ],
  G4b: [
    "calculate arc length from radius and central angle in degrees",
    "calculate sector area from radius and central angle in degrees",
    "determine a central angle from an arc length or sector area",
    "compare an arc or sector with the corresponding fraction of a circle",
  ],
  G4c: [
    "determine an inscribed angle from its intercepted arc",
    "determine an arc measure from a central or inscribed angle",
    "use the fact that a radius is perpendicular to a tangent at the point of tangency",
    "use equal tangent segments from a common external point",
    "combine circle-angle and tangent relationships in one diagram",
  ],
  G4d: [
    "convert an angle measure from degrees to radians",
    "convert an angle measure from radians to degrees",
    "determine radian measure as arc length divided by radius",
    "calculate arc length using s = rθ when θ is in radians",
  ],
  G4e: [
    "identify cosine and sine as the x- and y-coordinates of a unit-circle point",
    "determine sine or cosine for a standard unit-circle angle",
    "use quadrant signs to determine the sign of a trigonometric ratio",
    "use symmetry or a reference angle to relate unit-circle values",
  ],
  G4f: [
    "identify center and radius from a circle equation in standard form",
    "write a circle equation from its center and radius",
    "write a circle equation from a center and a point on the circle",
    "determine an unknown parameter in a circle equation from a stated point or radius",
  ],
  G4g: [
    "match a circle equation in standard form to its graph",
    "determine how changing the center parameters translates a circle",
    "determine how changing the radius changes a circle's graph",
    "write the equation of a translated or resized circle",
  ],
  G4h: [
    "complete the square in x to rewrite part of a circle equation",
    "complete the square in both x and y to obtain standard circle form",
    "identify center and radius after completing the square",
    "determine whether a general-form equation represents a real circle",
  ],
  G4i: [
    "use the distance formula to verify that a point lies on a circle",
    "determine a circle's radius from its center and a point",
    "determine a missing coordinate of a point on a circle",
    "combine the distance formula with a circle equation in a coordinate-plane problem",
  ],
};

export const frameworkTargetCodes = Object.keys(frameworkTargetsByUnit);
