const q = (stem, correct, wrong1, wrong2, wrong3) => ({
  stem,
  options: [correct, wrong1, wrong2, ...(wrong3 ? [wrong3] : [])],
  answer: 0,
});

const listen = (task, topic, transcript, qs) => ({
  task, topic, intro: "You will hear the recording only once.", transcript, qs,
});

const read = (task, topic, passage, qs, scene) => ({
  task, topic, passage,
  qs: qs.map((item) => item.options.length === 4 ? item : ({
    ...item,
    options: [...item.options, "The passage does not support this answer"],
  })),
  ...(scene ? { scene } : {}),
});

const speak = (task, topic, prompt, points, checks, scene) => ({
  task, topic, prompt, points, checks, ...(scene ? { scene } : {}),
});

const write = (task, topic, stem, points, hint, scene, minWords = 0) => ({
  task, topic, kind: "frame", stem, points, hint, minWords,
  ...(scene ? { scene } : {}),
});

const shortExchange = (topic, transcript, stem, correct, wrong1, wrong2) =>
  listen("Listen to a Short Exchange", topic, transcript, [q(stem, correct, wrong1, wrong2)]);

const longQuestions = (topic, details, count, advanced = false) => {
  const items = [
    q(`What is the main idea of the presentation about ${topic}?`, details.main,
      details.wrongMain1, details.wrongMain2),
    q(details.detailStem, details.detail, details.wrongDetail1, details.wrongDetail2),
    q(details.reasonStem, details.reason, details.wrongReason1, details.wrongReason2),
    q(advanced ? "Which conclusion is best supported by the speaker's evidence?" : "What can the listener understand from the presentation?",
      details.inference, details.wrongInference1, details.wrongInference2),
  ];
  return items.slice(0, count);
};

const readingQuestions = (topic, details, count, elementary = false) => {
  const items = [
    q(elementary ? `What is the passage mostly about?` : `What is the central idea of “${topic}”?`,
      details.main, details.wrongMain1, details.wrongMain2, details.wrongMain3),
    q(details.detailStem, details.detail, details.wrongDetail1, details.wrongDetail2, details.wrongDetail3),
    q(details.reasonStem, details.reason, details.wrongReason1, details.wrongReason2, details.wrongReason3),
    q(elementary ? "What can the reader figure out?" : "Which inference is best supported by the passage?",
      details.inference, details.wrongInference1, details.wrongInference2, details.wrongInference3),
    q("How is the passage mainly organized?", details.structure,
      "As unrelated facts with no connection", "As a list of characters in alphabetical order", "As questions with no answers"),
    q("Why does the author include a specific example?", details.examplePurpose,
      "To change to an unrelated topic", "To make the passage fictional", "To hide the main idea"),
    q(`What does “${details.word}” most nearly mean as used in the passage?`, details.meaning,
      details.wrongMeaning1, details.wrongMeaning2, details.wrongMeaning3),
    q("Which detail best supports the passage's main idea?", details.evidence,
      details.wrongEvidence1, details.wrongEvidence2, details.wrongEvidence3),
  ];
  return items.slice(0, count);
};

const makeListening = (span, cfg) => {
  const blocks = [
    ...cfg.exchanges.map((item) => shortExchange(...item)),
    listen("Listen to a Classroom Conversation", cfg.classroom.topic, cfg.classroom.transcript, cfg.classroom.qs),
  ];
  if (span === "g35") {
    cfg.stories.forEach((item) => blocks.push(listen("Listen to a Story", item.topic, item.transcript, item.qs)));
    cfg.orals.forEach((item) => blocks.push(listen("Listen to an Oral Presentation", item.topic, item.transcript,
      longQuestions(item.topic, item.details, 4))));
  } else {
    const rawCount = span === "g910" ? 3 : 4;
    cfg.orals.forEach((item) => blocks.push(listen("Listen to an Oral Presentation", item.topic, item.transcript,
      longQuestions(item.topic, item.details, rawCount, span !== "g68"))));
    cfg.opinions.forEach((item) => blocks.push(listen("Listen to a Speaker Support an Opinion", item.topic, item.transcript,
      longQuestions(item.topic, item.details, rawCount, span !== "g68"))));
  }
  return blocks;
};

const makeReading = (span, cfg) => {
  const elementary = span === "g35";
  const blocks = [];
  if (elementary) {
    cfg.pictureReads.forEach((item, index) => blocks.push(read("Read and Choose a Sentence", item.topic, "",
      [q("Choose the sentence that best describes the picture.", item.correct, item.wrong1, item.wrong2)], item.scene)));
  }
  const shortCount = span === "g910" ? [3, 4] : span === "g35" ? [3, 3] : span === "g68" ? [4, 4] : [3, 3];
  cfg.shorts.forEach((item, index) => blocks.push(read("Read a Short Informational Passage", item.topic, item.passage,
    readingQuestions(item.topic, item.details, shortCount[index], elementary))));
  const essayCount = span === "g1112" ? 8 : 6;
  blocks.push(read("Read a Student Essay", cfg.essay.topic, cfg.essay.passage,
    readingQuestions(cfg.essay.topic, cfg.essay.details, essayCount, elementary)));
  blocks.push(read("Read a Literary Passage", cfg.literary.topic, cfg.literary.passage,
    readingQuestions(cfg.literary.topic, cfg.literary.details, 6, elementary)));
  blocks.push(read("Read an Informational Passage", cfg.informational.topic, cfg.informational.passage,
    readingQuestions(cfg.informational.topic, cfg.informational.details, 6, elementary)));
  return blocks;
};

const makeSpeaking = (span, cfg) => {
  const sceneItems = [
    speak("Talk about a Scene (1 of 4)", cfg.sceneTopic, cfg.scenePrompts[0], 1, ["Relevant visible detail"], cfg.scene),
    speak("Talk about a Scene (2 of 4)", cfg.sceneTopic, cfg.scenePrompts[1], 1, ["Two connected details"], cfg.scene),
    speak("Talk about a Scene (3 of 4)", cfg.sceneTopic, cfg.scenePrompts[2], 2, ["Inference", "Visual evidence"], cfg.scene),
    speak("Talk about a Scene (4 of 4)", cfg.sceneTopic, cfg.scenePrompts[3], 2, ["Relevant experience", "Clear sequence"], cfg.scene),
  ];
  const functions = cfg.functions.map((item) => speak("Speech Functions", item[0], item[1], 2,
    ["Appropriate language", "Clear purpose"]));
  const opinions = cfg.speakingOpinions.map((item) => speak("Support an Opinion", item[0], item[1], 3,
    ["Clear position", "Developed reason"]));
  const summaries = cfg.summaries.map((item) => speak("Summarize an Academic Presentation", item.topic,
    item.prompt, 4, ["Main idea", "Important supporting details", "Own words"], item.scene));
  if (span === "g35") {
    return [...sceneItems, ...functions, ...opinions,
      speak("Retell a Narrative", cfg.retell.topic, cfg.retell.prompt, 4,
        ["Events in order", "Important details", "Clear ending"], cfg.retell.scene),
      ...summaries];
  }
  return [...sceneItems, ...functions, ...opinions, ...summaries];
};

const makeWriting = (span, cfg) => {
  const senior = span === "g910" || span === "g1112";
  return [
    write("Describe a Picture (Question 1)", cfg.sceneTopic, cfg.writing.picture1, 2,
      "Describe one visible action clearly.", cfg.scene, senior ? 12 : span === "g68" ? 8 : 5),
    write("Describe a Picture (Question 2)", cfg.sceneTopic, cfg.writing.picture2, 2,
      "Make a reasonable prediction and support it with a visible detail.", cfg.scene, senior ? 16 : span === "g68" ? 10 : 6),
    write("Write About an Experience", cfg.writing.experienceTopic, cfg.writing.experience, 4,
      cfg.writing.experienceHint, undefined, senior ? 45 : span === "g68" ? 30 : 20),
    write("Write About Academic Information (Question 4)", cfg.academicTopic, cfg.writing.academic1, 2,
      "Use accurate evidence from the graphic.", cfg.academicScene, senior ? 25 : span === "g68" ? 18 : 12),
    write("Write About Academic Information (Question 5)", cfg.academicTopic, cfg.writing.academic2, 3,
      "State a conclusion and support it with the graphic.", cfg.academicScene, senior ? 35 : span === "g68" ? 24 : 16),
    write("Justify an Opinion", cfg.writing.opinionTopic, cfg.writing.opinion, 4,
      senior ? "State a position, develop two reasons, and address a counterargument." : "State a position and explain two reasons.",
      undefined, senior ? 55 : span === "g68" ? 40 : 28),
  ];
};

const makeBank = (span, cfg) => ({
  listening: makeListening(span, cfg.listening),
  reading: makeReading(span, cfg.reading),
  speaking: makeSpeaking(span, cfg.speaking),
  writing: makeWriting(span, cfg.speaking),
});

const D = (main, detailStem, detail, reasonStem, reason, inference, structure, word, meaning, examplePurpose, evidence) => ({
  main, detailStem, detail, reasonStem, reason, inference, structure, word, meaning, examplePurpose, evidence,
  wrongMain1: "It focuses on an unrelated personal event", wrongMain2: "It argues that the topic has no importance", wrongMain3: "It lists names without explaining them",
  wrongDetail1: "The passage states the opposite", wrongDetail2: "That detail is never mentioned", wrongDetail3: "The passage gives no such number",
  wrongReason1: "The author gives no reason", wrongReason2: "It happens only by accident", wrongReason3: "It is caused by an unrelated event",
  wrongInference1: "The evidence supports the opposite conclusion", wrongInference2: "No conclusion can be drawn from any detail", wrongInference3: "The topic affects every situation in exactly the same way",
  wrongMeaning1: "to remove completely", wrongMeaning2: "to happen without a cause", wrongMeaning3: "to make less clear",
  wrongEvidence1: "A detail from a different topic", wrongEvidence2: "A claim the author rejects", wrongEvidence3: "An opinion not found in the passage",
});

const L = (main, detailStem, detail, reasonStem, reason, inference) => ({
  main, detailStem, detail, reasonStem, reason, inference,
  wrongMain1: "The speaker changes to an unrelated topic", wrongMain2: "The speaker says the process never works",
  wrongDetail1: "The speaker gives the opposite detail", wrongDetail2: "The speaker does not mention that action",
  wrongReason1: "There is no reason for the action", wrongReason2: "It is done only to save time",
  wrongInference1: "The evidence supports the opposite conclusion", wrongInference2: "The topic has no practical effect",
});

const classroom = (topic, transcript, a, b, c) => ({ topic, transcript, qs: [q(...a), q(...b), q(...c)] });

// Content is intentionally calibrated by band: concrete sequencing and direct
// evidence in grades 3–5, connected explanations in grades 6–8, analysis and
// counterargument in grades 9–10, and qualified evidence evaluation in 11–12.

const CONFIGS = {
  4: {
    g35: {
      listening: {
        exchanges: [
          ["Library Return", "Girl: I finished my library book, but the return box is locked. Boy: The librarian opens it after morning meeting. Keep the book in your backpack until then.", "What should the girl do?", "Keep the book until the box opens", "Leave it outside the box", "Take it home forever"],
          ["Paint Water", "Boy: Can I pour the dirty paint water into the sink? Girl: Ms. Lee said to use the gray bucket so the paint does not clog the drain.", "Where should the boy pour the water?", "Into the gray bucket", "Into the sink", "Onto the floor"],
          ["Field Day Hat", "Girl: The weather report says field day will be sunny. Boy: Then I will bring my hat and fill my water bottle tonight.", "Why will the boy bring a hat?", "Field day will be sunny", "The gym is cold", "His teacher lost one"],
        ],
        classroom: classroom("Seed Investigation", "Teacher: Each group has two cups of soil and four bean seeds. Put two seeds in each cup. Maya: Do both cups go by the window? Teacher: Only the cup marked Sun. Put the cup marked Dark in the cabinet. Luis: Do we water them today? Teacher: Yes, one spoonful in each cup. Then record what you notice every morning.",
          ["How many seeds go in each cup?", "Two", "One", "Four"], ["Where does the Dark cup go?", "In the cabinet", "By the window", "Outside"], ["What should students do each morning?", "Record what they notice", "Replace the seeds", "Empty the soil"]),
        stories: [
          { topic: "The Missing Seed Packet", transcript: "Nora's class was ready to plant a butterfly garden, but the milkweed seed packet was missing. Everyone searched the supply shelf. Nora remembered that the class had carried materials outside the day before. She looked under the garden cart and found the packet beside one wheel. The seeds were still dry inside. Her class planted them, added a small sign, and promised to return every tool before going indoors.", qs: [q("Where did Nora find the seeds?", "Under the garden cart", "Inside a desk", "Near the lunch tables"), q("What did the class promise?", "To return every tool", "To stop planting", "To move the garden indoors")] },
          { topic: "A Kite for Two", transcript: "Eli brought a new kite to the park, but there was almost no wind. His younger cousin waited with the string while Eli watched the trees. Soon the leaves began to move. Eli ran across the grass, and the kite rose above them. Instead of keeping the string, he handed it to his cousin and showed her how to let it out slowly. They took turns until the sun began to set.", qs: [q("Why did Eli wait before running?", "There was almost no wind", "The string was broken", "His cousin went home"), q("How did Eli help his cousin?", "He showed her how to use the string", "He hid the kite", "He carried her home")] },
        ],
        orals: [
          { topic: "Frog Life Cycle", transcript: "A frog begins life as an egg in water. A tadpole hatches from the egg and swims with a tail. As it grows, back legs and then front legs appear. Its lungs develop, and the tail becomes shorter. Finally, the young frog can leave the water and live on land as well as in ponds. The cycle begins again when adult frogs lay eggs.", details: L("A frog changes through several life stages", "What hatches from the egg?", "A tadpole", "Why can the young frog leave the water?", "Its legs and lungs develop", "Each stage prepares the frog for adult life") },
          { topic: "Simple Machines", transcript: "Simple machines help people move or lift things with less effort. A ramp lets a person roll a heavy box upward instead of lifting it straight up. A lever can lift a rock when someone pushes down on the other end. A wheel and axle helps a cart move. These tools do not remove work, but they can change the force or direction used.", details: L("Simple machines make work easier by changing force or direction", "What does a ramp help a person do?", "Move a box upward", "Why is a lever useful?", "Pushing one end can lift the other", "Different simple machines solve different movement problems") },
          { topic: "Animal Tracks", transcript: "Animals often leave signs even when people do not see them. A bird may leave three-toed prints in mud. A rabbit leaves two long back-foot prints ahead of smaller front prints. Deer leave split hoof marks. Scientists look at the size, shape, and spacing of tracks to identify the animal and learn whether it walked or ran.", details: L("Tracks provide clues about animals", "What do scientists examine?", "Track size, shape, and spacing", "Why are track patterns useful?", "They can show how an animal moved", "A careful observer can learn about an unseen animal") },
        ],
      },
      reading: {
        pictureReads: [
          { topic: "Community Cleanup", scene: "s4-35-read-community-cleanup", correct: "The children are putting litter into bags.", wrong1: "The children are taking a spelling test.", wrong2: "The playground is covered with snow." },
          { topic: "Lost Glove", scene: "s4-35-read-lost-glove", correct: "A girl is handing a blue glove to a teacher.", wrong1: "A girl is planting a tall tree.", wrong2: "The teacher is driving a bus." },
        ],
        shorts: [
          { topic: "How Owls Hunt", passage: "Owls hunt mostly at night. Their large eyes collect light, but their ears may be even more helpful. One ear opening is slightly higher than the other. A sound reaches each ear at a different moment, helping the owl tell exactly where it came from. Soft feathers also let an owl fly quietly. A mouse may not hear the owl until it is already very close.", details: D("Owls use special senses and feathers to hunt", "How are an owl's ear openings placed?", "One is slightly higher than the other", "Why are soft feathers helpful?", "They make flight quiet", "An owl can locate prey it cannot clearly see", "By describing several helpful features", "locate", "find the position of", "To show how one feature helps hunting", "Sound reaches the two ears at slightly different times") },
          { topic: "Why Bridges Have Triangles", passage: "Many bridges have metal beams that form triangles. A triangle keeps its shape when force pushes on it. A square can lean to one side unless another beam crosses it, but three connected sides make a triangle stiff. Bridge builders join many triangles into a truss. The truss spreads the weight of cars and people across several beams instead of placing it on one small part.", details: D("Triangles help bridges stay strong", "What is a group of joined triangles called?", "A truss", "Why does a truss spread weight?", "Several beams share the force", "A bridge with well-connected triangles can carry weight more safely", "As a comparison followed by an explanation", "stiff", "not easily bent", "To compare squares and triangles", "A triangle keeps its shape when pushed") },
        ],
        essay: { topic: "A Reading Cart at Recess", passage: "Our playground should have a reading cart during recess. Some students like running games, but others want a quiet choice. The cart could hold comics, short books, and magazines. Student helpers could roll it outside and bring it back after recess. Books might get lost, so each one should have a bright cart sticker. A teacher could count the books once a week. A reading cart would not replace play. It would simply give every student another good way to enjoy recess.", details: D("The writer supports a recess reading cart", "Who could move the cart?", "Student helpers", "Why should books have bright stickers?", "To help prevent them from getting lost", "The plan tries to solve a possible problem", "As a claim with reasons and a solution", "replace", "take the place of", "To explain how the cart would work", "The cart would give students a quiet choice") },
        literary: { topic: "The Map in the Book", passage: "Lena opened the old library book and a folded map slipped onto the floor. Someone had drawn a red star beside the school garden. At recess, Lena and Omar followed the map. The star led them to a flat stone under the pear tree. Beneath it was not treasure, but a small metal tag that read, 'Tree planted by Class 5, 1986.' They returned the tag to the librarian. She smiled and placed it in a display case beside a photograph of the students who had planted the tree.", details: D("Two students discover a piece of school history", "What was under the stone?", "A metal tree tag", "Why did the librarian display the tag?", "It connected the tree to an earlier class", "The map led to something valuable because of its history", "In chronological order", "display", "an arrangement meant to be seen", "To reveal why the tag mattered", "A photograph showed the class that planted the tree") },
        informational: { topic: "From Seed to Sunflower", passage: "A sunflower starts as a seed with a tiny plant inside. Water softens the seed coat, and the first root pushes downward. A small shoot grows upward toward light. Leaves open and begin making food for the plant. The stem becomes thick enough to hold a large flower head. After bees carry pollen between flowers, new seeds form in the center. Birds may eat some seeds, while others fall to the ground and may grow the next year. Sunlight and water help each stage continue.", details: D("A sunflower grows and makes new seeds", "What grows first?", "A root", "Why do leaves open?", "To make food for the plant", "The life cycle can begin again from fallen seeds", "As stages in a process", "coat", "an outer covering", "To explain how pollination leads to seeds", "New seeds form after bees carry pollen") },
      },
      speaking: {
        sceneTopic: "Library Makerspace", scene: "s4-35-scene-library-makerspace",
        scenePrompts: ["Look at the library makerspace picture. What are the children doing?", "Describe two objects the children are using and tell how they are using them.", "What do you think the group is making? Give a reason from the picture.", "Tell about a time you made or built something with another person."],
        functions: [["Ask to Borrow a Tool", "You need the scissors another student is using. What would you say?"], ["Explain a Spill", "You accidentally spill water near a project. What would you say to the teacher?"]],
        speakingOpinions: [["More Making Time", "Should students have more time at school to build and create things? Give your opinion and a reason."], ["Work Alone or Together", "Is it better to make a class project alone or with a group? Give your opinion and explain it."]],
        retell: { topic: "The Garden Sign", scene: "s4-35-retell-garden-sign", prompt: "Look at the four pictures. Retell the story of how the students made and placed a sign for their garden. Include the events in order and the ending." },
        summaries: [
          { topic: "Frog Life Cycle", scene: "s4-35-summary-frog-life-cycle", prompt: "Summarize the frog life-cycle presentation. Tell how a frog changes from an egg to an adult." },
          { topic: "Simple Machines", scene: "s4-35-summary-simple-machines", prompt: "Summarize the simple-machines presentation. Explain how a ramp, lever, or wheel helps people do work." },
        ],
        academicTopic: "Class Plant Growth", academicScene: "plant-experiment-chart",
        writing: {
          picture1: "Look at the picture. Write one complete sentence describing what one child is doing in the makerspace.",
          picture2: "Look at the same picture. Write one sentence about what the children may do next.",
          experienceTopic: "Making Something", experience: "Write about something you made or built. What did you use, what steps did you follow, and how did it turn out? Write at least three sentences.", experienceHint: "Tell the steps in order and explain the result.",
          academic1: "The chart compares two plants that received the same amount of water. Plant A was by a window and grew 12 centimeters. Plant B was in a dark closet and grew 3 centimeters. Write at least two sentences describing the results.",
          academic2: "Using the same chart, explain what the experiment shows about light and plant growth. Use both measurements.",
          opinionTopic: "School Makerspace", opinion: "Should every school have a place where students can build and create projects? State your opinion and give at least two reasons.",
        },
      },
    },
  },
};

const RB=(topic,passage,main,detail,reason,inference,word,meaning,structure="As an explanation supported by examples")=>({topic,passage,details:D(main,"Which detail is stated in the passage?",detail,"Why is this detail important?",reason,inference,structure,word,meaning,"To make the explanation concrete",detail)});
const OB=(topic,transcript,main,detail,reason,inference)=>({topic,transcript,details:L(main,"Which detail does the speaker include?",detail,"Why does the speaker include that detail?",reason,inference)});
const standardExchanges=(setNum,label)=>setNum===4?[
 [`${label} Schedule Change`,`Student: The ${label.toLowerCase()} meeting moved to Wednesday. Classmate: Update the shared calendar tonight so everyone sees the change.`,"What should the student do?","Update the shared calendar","Cancel the meeting","Ignore the change"],
 [`${label} Source Check`,"Student: This website has facts, but no author. Classmate: Use the database article. It names the author and evidence.","Why is the database article preferred?","It identifies its author and evidence","It has brighter colors","It is shorter"],
 [`${label} Materials`,"Student: I brought the poster, but the display clips are in class. Classmate: I will hold our place while you get them.","What will the student get?","The display clips","A new poster","A classroom key"],
]:[
 [`${label} Feedback`,"Student: I revised the conclusion, but the evidence may not connect. Classmate: Check each detail against the claim.","What should the student do?","Check details against the claim","Delete the conclusion","Add unrelated evidence"],
 [`${label} Reservation`,"Student: Our room reservation ends when the interview starts. Classmate: Ask for the next time slot before inviting the guest.","What should the student do first?","Request a later time slot","Invite the guest","Cancel the project"],
 [`${label} Draft Copy`,"Student: My laptop died before the file uploaded. Classmate: The library computer can open your cloud draft.","How can the student submit?","Use a library computer","Rewrite it","Wait for a laptop"],
];
const standardClassroom=(setNum,label)=>classroom(`${label} Project Meeting`,setNum===4?`Teacher: Your ${label.toLowerCase()} project needs a clear question, two reliable sources, and an evidence-based conclusion. Student: May we use our survey? Teacher: Yes, if you explain who answered it and how the questions were written. Student: Should every result go on the poster? Teacher: No. Select results that answer the question and put the full table in an appendix.`:`Teacher: During tomorrow's ${label.toLowerCase()} review, each team will explain its claim and one limitation. Student: Do we submit source notes tonight? Teacher: Yes, so reviewers can check them. Student: May we revise afterward? Teacher: Yes. Explain which feedback you used and why.`,
 ["What must the work explain?",setNum===4?"A question, sources, and conclusion":"A claim and a limitation","Only a title","A fictional ending"],
 ["Why explain or submit sources?","So evidence can be evaluated","So no one reads them","To replace the conclusion"],
 ["What should students do with information or feedback?",setNum===4?"Select what answers the question":"Explain what feedback they used","Include unrelated details","Avoid revision"]);
const upperConfig=(setNum,spec)=>({listening:{exchanges:spec.exchanges||standardExchanges(setNum,spec.label),classroom:standardClassroom(setNum,spec.label),orals:spec.orals,opinions:spec.opinions||[]},reading:{pictureReads:spec.pictureReads||[],shorts:spec.shorts,essay:spec.essay,literary:spec.literary,informational:spec.informational},speaking:{sceneTopic:spec.sceneTopic,scene:spec.scene,scenePrompts:spec.scenePrompts,functions:spec.functions,speakingOpinions:spec.speakingOpinions,...(spec.retell?{retell:spec.retell}:{}),summaries:spec.summaries,academicTopic:spec.academicTopic,academicScene:spec.academicScene,writing:spec.writing}});
CONFIGS[5]={};
// sets 4-C5 extension point
CONFIGS[5].g35=upperConfig(5,{label:"Nature Study",pictureReads:[
 {topic:"Bird Feeder",scene:"s5-35-read-bird-feeder",correct:"Two children are filling a bird feeder with seeds.",wrong1:"Two children are washing a bicycle.",wrong2:"The birds are sleeping in a classroom."},
 {topic:"Rain Boots",scene:"s5-35-read-rain-boots",correct:"A boy is placing wet boots on a mat by the door.",wrong1:"A boy is putting books into an oven.",wrong2:"The floor is covered with beach sand."}],
 orals:[
 OB("How Seeds Travel","Plants cannot walk, but their seeds travel in many ways. Wind carries light seeds with wings or fluff. Burrs hook onto animal fur. Birds eat berries and later drop the seeds somewhere else. Coconuts can float across water. Moving away from the parent plant gives each new seed more room, sunlight, and water to begin growing.","Seeds travel away from parent plants in several ways","Wind, animals, and water can move seeds","Examples show how different seed shapes help movement","Traveling can help a seed find space to grow"),
 OB("Clouds and Rain","Warm sunlight causes water from lakes and soil to rise as invisible vapor. Higher in the sky, the air is cooler, so the vapor gathers into tiny drops that form clouds. The drops bump together and become larger. When they grow too heavy to stay in the cloud, they fall as rain. Water then collects in rivers and lakes, ready to move through the cycle again.","Water changes and moves through a cycle","Tiny drops gather to form clouds","Drops fall when they become too heavy","Rain returns water that can begin the cycle again"),
 OB("A Spider's Web","A spider makes silk inside its body. It first builds strong lines that hold the web in place, then adds a spiral of sticky silk. Flying insects touch the sticky threads and cannot escape quickly. The spider feels the web shake and moves toward the insect. Although a web looks delicate, its pattern helps it bend without breaking in light wind.","A spider web is carefully built to catch food","Sticky spiral threads trap insects","The web's pattern helps it bend","Different threads have different jobs")],
 shorts:[
 RB("Busy Beavers","Beavers build dams by piling branches, stones, and mud across moving water. The dam slows the stream and forms a pond. The pond gives beavers a safer place to build their lodge because many predators do not swim well. A deep pond also keeps the lodge entrance underwater during winter. Beaver ponds can create wet places where frogs, fish, insects, and water birds find food and shelter.","Beaver dams create ponds that help many animals","A lodge entrance can stay underwater","The pond helps protect beavers","Other animals may benefit from beaver work","predators","animals that hunt other animals"),
 RB("The Moon's Changing Shape","The moon does not make its own light. Sunlight brightens half of it at all times. As the moon moves around Earth, people see different amounts of that bright half. A thin crescent grows into a half moon and then a full moon. Afterward, the bright shape becomes smaller again. The moon itself does not disappear or change shape; only our view of its sunlit half changes.","Moon phases come from our changing view of sunlight","Sunlight always brightens half of the moon","The moon moves around Earth","A dark-looking part of the moon is still there","phases","the different shapes we seem to see")],
 essay:RB("A Weekly Nature Walk","Our class should take a short nature walk every Friday. We could observe plants, weather, insects, and birds near the school. Writing one observation in a notebook would give us real examples for science and writing. Some people may worry that a walk takes class time. The route could be only ten minutes long, and the notes could become part of the lesson. We would return with questions that no worksheet could give us. A weekly walk would help us notice how our schoolyard changes through the seasons.","The writer supports a short weekly nature walk","Students could record observations","The notes could become part of class lessons","The writer answers a concern about time","observe","watch carefully"),
 literary:RB("The Quiet Nest","A robin built a nest above the light outside Mateo's apartment. Every afternoon, Mateo checked from the window but never touched it. One windy day, a strip of plastic caught on the branch and flapped beside the nest. The robin would not come close. Mateo asked his aunt for help. She held the ladder while he carefully removed the plastic without touching the nest. By evening, the robin had returned. A week later, Mateo saw three tiny heads rise above the twigs, their mouths wide open.","Mateo helps a robin return safely to its nest","Plastic was flapping beside the nest","Removing the plastic made the area calm again","Mateo understood that helping meant being careful","carefully","with attention to avoid harm"),
 informational:RB("How Compost Becomes Soil","Fruit peels, dry leaves, and grass clippings can become compost. Tiny living things such as bacteria and fungi break the scraps into smaller pieces. Air and a little water help them work. Turning the pile brings fresh air inside. Over time, the scraps become dark and crumbly. Gardeners mix the finished compost into soil, where it holds water and adds nutrients that help plants grow. Meat and plastic do not belong in a school compost pile. Only safe plant scraps should be added.","Composting turns certain scraps into useful soil material","Bacteria and fungi break down scraps","Turning brings air into the pile","Finished compost can help plants grow","crumbly","easy to break into small pieces"),
 sceneTopic:"Community Garden Harvest",scene:"s5-35-scene-garden-harvest",scenePrompts:["Look at the picture. What are the children doing in the garden?","Describe two things the children have harvested.","What will the group probably do with the vegetables next? Give a picture detail.","Tell about a time you helped grow, prepare, or share food."],
 functions:[["Offer Help","A classmate is carrying a heavy basket. What would you say?"],["Ask for Directions","You do not know where to put the garden tools. What would you ask?"]],
 speakingOpinions:[["Grow Food at School","Should schools grow some food in gardens? Give your opinion and a reason."],["Share the Harvest","Should the class share extra vegetables with neighbors? Explain your opinion."]],
 retell:{topic:"The Windy Bird Feeder",scene:"s5-35-retell-bird-feeder",prompt:"Look at the four pictures. Retell how the children fixed a bird feeder after the wind knocked it down. Include the beginning, middle, and ending."},
 summaries:[{topic:"How Seeds Travel",scene:"s5-35-summary-seed-travel",prompt:"Summarize how seeds travel. Include at least two ways and explain why moving helps seeds."},{topic:"Clouds and Rain",scene:"s5-35-summary-clouds-rain",prompt:"Summarize how water vapor forms clouds and then falls as rain."}],
 academicTopic:"Playground Survey",academicScene:"playground-survey-chart",writing:{picture1:"Write one complete sentence describing what one child is doing during the garden harvest.",picture2:"Write one sentence predicting what the group may do after the baskets are full.",experienceTopic:"Helping Outdoors",experience:"Write about a time you helped with an outdoor job. What did you do, who helped, and what happened? Write at least three sentences.",experienceHint:"Tell the events in order and include a result.",academic1:"A survey shows that 14 students chose a climbing wall, 9 chose swings, and 7 chose a basketball hoop. Write at least two sentences comparing the choices.",academic2:"Using the same survey, explain which equipment the school should consider first and support your answer with numbers.",opinionTopic:"Outdoor Learning",opinion:"Should classes sometimes learn outdoors? State your opinion and explain at least two reasons."}});
CONFIGS[5].g35.listening.stories=[
 {topic:"The Fallen Nest",transcript:"Maya saw a small nest on the grass after a windy night. She did not touch the nest or the baby bird beside it. Instead, she asked the school gardener for help. The gardener placed a basket near the tree and called a wildlife center. Maya watched quietly from far away. Soon, the parent birds returned and stayed close while the helper arrived.",qs:[q("Why did Maya ask the gardener for help?","She found a fallen nest and baby bird","She wanted to plant a tree","She had lost her lunch"),q("What did Maya do while the helper was coming?","She watched quietly from far away","She carried the baby bird home","She climbed the tree")]},
 {topic:"The Seed Exchange",transcript:"Leo saved bean seeds from his class garden. At the school seed exchange, he traded some beans for sunflower seeds. A label on each envelope told the plant name and how much sunlight it needed. Leo chose a sunny place beside the fence, planted three seeds, and watered them. Weeks later, tall green stems reached above the fence.",qs:[q("What information was written on each label?","The plant name and sunlight it needed","The price of a new fence","The name of Leo's teacher"),q("Why did Leo plant beside the fence?","The place was sunny","The soil was frozen","The seeds needed darkness")]}];
const extendText=(text,min,topic)=>{
 const support=[`The evidence about ${topic} connects the example to the larger process and shows why the result matters.`,`A careful reader should compare the conditions, identify the cause, and avoid assuming that one observation proves more than the evidence supports.`,`Together, the details show how people can use evidence to explain a pattern, evaluate a choice, or revise a conclusion.`];
 let result=text, index=0;
 while(result.trim().split(/\s+/).length<min){result+=` ${support[index%support.length]}`;index+=1;}
 return result;
};
const upperBank=(setNum,span,s)=>{
 const minRead=span==="g68"?90:span==="g910"?105:130;
 const minListen=span==="g68"?75:span==="g910"?90:110;
 const oral=s.orals.map(x=>OB(x[0],extendText(x[1],minListen,x[0]),...x.slice(2,6)));
 const scenePrompts=span==="g68"
  ? [`Describe the main activity in the ${s.sceneTopic.toLowerCase()} scene.`,`Explain how two parts of the ${s.sceneTopic.toLowerCase()} work are connected.`,`Predict the team's next action and support it with visible evidence from the ${s.sceneTopic.toLowerCase()} scene.`,`Describe a group project related to the ${s.sceneTopic.toLowerCase()} and explain what you learned from it.`]
  : span==="g910"
    ? [`Analyze the main activity in the ${s.sceneTopic.toLowerCase()} scene.`,`Explain how two visible roles in the ${s.sceneTopic.toLowerCase()} depend on one another.`,`Infer the team's next step and justify it with two visible details from the ${s.sceneTopic.toLowerCase()} scene.`,`Connect the ${s.sceneTopic.toLowerCase()} to a comparable experience and explain the lesson.`]
    : [`Analyze the purpose of the ${s.sceneTopic.toLowerCase()} shown in the scene.`,`Evaluate how two visible participants or resources contribute to the ${s.sceneTopic.toLowerCase()}.`,`Infer the next decision the group should make and qualify the inference with visible evidence from the ${s.sceneTopic.toLowerCase()} scene.`,`Connect the ${s.sceneTopic.toLowerCase()} to a comparable situation and evaluate what the experience demonstrates.`];
 const picturePrediction=span==="g68"?`Predict the next action in the ${s.sceneTopic.toLowerCase()} and support it with a visible detail.`:span==="g910"?`Infer the team's next step in the ${s.sceneTopic.toLowerCase()} and justify it with two visible details.`:`Infer the group's next decision in the ${s.sceneTopic.toLowerCase()} and qualify the prediction using visible evidence.`;
 const opinion=s.opinions.map(x=>OB(x[0],extendText(x[1],minListen,x[0]),...x.slice(2,6)));
 const seniorExchanges=span!=="g1112"?undefined:setNum===4?[
  ["Baseline Comparison","Student: The report says emissions fell, but the calculation method changed. Classmate: State both baselines before comparing the percentages.","What should the student do before comparing results?","State both baselines","Hide the method change","Report only one percentage"],
  ["Consent Records","Student: The interviews are recorded, but two consent forms are missing. Classmate: Do not analyze those recordings until permission is documented.","Which recordings should the student wait to analyze?","Those without documented consent","Those with the clearest audio","Those from the first interview"],
  ["Hearing Evidence","Student: Our summary uses the citywide average. Classmate: Add neighborhood data so the hearing panel can see who is affected.","Why should neighborhood data be added?","To reveal how effects differ by area","To make the report shorter","To remove the citywide result"],
 ]:[
  ["Model Assumptions","Student: The ranking changed after I adjusted one weight. Classmate: Include a sensitivity table and explain why the weight is uncertain.","What should accompany the revised ranking?","A sensitivity table and explanation","Only the highest score","An unrelated survey"],
  ["Confidential Draft","Student: The internship file includes participant names. Classmate: Remove identifiers before sharing it with reviewers.","What should the student remove?","Participant identifiers","The research question","All numerical results"],
  ["Replication Note","Student: The second trial did not match the first. Classmate: Report both trials and investigate the changed conditions.","What should the student report?","Both trials and changed conditions","Only the first trial","A result from another project"],
 ];
 const toRead=x=>RB(x[0],extendText(x[1],minRead,x[0]),...x.slice(2,8));
 return upperConfig(setNum,{label:s.label,exchanges:seniorExchanges,orals:oral,opinions:opinion,shorts:s.shorts.map(toRead),essay:toRead(s.essay),literary:toRead(s.literary),informational:toRead(s.informational),
 sceneTopic:s.sceneTopic,scene:s.scene,scenePrompts,
 functions:[[setNum===4?"Clarify Evidence":"Request Feedback",setNum===4?"A teammate makes a claim that you do not understand. Ask for the evidence politely.":"Ask a teammate for specific feedback on your explanation."],[setNum===4?"Disagree Respectfully":"Explain a Revision",setNum===4?"A classmate draws a conclusion that the data may not support. Respond respectfully.":"Explain to a reviewer why you changed one part of your project."]],
 speakingOpinions:s.speakingOpinions,summaries:oral.slice(0,2).map((x,i)=>({topic:x.topic,scene:s.summaryScenes[i],prompt:`Summarize the presentation about ${x.topic}. State the main idea and explain the most important evidence in your own words.`})),
 academicTopic:s.academicTopic,academicScene:s.academicScene,writing:{picture1:`Describe one visible action in the ${s.sceneTopic.toLowerCase()} scene and explain its purpose.`,picture2:picturePrediction,experienceTopic:s.experienceTopic,experience:s.experience,experienceHint:"Organize the event clearly and explain what changed or what you learned.",academic1:s.academic1,academic2:s.academic2,opinionTopic:s.opinionTopic,opinion:s.opinion}});
};
CONFIGS[4].g68=upperBank(4,"g68",{label:"Environmental Investigation",sceneTopic:"Stream Testing Team",scene:"s4-68-scene-stream-testing",summaryScenes:["s4-68-summary-wetland-filters","s4-68-summary-tectonic-plates"],
 orals:[
 ["Wetlands as Filters","Wetlands slow water as it moves through dense plants and shallow soil. The slower flow lets sediment settle instead of washing downstream. Plant roots absorb some nutrients, and microbes in the mud break down certain pollutants. Wetlands cannot remove every contaminant, but protecting them can improve water quality and reduce flooding during heavy rain.","Wetlands can improve water quality through several connected processes","Slow water allows sediment to settle","The example explains how physical and biological processes work together","Wetlands help but do not eliminate every water problem"],
 ["Tectonic Plates","Earth's outer shell is divided into plates that move a few centimeters each year. Where plates pull apart, magma rises and forms new crust. Where they collide, one plate may slide beneath another or mountains may rise. Plates can also grind past each other, storing and releasing energy as earthquakes. Scientists use patterns of earthquakes and volcanoes to study these boundaries.","Plate movement shapes Earth's surface and causes geologic events","Different boundaries produce different results","The examples connect plate direction to landforms and hazards","Earthquake and volcano patterns provide evidence about hidden boundaries"]],
 opinions:[["Repair Café","A school repair café would let students bring broken lamps, backpacks, and small devices to supervised workshops. Repairing an item can reduce waste and teach practical skills. Safety rules and trained adults would be necessary, and not every object could be fixed. Even so, monthly sessions could begin with low-risk materials and expand only after the program is evaluated.","A supervised repair café could reduce waste and build skills","The plan would begin with low-risk repairs","A limited pilot addresses safety concerns","The proposal supports testing the idea before expansion"],["Native Plant Garden","Replacing one lawn area with native plants could provide food for local insects and use less irrigation. Students could record visiting species and compare water use before and after planting. The change would require planning because paths and visibility must remain safe. A small demonstration plot would provide evidence before the school changes a larger area.","A native plant pilot could support wildlife and learning","Students could compare species and water use","A demonstration plot would test benefits and practical limits","The speaker favors a measured pilot rather than an immediate full conversion"]],
 shorts:[["Coral Bleaching","Corals contain tiny algae that provide much of their food and color. When ocean water stays unusually warm, stressed corals may release the algae and turn white. A bleached coral is still alive, but it has less energy and becomes more vulnerable to disease. If temperatures return to normal soon, algae can return; repeated heat waves make recovery less likely.","Heat stress can cause coral bleaching and weaken reefs","Bleached coral has lost helpful algae","The algae provide food as well as color","Recovery depends partly on how long and how often heat occurs","vulnerable","more likely to be harmed"],["Fingerprint Patterns","Fingerprint ridges form before birth and usually keep the same general pattern throughout life. Investigators compare loops, whorls, arches, and smaller ridge details. A computer may locate possible matches, but a trained examiner must inspect image quality and similarities. A partial or smudged print may support an investigation without proving who touched an object by itself.","Fingerprint comparison combines pattern evidence with careful limits","Examiners inspect smaller ridge details","Partial prints may be incomplete or unclear","A fingerprint result should be interpreted with other evidence","partial","not complete"]],
 essay:["Reusable Cafeteria Trays","Our school should replace disposable lunch trays with reusable ones. Disposable trays create daily trash, while durable trays can be washed and used for years. The change would require water, energy, and staff time, so the school should compare those costs instead of assuming reuse is always better. A one-month trial could measure waste, washing time, and student response before a final decision.","The writer supports testing reusable trays before a final decision","A trial would measure both benefits and costs","Measurement answers concerns about hidden resource use","The argument uses a pilot to evaluate a proposal","durable","able to last through repeated use"],
 literary:["The Missing Data Point","Jada's graph showed that every plant grew faster under the blue lamp, except one. She nearly erased the odd measurement, worried that it would make the project look careless. Her partner Amir checked the notebook and found that the lamp had been unplugged that afternoon. They kept the point, added the explanation, and repeated the trial. The new result followed the pattern, but Jada was proudest of the first graph because it showed exactly what had happened.","Students preserve an unexpected result and investigate it","The lamp had been unplugged","The odd point revealed a condition that needed explanation","Honest reporting can strengthen an investigation","preserve","keep without hiding or changing"],
 informational:["How Transit Routes Change","Transit planners study where riders begin and end trips, how long buses wait in traffic, and which stops are crowded. Adding a route may help one neighborhood but require buses or drivers from another. Planners model several options, invite public comments, and sometimes run a temporary service. Ridership during the trial provides evidence, but seasonal events and construction can affect the numbers.","Transit changes require evidence and tradeoff analysis","A temporary service can provide ridership data","Resources moved to one route may affect another","Planners should interpret trial data in context","seasonal","connected to a particular time of year"],
 speakingOpinions:[["Outdoor Water Testing","Should science classes conduct supervised water tests outside school? Support your position with reasons."],["Repair Before Replace","Should schools repair usable equipment before buying replacements? Explain your position."]],academicTopic:"Club Funding Requests",academicScene:"club-funding-chart",academic1:"Compare the three club requests and identify the two largest amounts using exact values.",academic2:"The requests total more than the available budget. Recommend a funding decision and justify it with at least two values from the chart.",experienceTopic:"Revising a Project",experience:"Write about a time evidence or feedback caused you to revise a project. Explain the original plan, the change, and the result.",opinionTopic:"Student Research Outdoors",opinion:"Should every middle school course include at least one supervised field investigation? State a position, develop two reasons, and address one concern."});
CONFIGS[5].g68=upperBank(5,"g68",{label:"Systems and Design",sceneTopic:"Museum Exhibit Team",scene:"s5-68-scene-museum-exhibit",summaryScenes:["s5-68-summary-artifact-preservation","s5-68-summary-algorithm-recommendations"],
 orals:[["Protecting Museum Objects","Museum objects can slowly change when they are exposed to too much light, moisture, heat, or handling. Bright light may fade paper and fabric, while changing humidity can make wood swell and shrink. Curators reduce damage by using filtered lights, stable display cases, clean gloves, and padded supports. They also check objects regularly because no single protection removes every risk.","Museums slow damage by controlling several environmental risks","Light can fade paper and fabric","Stable cases and careful handling protect different materials","Regular checks matter because no single method removes every risk"],["Recommendation Algorithms","A recommendation algorithm predicts what a user may want to watch, read, or buy. It compares signals such as prior choices, search terms, and patterns from similar users. The prediction can be useful, but repeated recommendations may narrow what a person encounters. Designers evaluate both accuracy and variety, while users can reduce some influence by changing settings or seeking sources directly.","Recommendation systems use behavior patterns to make predictions","Designers may evaluate accuracy and variety","Variety matters because repeated suggestions can narrow exposure","Users and designers both influence recommendation results"]],
 opinions:[["Device Repair Program","A student device-repair program could teach troubleshooting and keep usable equipment out of the waste stream. Students would need training, privacy rules, and adult supervision. Repairs involving stored data or electrical risk should remain with professionals. A limited program focused on keyboards, cases, and approved parts could provide benefits without ignoring safety.","A limited device-repair program could build skills safely","High-risk repairs would remain with professionals","Boundaries answer safety and privacy concerns","The proposal supports a restricted program, not unrestricted access"],["Quiet Study Room","Converting one unused room into a quiet study space could help students who need fewer distractions. The room would need clear expectations and enough supervision. It should not replace collaborative spaces or become a punishment area. Usage records and student feedback could show whether the room serves a real need.","A carefully managed quiet room could expand study choices","The room should not replace collaboration","Feedback could test whether students benefit","The proposal balances focus with access to other learning settings"]],
 shorts:[["Pollinator Networks","Many flowering plants depend on insects, birds, or bats to carry pollen. Different pollinators visit different flower shapes and bloom at different times. If a habitat supports only one pollinator species, disease or weather could interrupt the entire connection. Diverse gardens provide overlapping food sources and nesting places, making the network more resilient when one species declines.","Diverse pollinator networks make plant reproduction more resilient","Species visit different flowers and seasons","Overlapping roles reduce dependence on one species","Habitat diversity can protect a system from disruption","resilient","able to recover or keep functioning"],["Water Footprints","A water footprint includes direct water use and the water used to produce goods. A cotton shirt, for example, requires water to grow cotton, dye fabric, and operate factories. Estimates vary by climate and production method, so one number does not describe every shirt. Water-footprint comparisons are most useful when their assumptions and locations are clearly stated.","Water footprints reveal hidden use but depend on assumptions","Production location affects estimates","Climate and methods change the amount of water required","Comparisons require context, not just a single number","assumptions","conditions accepted when making an estimate"]],
 essay:["Student-Led Conferences","Students should lead part of their own family conferences. Preparing a short presentation would require them to choose evidence of growth, name a challenge, and set a next goal. Some students may feel nervous or select only their strongest work, so teachers should provide a common outline and review the evidence first. Student leadership should add to, not replace, honest teacher feedback.","The writer supports structured student leadership in conferences","Teachers would review evidence beforehand","A common outline addresses uneven preparation","The proposal balances student voice with teacher feedback","structured","organized by clear expectations"],
 literary:["The Borrowed Label","At the museum workshop, Niko attached a label that described a clay bowl as ceremonial. Dr. Chen asked which source supported that word. Niko pointed to an old catalog, but a newer excavation report called the bowl an everyday cooking vessel. Rather than choosing the more dramatic description, the team rewrote the label to explain both interpretations and why the evidence had changed. Visitors paused longer at the revised display than at the original one. Their questions showed that uncertainty could invite careful thinking.","A museum team revises a claim when newer evidence challenges it","A newer report described an everyday vessel","Explaining both interpretations was more honest than choosing drama","Good exhibits reveal uncertainty instead of hiding it","interpretations","explanations of what evidence may mean"],
 informational:["How Museums Date Objects","Museums estimate an object's age by combining evidence. A maker's mark may connect it to a workshop, while the soil layer where it was found provides context. Scientists can date some organic materials, and style comparisons may narrow a range. Each method has limits, so curators record where an object came from and which tests were used. A date is strongest when independent clues agree.","Object dates are estimates built from multiple kinds of evidence","Curators record an object's context and tests","Methods have different limits","Agreement among independent clues strengthens a conclusion","independent","not produced by the same source or method"],
 speakingOpinions:[["Interactive Exhibits","Should museums replace some text labels with interactive exhibits? Support your position and address access."],["Personalized Recommendations","Should school learning platforms recommend materials from student history? Explain benefits and risks."]],academicTopic:"Solar Cost and Electricity Share",academicScene:"solar-cost-share-chart",academic1:"Describe both trends from 2018 to 2024 and cite at least two exact values from each graph.",academic2:"Explain the relationship suggested by the two graphs and identify one conclusion the data cannot prove.",experienceTopic:"Explaining a Complex Idea",experience:"Write about a time you helped someone understand a difficult idea. Explain the strategy you used and how you knew whether it worked.",opinionTopic:"Personalized Technology",opinion:"Should schools use recommendation systems to personalize assignments? State a position, give two reasons, and address a privacy or fairness concern."});
CONFIGS[4].g910=upperBank(4,"g910",{label:"Evidence and Public Communication",sceneTopic:"Student Newsroom",scene:"s4-910-scene-student-newsroom",summaryScenes:["s4-910-summary-bioluminescence","s4-910-summary-prairie-restoration"],
 orals:[["Bioluminescence","Bioluminescent organisms produce light through a chemical reaction involving a light-emitting molecule and an enzyme. In the deep ocean, some animals use flashes to attract prey, confuse predators, or signal mates. Similar light can evolve for different functions, so scientists cannot infer an organism's purpose from brightness alone. They compare behavior, anatomy, and environmental conditions before proposing an explanation.","Bioluminescence serves varied functions that require contextual evidence","Scientists compare behavior and anatomy","Similar light may serve different purposes","A visible trait alone does not establish its function"],["Prairie Restoration","Prairie restoration begins by identifying which native plants once occupied a site and which pressures removed them. Crews may control invasive species, reintroduce periodic fire, and sow diverse seeds. Plant counts can rise before soil communities and animal networks recover, so a single season is not enough to judge success. Long-term monitoring examines species diversity, soil condition, and resilience during drought.","Restoration success requires multiple actions and long-term measures","Early plant growth does not prove full recovery","Soil and animal networks change more slowly","A credible evaluation uses several indicators across years"]],
 opinions:[["Later Activity Bus","A later bus could let more students participate in tutoring, clubs, and athletics. However, low ridership on some days could make fixed routes expensive. The district should pilot two centralized routes, publish ridership and cost data, and survey students who still cannot reach a stop. A pilot would test access without treating initial participation as the only measure of need.","A limited later-bus pilot could test access and cost","The district would publish several kinds of data","Ridership alone may miss students who cannot reach a stop","The proposal uses a pilot while recognizing an equity limitation"],["Media Literacy Course","A required media-literacy unit could teach students to trace claims, inspect sources, and recognize manipulated images. Adding a full course may displace electives, so the unit could be integrated into English, science, and history assignments. Shared criteria would help teachers reinforce the same habits while allowing examples to fit each subject.","Media literacy should be required but integrated across subjects","Shared criteria could connect different classes","Integration addresses concern about displacing electives","The proposal prioritizes common skills without prescribing one course format"]],
 shorts:[["Green Roofs","A green roof adds layers of soil and plants above a waterproof membrane. Plants can shade the roof, slow storm runoff, and provide habitat, but saturated soil adds weight. Engineers must assess the structure, drainage, climate, and maintenance plan before installation. Comparing a green roof with reflective roofing also requires a common time period because construction cost, energy savings, and lifespan occur on different schedules.","Green roofs offer benefits that must be evaluated against structural and maintenance limits","Saturated soil increases roof load","Costs and savings occur on different schedules","A suitable roof depends on site conditions rather than one universal answer","membrane","a protective layer that blocks water"],["Sleep Cycles","During sleep, the brain moves through repeating stages that differ in activity and body response. Deep sleep is associated with physical restoration, while rapid-eye-movement sleep is linked to vivid dreaming and some memory processes. A person awakened repeatedly may spend enough total hours in bed but complete fewer uninterrupted cycles. Researchers therefore distinguish sleep duration from sleep quality when interpreting performance.","Sleep quality depends on uninterrupted cycles as well as total duration","Repeated waking can interrupt cycles","Time in bed may not equal restorative sleep","Performance claims should consider both duration and continuity","duration","the amount of time something lasts"]],
 essay:["Peer Tutoring Credit","Our school should offer elective credit for trained peer tutors. Tutors would deepen their own understanding while expanding academic support, but credit should reflect documented preparation and service rather than informal help between friends. A supervising teacher could review session logs, student feedback, and brief reflections. Critics may worry that peers will replace professional support; the program should instead cover practice and study strategies while teachers handle diagnosis and grading.","The writer supports structured credit for supervised peer tutoring","Credit would require documented preparation and service","Defined roles prevent tutors from replacing teachers","The proposal answers a concern by limiting tutor responsibilities","documented","recorded so it can be checked"],
 literary:["The Unsent Correction","Minutes before publication, Ana noticed that the student newspaper article called a survey representative. Only students in advanced classes had received the form. The claim made the headline stronger, and the editor had already approved the layout. Ana reopened the file, changed the headline, and added a note about the sample. The edition went online late. The next morning, a teacher thanked the staff for explaining the limitation. Ana saved the original headline in her drafts as a reminder that speed could make certainty look easier than it was.","A student journalist weakens a headline to report evidence honestly","Only advanced classes received the survey","The sample could not represent the whole school","Accuracy sometimes requires delaying publication and qualifying a claim","representative","reflecting the larger group fairly"],
 informational:["How Vaccines Are Tested","Vaccine trials proceed through stages that examine safety, immune response, and protection against disease. Random assignment helps create comparable groups, while blinding can reduce the influence of expectations. Researchers define outcomes before analyzing results and report uncertainty around estimates. A successful trial does not prove identical effects for every person or every future variant, so monitoring continues after authorization.","Vaccine evidence develops through controlled trials and continued monitoring","Random assignment supports comparable groups","Predefined outcomes reduce selective interpretation","Strong evidence can still contain uncertainty and population limits","authorization","official permission for use under stated conditions"],
 speakingOpinions:[["Publish Preliminary Results","Should a school newspaper publish preliminary survey results before collecting a broader sample? Defend your position."],["Later Activity Bus","Should the district fund a later activity bus even if initial ridership is uncertain? Address access and cost."]],academicTopic:"Solar Cost and Electricity Share",academicScene:"solar-cost-share-chart",academic1:"Analyze both trends from 2018 through 2024 and support the analysis with at least four exact values.",academic2:"Evaluate the claim that lower solar costs caused the higher local solar share. Explain what the graphs support and what additional evidence is needed.",experienceTopic:"Correcting a Claim",experience:"Write about a time you corrected or qualified a claim after checking evidence. Explain the original claim, the new evidence, and the effect of the revision.",opinionTopic:"Required Media Literacy",opinion:"Should media literacy be a graduation requirement? Develop a position with evidence-based reasoning and address a scheduling or curriculum counterargument."});
CONFIGS[5].g910=upperBank(5,"g910",{label:"Engineering and Information",sceneTopic:"Engineering Design Review",scene:"s5-910-scene-engineering-review",summaryScenes:["s5-910-summary-battery-recycling","s5-910-summary-language-change"],
 orals:[["Battery Recycling","Lithium-ion batteries contain materials that can be recovered, but recycling involves collection, sorting, discharge, and chemical separation. The environmental benefit depends on recovery rates, transportation distance, and the energy source used by the facility. Recycling can reduce demand for new mining without eliminating it because material is lost and battery demand is growing. Analysts compare the full life cycle rather than treating recycling as impact-free.","Battery recycling can reduce impacts but must be evaluated across its full process","Some material is lost and demand is growing","Transportation and energy sources affect benefits","Recycling complements rather than completely replaces new material supply"],["Language Change","Languages change as communities create words, borrow expressions, and shift pronunciations. Digital communication can spread a phrase quickly, but visibility online does not show whether every group uses it. Dictionaries document established patterns after examining varied evidence; they do not create usage by adding a word. A change can be widespread in one community and rare in another, making context essential.","Language change emerges from community use and varies by context","Dictionaries examine patterns rather than create them","Online visibility may not represent every group","Claims about language change require evidence across communities"]],
 opinions:[["Later Start Pilot","Moving the high-school start time later could improve sleep for some students, but transportation, activities, and family schedules would change. A one-year pilot should compare attendance, tardiness, sleep reports, and participation with prior years. Results should also be separated by student group because an average could hide unequal effects.","A later-start pilot should be evaluated with multiple measures and groups","Averages can hide unequal effects","Several outcomes are affected beyond sleep","The speaker supports testing the policy without assuming uniform benefits"],["Community Service Credit","Students should be able to earn elective credit for sustained community service connected to reflection and learning goals. Hours alone would reward time rather than growth, and unpaid service may be harder for students with jobs or caregiving duties. Schools should offer on-campus options and assess a final project instead of requiring one fixed number of outside hours.","Service credit should assess learning while accounting for unequal access","On-campus options could improve access","Hours alone do not show learning","The proposal combines service, reflection, and flexible participation"]],
 shorts:[["Wildfire Buffers","A wildfire buffer reduces combustible material near buildings, but it is not simply an empty ring of soil. Plans may space trees, remove dead branches, choose less flammable plants, and keep roofs clear. Effectiveness depends on wind, terrain, building materials, and maintenance. A buffer can lower risk without guaranteeing safety, so evacuation planning and broader landscape management remain necessary.","Wildfire buffers are risk-reduction systems, not guarantees","Maintenance and building materials affect performance","Fire behavior depends on conditions beyond one property","Effective preparation combines several strategies","combustible","able to catch fire and burn"],["Deepfake Detection","Deepfakes use machine-learning systems to generate or alter audio and video. Detection tools search for visual artifacts, inconsistent sound, or patterns left by a model, but new generation methods can reduce those clues. Investigators also verify when and where a file appeared, locate earlier versions, and contact original sources. Provenance evidence may remain useful even when image-based detectors disagree.","Deepfake verification combines technical detection with source tracing","New generators can reduce familiar artifacts","Provenance checks do not depend only on visible clues","No single detector should be treated as permanent proof","provenance","the documented origin and history of a file"]],
 essay:["Open-Campus Lunch","Our school should not adopt open-campus lunch without a limited trial. Nearby restaurants could expand choice, but travel time, traffic, affordability, and unequal access could affect students differently. A trial for eligible upper-grade students could track late returns, incidents, participation, and student spending. The school should also preserve a complete on-campus meal. If evaluation focuses only on popularity, it will miss whether the policy works safely and fairly.","The writer supports a cautious trial rather than immediate adoption","The school should preserve an on-campus meal","Popularity would not measure safety or fairness","A trial can test benefits while monitoring unequal effects","eligible","meeting stated requirements"],
 literary:["The Last Prototype","The bridge team celebrated when their final model held the required weight. Then Sora noticed that one support had been glued at a different angle than the drawing showed. Rebuilding before judging could lower their score if the new model failed. The group photographed the model, reported the difference, and tested a second copy built to the drawing. It failed sooner. Their presentation explained that the accidental angle had improved the design and proposed a revised plan. The judges praised the discovery more than the original success.","A team turns an accidental difference into a documented design improvement","The model differed from the drawing","Testing a second copy isolated the design change","Transparent replication made an accidental result useful","replication","repeating work to check whether a result occurs again"],
 informational:["How Satellites Track Drought","Satellites observe rainfall, plant color, surface temperature, and changes in stored water. Each measurement captures a different part of drought. Cloud cover may interrupt optical images, and healthy-looking leaves can persist after soil moisture declines. Researchers combine satellite records with weather stations and ground sensors, then compare current conditions with long-term baselines. The resulting maps estimate severity; they do not directly measure every field.","Drought monitoring combines several remote and ground measurements","Long-term baselines provide comparison","Individual indicators can lag or be obstructed","Drought maps are estimates strengthened by multiple sources","baseline","a reference condition used for comparison"],
 speakingOpinions:[["Replicate Before Publishing","Should student engineering teams be required to replicate a successful test before presenting it? Defend your position."],["Later School Start","Should the school run a one-year later-start pilot? Address both evidence and implementation."]],academicTopic:"Club Funding Requests",academicScene:"club-funding-chart",academic1:"Analyze how the three requests create a budget shortfall, citing every relevant amount.",academic2:"Propose a defensible allocation under the $1,200 budget and explain the tradeoffs with numerical evidence.",experienceTopic:"Learning from a Failed Design",experience:"Write about a failed attempt that improved your later work. Explain the failure, the evidence you noticed, and the revision.",opinionTopic:"Replication in School Research",opinion:"Should replication be required before a student research result is presented as reliable? Develop a position and address time or resource constraints."});
CONFIGS[4].g1112=upperBank(4,"g1112",{label:"Policy Evidence and Tradeoffs",sceneTopic:"Community Planning Hearing",scene:"s4-1112-scene-public-hearing",summaryScenes:["s4-1112-summary-desalination","s4-1112-summary-microgrids"],
 orals:[["Desalination Tradeoffs","Desalination can provide a drought-resistant water source by removing salts from seawater, yet the process requires substantial energy and produces concentrated brine. Plant location affects intake impacts, transmission costs, and which ecosystems encounter the discharge. New membranes and renewable power can reduce some burdens, but comparisons must use consistent assumptions about energy prices, emissions, and water reliability. Policymakers therefore evaluate desalination alongside conservation, recycling, storage, and regional transfers rather than asking whether it is simply good or bad.","Desalination is a context-dependent water option with benefits and significant tradeoffs","Plant location changes several environmental and infrastructure effects","Consistent assumptions are needed for fair comparison","Policy analysis should compare a portfolio of alternatives rather than isolate one technology"],["Community Microgrids","A community microgrid links local generation, batteries, and selected buildings that can disconnect from the larger grid during an outage. Hospitals or cooling centers may gain resilience, but equipment cost and decisions about which loads receive priority raise distributional questions. A project that performs well in one emergency may face different limits during a longer or seasonal event. Evaluators model multiple outage scenarios, disclose priority rules, and examine who pays as well as who benefits.","Microgrids can improve resilience while creating technical and equity choices","Priority rules determine which loads remain powered","Different outage scenarios may change performance","A complete evaluation includes cost distribution and transparent service priorities"]],
 opinions:[["Civic Data Portal","A public civic-data portal could help residents inspect budgets, permits, and service performance. Raw publication alone, however, may advantage users with technical skills and expose sensitive details. Agencies should publish documentation, accessible summaries, privacy reviews, and revision histories. Independent users must be able to reproduce key figures, while officials should explain uncertainty rather than presenting every value as exact.","A civic-data portal should combine openness with accessibility, privacy, and documentation","Revision histories help users trace changes","Raw data alone does not guarantee meaningful access","Transparency depends on usable context and reproducible methods"],["Senior Capstone Requirement","A senior capstone can require students to investigate a sustained question, revise work, and present evidence publicly. A single format could disadvantage students whose projects are technical, artistic, or community-based, and unequal access to mentors could affect outcomes. Schools should provide multiple formats, common evidence standards, and scheduled advising. The requirement is defensible only if support is built into the school day.","A capstone can demonstrate sustained learning if formats and support are equitable","Scheduled advising reduces dependence on outside mentors","Common evidence standards can coexist with multiple formats","A requirement without access to support would produce misleading comparisons"]],
 shorts:[["Carbon Accounting","Organizations estimate greenhouse-gas emissions by defining boundaries and converting activities into carbon-dioxide equivalents. Direct fuel use may be easier to measure than emissions embedded in purchased goods. Two reports can therefore differ because they use different scopes, factors, or time periods, even if neither contains arithmetic errors. Credible comparisons disclose these choices and test how conclusions change under plausible alternatives.","Carbon accounts are estimates shaped by methodological boundaries and conversion choices","Reports may use different scopes without arithmetic errors","Disclosed methods reveal why totals differ","Comparisons require aligned boundaries and sensitivity to assumptions","embedded","indirectly contained within production and supply chains"],["Clinical Trial Blinding","Blinding in a clinical trial keeps some participants, clinicians, or outcome assessors unaware of treatment assignments. The method can reduce expectation effects and biased measurement, but it is not always possible when treatments have obvious procedures or side effects. Researchers document who was blinded, test whether assignments may have been guessed, and interpret subjective outcomes cautiously. Blinding strengthens design without automatically eliminating every source of bias.","Blinding can reduce specific biases but has practical limits","Researchers may test whether assignments were guessed","Obvious procedures can reveal treatment assignment","Design quality depends on documenting and interpreting limits, not merely labeling a study blinded","subjective","influenced by personal judgment or perception"]],
 essay:["Paid Community Research","The district should offer paid student positions for community research projects. Compensation can broaden participation beyond students who can afford unpaid service, while partnerships can provide authentic audiences and data. Payment alone does not guarantee educational value, so projects should include research questions, source review, ethical guidance, and reflection. Selection must also be transparent. A funded pilot across several schools could compare participation and learning before the district treats one model as scalable.","The writer supports a paid, structured pilot for community research","Transparent selection is necessary","Payment improves access but does not ensure learning quality","A multisite pilot can test both equity and educational outcomes","scalable","capable of expanding without losing essential quality"],
 literary:["The Footnote","Leila's policy brief contained a clean estimate: the proposal would save twenty percent. In the source spreadsheet, a footnote said the estimate excluded maintenance and assumed full participation. Her supervisor suggested leaving the number in the executive summary because the caveat appeared later. Leila replaced the sentence with a range and moved the assumptions beside it. The revised claim looked less decisive. During the hearing, however, a council member used those assumptions to ask a better question about implementation, and the discussion shifted from whether the estimate was certain to which conditions could make it plausible.","A writer makes a policy estimate less certain but more useful by foregrounding assumptions","The original estimate excluded maintenance and assumed full participation","Moving assumptions changed how decision makers evaluated implementation","Qualified claims can support better decisions than overstated precision","plausible","reasonable under stated conditions"],
 informational:["Managed Retreat","Managed retreat relocates buildings or infrastructure away from areas exposed to repeated flooding or erosion. Avoided future damage can be substantial, but property values, cultural ties, tax revenue, and voluntary participation complicate the analysis. Cost-benefit models may discount future losses differently and often struggle to represent nonmarket harms. Effective programs combine hazard projections with community governance, relocation support, and transparent criteria; a favorable regional average does not ensure fair outcomes for each household.","Managed retreat requires technical risk analysis and attention to distributional and cultural consequences","Models may represent future and nonmarket harms differently","Regional averages can hide household-level burdens","A defensible program combines projections with participatory governance and support","nonmarket","not fully represented by a monetary price"],
 speakingOpinions:[["Open Civic Data","Should local governments publish detailed operational data by default? Define appropriate privacy and accessibility limits."],["Required Senior Capstone","Should a capstone be required for graduation? Defend a position while addressing unequal access to time or mentorship."]],academicTopic:"Solar Cost and Electricity Share",academicScene:"solar-cost-share-chart",academic1:"Synthesize the two time series using exact values and distinguish correlation from a demonstrated causal relationship.",academic2:"Evaluate the claim that falling cost alone explains the change in solar share. Identify at least two omitted variables or data sources needed.",experienceTopic:"Revising Under Uncertainty",experience:"Write about a decision you revised after recognizing uncertainty or an unstated assumption. Analyze the evidence, the revision, and its consequences.",opinionTopic:"Public Data by Default",opinion:"Should public agencies adopt an open-by-default data policy? Develop a qualified position that addresses reproducibility, privacy, accessibility, and administrative cost."});
CONFIGS[5].g1112=upperBank(5,"g1112",{label:"Models, Risk, and Accountability",sceneTopic:"Internship Project Briefing",scene:"s5-1112-scene-internship-briefing",summaryScenes:["s5-1112-summary-grid-storage","s5-1112-summary-epidemiological-risk"],
 orals:[["Grid-Scale Energy Storage","Grid-scale storage shifts electricity across time rather than creating new energy. Batteries respond quickly but differ in duration, material supply, degradation, and fire-management needs. Pumped storage can hold large amounts for longer periods but depends on geography and water impacts. Comparing technologies by cost per unit of power alone can obscure how long they discharge and which grid service they provide. Planners model demand, transmission constraints, extreme events, and replacement schedules before selecting a portfolio.","Storage technologies serve different grid functions and require multidimensional comparison","Cost per unit of power can obscure discharge duration","Geography constrains some long-duration options","A portfolio should be matched to scenarios and services rather than one headline metric"],["Interpreting Epidemiological Risk","An epidemiological association compares how often an outcome occurs across groups or exposures. Relative risk describes proportional difference, while absolute risk shows the change in probability. Confounding, selection, measurement error, and chance can influence an observed relationship. Researchers examine design, uncertainty intervals, dose patterns, and evidence from other studies before inferring causation. A statistically detectable association may still have modest practical importance, and a small study may miss an effect that exists.","Risk evidence requires interpreting magnitude, uncertainty, design, and alternative explanations","Relative and absolute risk answer different questions","Confounding can create or distort an association","Statistical detection and practical importance are not equivalent"]],
 opinions:[["Public Transit Pricing","Fare-free transit may increase access and reduce boarding delays, but lost revenue must be replaced and benefits depend on service quality. A policy analysis should compare targeted discounts, universal free fares, and investment in frequency. Ridership totals alone cannot show whether low-income riders gained reliable access. Agencies should report distributional outcomes and opportunity costs under each scenario.","Transit pricing should be evaluated against alternatives using distributional and service evidence","Ridership totals do not establish equitable access","Lost revenue has an opportunity cost","The speaker calls for comparative analysis rather than a universal slogan"],["AI Disclosure in Schoolwork","Students should disclose substantial use of generative tools in assessed work, but disclosure rules must distinguish brainstorming, editing, translation, and generated content. A single prohibition may hide legitimate support needs, while vague permission can make authorship impossible to evaluate. Courses should define allowed assistance by task, require process evidence when relevant, and teach citation practices. Enforcement data should be reviewed for unequal effects.","AI-use rules should be task-specific, transparent, and monitored for equity","Different forms of assistance affect authorship differently","Process evidence can clarify how work was produced","A nuanced disclosure policy is more defensible than a single undefined rule"]],
 shorts:[["Causal Inference","Causal inference asks what would have happened to the same units under a different condition, a counterfactual that cannot be observed directly. Randomization can make groups comparable on average, while observational studies use design and statistical adjustment to approximate that comparison. Every approach relies on assumptions. Researchers test balance, examine alternative specifications, and state which populations and settings the estimate may apply to.","Causal claims depend on designs that approximate an unobservable comparison","Randomization creates comparability on average","Counterfactual outcomes cannot both be observed for the same unit","Credible inference requires explicit assumptions and robustness checks","counterfactual","an alternative outcome under a condition that did not occur"],["Model Uncertainty","Models simplify systems by selecting variables and relationships. Parameter uncertainty concerns values inside a chosen structure, while structural uncertainty concerns whether the relationships themselves are appropriate. Producing a narrow numerical range from one model may understate uncertainty if plausible structures give different results. Analysts compare models, validate against withheld observations, and communicate scenario dependence instead of treating precision as certainty.","Model uncertainty includes uncertainty about values and about structure","Plausible structures may produce different results","One narrow interval may omit structural alternatives","Responsible reporting connects results to model and scenario assumptions","withheld","reserved from model fitting for an independent check"]],
 essay:["Paid Civic Internships","The state should fund paid civic internships for high-school students, but expansion should follow a deliberately evaluated pilot. Compensation can widen access, while structured placements can develop research and communication skills. Yet competitive selection may reproduce existing advantages, and host quality may vary. Programs should recruit across schools, provide common training, audit placement experiences, and compare outcomes with applicants who were not selected while acknowledging that selection is not random.","The writer supports an equity-focused, evaluated pilot for paid civic internships","Host quality and selection may vary","Common training and audits address implementation differences","Outcome comparisons must acknowledge nonrandom selection","audit","systematically examine performance and records"],
 literary:["The Revision Log","Mara's internship team used a model to rank cooling-center locations. The first map favored downtown because it weighted population density heavily. A neighborhood organizer asked why tree cover, disability access, and transit reliability were absent. The deadline was close, and adding variables changed the top sites. Mara recorded both versions, documented the new weights, and presented sensitivity results rather than one final ranking. The council postponed its vote, but several members said the revision log revealed a policy choice that the polished first map had hidden.","A revision log exposes value choices embedded in a seemingly objective ranking","The first model heavily weighted population density","Adding access and environmental variables changed rankings","Sensitivity analysis can reveal how modeling choices affect policy recommendations","sensitivity","the degree to which results change when assumptions or inputs change"],
 informational:["Adaptive Reuse","Adaptive reuse converts an existing building to a new purpose. Reuse may avoid demolition waste and preserve cultural value, but old structures can require seismic upgrades, hazardous-material removal, or inefficient layouts. Carbon comparisons depend on the study period, the emissions embodied in new materials, and operational energy after renovation. Planners also consider zoning, accessibility, financing, and displacement. A claim that reuse is always greener or always costlier ignores project-specific baselines and social effects.","Adaptive reuse decisions require environmental, technical, financial, and social comparison","Study period affects carbon comparison","Old structures may need major upgrades","General claims are unreliable without project-specific baselines","embodied","associated with producing and constructing materials before operation"],
 speakingOpinions:[["Fare-Free Transit","Should a transit agency prioritize universal fare-free service or targeted discounts plus greater frequency? State criteria and defend a choice."],["AI Assistance Disclosure","Should all substantial generative-tool assistance be disclosed in assessed schoolwork? Define substantial and address accessibility."]],academicTopic:"Comparing Summer Jobs",academicScene:"two-jobs-comparison",academic1:"Compare the two jobs across pay, travel time, and career relevance without treating one factor as automatically decisive.",academic2:"Recommend a job for a student considering both immediate income and a veterinary career. State assumptions and explain how a different priority could change the conclusion.",experienceTopic:"Modeling a Decision",experience:"Write about a decision in which changing one priority or assumption changed the preferred option. Explain the criteria, tradeoffs, and final judgment.",opinionTopic:"AI Assistance Disclosure",opinion:"Should schools require disclosure of substantial generative-tool assistance? Define a workable rule and address authorship, privacy, accessibility, and enforcement."});
export { q, D, L, classroom };
export const SET45_CONFIGS = CONFIGS;
export const SET45_BANKS = Object.fromEntries(Object.entries(CONFIGS).map(([setNum, spans]) => [
  Number(setNum),
  Object.fromEntries(Object.entries(spans).map(([span, cfg]) => [span, makeBank(span, cfg)])),
]));
